In [1]:
import pandas as pd
import os 
import numpy as np

import gurobipy as gp
from gurobipy import GRB

dir = "/Users/rahulprakash/Desktop/Exam_Scheduling_Sp24/2023-2024"
os.chdir(dir)
os.listdir()

['Final_Exams2023.csv',
 '.DS_Store',
 '2023.ipynb',
 'StudentRegistration2023.csv',
 'Schedule2023.csv',
 'Class_Info2023.csv']

In [2]:
class_info2023 = pd.read_csv('Class_Info2023.csv')
registrar_schedule2023 = pd.read_csv("Final_Exams2023.csv") #The schedule the registrar implemented (used for comparison purposes)
student_registration2023 = pd.read_csv("StudentRegistration2023.csv") #registration for each student class schedule
exam_info2023 = pd.read_csv("Schedule2023.csv") #information on each class room enrollment

In [3]:
class_info2023['TIME_Column'] = pd.to_datetime(class_info2023['TIME'], format='%H:%M').dt.time
class_info2023

,BUILDING_CODE,BUILDING,ROOM_NUMBER,DAY_OF_WEEK,TIME,AVAILABLE_TO_SCHEDULE,ROOM_CAPACITY,ROOM_TYPE,TIME_Column
0,RZR,Rayzor Hall,227,U,06:50,Y,12,Classroom - Flexible/SCALAR,06:50:00
1,RZR,Rayzor Hall,227,U,07:00,Y,12,Classroom - Flexible/SCALAR,07:00:00
2,RZR,Rayzor Hall,227,U,07:10,Y,12,Classroom - Flexible/SCALAR,07:10:00
3,RZR,Rayzor Hall,227,U,07:20,Y,12,Classroom - Flexible/SCALAR,07:20:00
4,RZR,Rayzor Hall,227,U,07:30,Y,12,Classroom - Flexible/SCALAR,07:30:00
...,...,...,...,...,...,...,...,...,...
103098,PCF,Provisional Campus Facility,4,W,11:50,Y,90,Classroom - Flexible/SCALAR,11:50:00
103099,PCF,Provisional Campus Facility,4,W,12:00,Y,90,Classroom - Flexible/SCALAR,12:00:00
103100,PCF,Provisional Campus Facility,4,W,12:10,Y,90,Classroom - Flexible/SCALAR,12:10:00
103101,PCF,Provisional Campus Facility,4,W,12:20,Y,90,Classroom - Flexible/SCALAR,12:20:00
103102,PCF,Provisional Campus Facility,4,W,12:30,Y,90,Classroom - Flexible/SCALAR,12:30:00

In [4]:
class_info2023['TIME_FLOAT'] = class_info2023['TIME_Column'].apply(lambda x: float(f"{x.hour}.{x.minute:02d}"))
filtered_df = class_info2023[(class_info2023['TIME_FLOAT'] == 9.0) | (class_info2023['TIME_FLOAT'] == 14.0) | (class_info2023['TIME_FLOAT'] == 19.0)]
available_slots = filtered_df[(filtered_df['AVAILABLE_TO_SCHEDULE'] == 'Y')]


available_slots

,BUILDING_CODE,BUILDING,ROOM_NUMBER,DAY_OF_WEEK,TIME,AVAILABLE_TO_SCHEDULE,ROOM_CAPACITY,ROOM_TYPE,TIME_Column,TIME_FLOAT
13,RZR,Rayzor Hall,227,U,09:00,Y,12,Classroom - Flexible/SCALAR,09:00:00,9.0
43,RZR,Rayzor Hall,227,U,14:00,Y,12,Classroom - Flexible/SCALAR,14:00:00,14.0
73,RZR,Rayzor Hall,227,U,19:00,Y,12,Classroom - Flexible/SCALAR,19:00:00,19.0
156,RZR,Rayzor Hall,227,W,09:00,Y,12,Classroom - Flexible/SCALAR,09:00:00,9.0
186,RZR,Rayzor Hall,227,W,14:00,Y,12,Classroom - Flexible/SCALAR,14:00:00,14.0
...,...,...,...,...,...,...,...,...,...,...
102509,PCF,Provisional Campus Facility,4,R,09:00,Y,90,Classroom - Flexible/SCALAR,09:00:00,9.0
102539,PCF,Provisional Campus Facility,4,R,14:00,Y,90,Classroom - Flexible/SCALAR,14:00:00,14.0
102795,PCF,Provisional Campus Facility,4,T,09:00,Y,90,Classroom - Flexible/SCALAR,09:00:00,9.0
102825,PCF,Provisional Campus Facility,4,T,14:00,Y,90,Classroom - Flexible/SCALAR,14:00:00,14.0
103081,PCF,Provisional Campus Facility,4,W,09:00,Y,90,Classroom - Flexible/SCALAR,09:00:00,9.0

In [5]:
mapping = {'M': 1,
           'T': 2,
           'W': 3,
           'R': 4,
           'F': 5,
           'S': 6,
           'U': 7
}

mapping1 = {9.0: 'Morning',
            14.0: 'Afternoon',
            19.0: 'Evening'}

available_slots['DAY_OF_WEEK'] = available_slots['DAY_OF_WEEK'].map(mapping)
available_slots['TIME_OF_DAY'] = available_slots['TIME_FLOAT'].map(mapping1)
available_slots

/var/folders/xy/4pwp0wc90bd548jjl3c1y5mc0000gn/T/ipykernel_79229/4004836996.py:14: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  available_slots['DAY_OF_WEEK'] = available_slots['DAY_OF_WEEK'].map(mapping)
/var/folders/xy/4pwp0wc90bd548jjl3c1y5mc0000gn/T/ipykernel_79229/4004836996.py:15: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  available_slots['TIME_OF_DAY'] = available_slots['TIME_FLOAT'].map(mapping1)

,BUILDING_CODE,BUILDING,ROOM_NUMBER,DAY_OF_WEEK,TIME,AVAILABLE_TO_SCHEDULE,ROOM_CAPACITY,ROOM_TYPE,TIME_Column,TIME_FLOAT,TIME_OF_DAY
13,RZR,Rayzor Hall,227,7,09:00,Y,12,Classroom - Flexible/SCALAR,09:00:00,9.0,Morning
43,RZR,Rayzor Hall,227,7,14:00,Y,12,Classroom - Flexible/SCALAR,14:00:00,14.0,Afternoon
73,RZR,Rayzor Hall,227,7,19:00,Y,12,Classroom - Flexible/SCALAR,19:00:00,19.0,Evening
156,RZR,Rayzor Hall,227,3,09:00,Y,12,Classroom - Flexible/SCALAR,09:00:00,9.0,Morning
186,RZR,Rayzor Hall,227,3,14:00,Y,12,Classroom - Flexible/SCALAR,14:00:00,14.0,Afternoon
...,...,...,...,...,...,...,...,...,...,...,...
102509,PCF,Provisional Campus Facility,4,4,09:00,Y,90,Classroom - Flexible/SCALAR,09:00:00,9.0,Morning
102539,PCF,Provisional Campus Facility,4,4,14:00,Y,90,Classroom - Flexible/SCALAR,14:00:00,14.0,Afternoon
102795,PCF,Provisional Campus Facility,4,2,09:00,Y,90,Classroom - Flexible/SCALAR,09:00:00,9.0,Morning
102825,PCF,Provisional Campus Facility,4,2,14:00,Y,90,Classroom - Flexible/SCALAR,14:00:00,14.0,Afternoon
103081,PCF,Provisional Campus Facility,4,3,09:00,Y,90,Classroom - Flexible/SCALAR,09:00:00,9.0,Morning

In [11]:
#read all of the data and start the new version

In [6]:
person_schedule_map = {}

# Iterating through each row in the DataFrame
for index, row in student_registration2023.iterrows():
    person_id = row['PERSON_IDENTIFIER']
    course_code = row['SUBJECT'] + str(row['COURSE_NUMBER'])
    
    # Check if the person_id is already in the dictionary
    if person_id in person_schedule_map:
        # If present, append the course_code to the existing tuple
        person_schedule_map[person_id].add(course_code)
    else:
        # If not present, create a new entry in the dictionary
        person_schedule_map[person_id] = {course_code}

# To convert the sets to tuples for the final output as specified
person_schedule_map = {k: tuple(v) for k, v in person_schedule_map.items()}

person_schedule_map

{93423: ('THEA303',),
 94572: ('MUSI335',),
 361383: ('PORT106',),
 559884: ('JAPA141',),
 565527: ('FWIS184', 'RELI421'),
 566199: ('SOCI325', 'ENST312', 'PHIL400', 'LPAP171', 'LPAP183', 'HIST340'),
 607599: ('HIST438', 'HART358'),
 637395: ('ANTH200',),
 883479: ('JAPA141',),
 971649: ('PSYC202', 'KINE498', 'KINE302', 'KINE321'),
 975462: ('ASIA223',),
 1074561: ('HART203', 'COMP140', 'ENGL210', 'MATH101', 'FWIS100'),
 1107495: ('KINE498', 'KINE375', 'NAVA302', 'SMGT450', 'KINE302', 'KINE321'),
 1167519: ('MATH321', 'MATH356'),
 1235406: ('STAT413', 'STAT482', 'STAT487'),
 1292541: ('FREN263',),
 1305336: ('MUSI426', 'MUSI414'),
 1365753: ('KORE401',),
 1368495: ('COMP382', 'COMP480', 'COMP490', 'COMP310'),
 1370427: ('ECON483', 'ECON300', 'BUSI380', 'BUSI440', 'ECON441'),
 1378170: ('ARCH450',),
 1389207: ('GERM301',),
 1389840: ('PHYS311', 'CMOR420', 'HIST237', 'PHYS301'),
 1396599: ('ARCH450', 'ARCH327'),
 1423698: ('SMGT364', 'ASTR101', 'SOSC302', 'SMGT360', 'SMGT450', 'SOCI102'),
 1462875: ('ENGL382',),
 1470960: ('MUSI334',),
 1474185: ('LING327', 'PSYC308', 'HUMA315', 'PSYC340'),
 1474425: ('ARCH311', 'ARCH327'),
 1482525: ('ARCH327',),
 1512606: ('RELI334',),
 1514424: ('ECON481', 'MUSI117', 'BUSI401', 'SMGT450', 'ECON210'),
 1520835: ('ARCH450',),
 1522512: ('ARCH327', 'ARTS312'),
 1522686: ('COMP430', 'COMP431', 'HIST314', 'COMP412'),
 1522737: ('SWGS101', 'SWGS338', 'HART203', 'PSYC351', 'LALX238'),
 1523073: ('CMOR495',),
 1523136: ('ARCH450', 'ARCH350'),
 1524090: ('COLL114', 'LING300', 'PSYC467', 'LING327', 'PSYC375'),
 1524096: ('ARCH327',),
 1524828: ('ARCH450',),
 1525338: ('COMP382', 'LPAP186', 'LPAP183', 'BUSI221', 'COMP215'),
 1525632: ('PSYC409', 'PSYC308', 'PSYC340', 'COLL178'),
 1526673: ('BUSI401',),
 1526691: ('ARCH450',),
 1527726: ('RELI334', 'ENGL341', 'ENGL410', 'PSYC485'),
 1527843: ('MUSI141',),
 1528590: ('ARCH311', 'ARCH450'),
 1529172: ('ECON437', 'ECON483', 'COMP382', 'COMP341', 'COMP215'),
 1530069: ('FREN263',),
 1534368: ('ARCH311', 'FREN141'),
 1536762: ('SMGT376',
  'COLL186',
  'COLL178',
  'MUSI403',
  'BUSI360',
  'LPAP101',
  'MUSI317'),
 1537638: ('MUSI417', 'KORE263'),
 1538535: ('MUSI413',),
 1538583: ('MUSI413',),
 1539462: ('MUSI416',),
 1539846: ('MUSI413',),
 1540029: ('RCEL410', 'CHBE403', 'CHBE470', 'CHBE443', 'STAT305'),
 1542621: ('ENGL383', 'ENGL341', 'ENGL362', 'ENGL308'),
 1542753: ('ARCH450',),
 1546815: ('PSYC203', 'ELEC494', 'ELEC326', 'PHIL130'),
 1547430: ('SWGS101', 'BUSI440', 'ECON441'),
 1550775: ('HIST438', 'LPAP171', 'ASIA360', 'HIST340', 'ECON100', 'PHIL383'),
 1556151: ('STAT305', 'RELI101'),
 1566684: ('CEVE310', 'COMP462', 'COMP450', 'EEPS471'),
 1567764: ('MUCH238',),
 1574196: ('ARCH450',),
 1574883: ('PHYS311',),
 1577868: ('CMOR441', 'SPAN322', 'ENST301', 'CMOR422'),
 1580550: ('HEAL222', 'HEAL407', 'KINE319', 'ANTH381', 'HEAL379', 'HEAL380'),
 1586169: ('SWGS345', 'EDUC304', 'LPAP134', 'BIOS341', 'SPAN263'),
 1587384: ('RELI334', 'BUSI450'),
 1590321: ('EEPS480',),
 1590855: ('KORE141',),
 1592247: ('MUSI335',),
 1595265: ('CHEM492', 'HART358', 'CHEM415', 'CHEM462'),
 1595850: ('CHEM491', 'BIOS372', 'CHEM301', 'CMOR220', 'BIOS341', 'CHEM366'),
 1601052: ('COMP490', 'COMP301', 'COMP311', 'COMP382'),
 1601136: ('PHYS425',
  'ARTS312',
  'PHYS494',
  'PHYS411',
  'CMOR302',
  'MUSI342',
  'PHYS492'),
 1601559: ('LPAP113', 'ENST265', 'EEPS101', 'THEA308', 'EEPS115'),
 1602255: ('AWAY100',),
 1603413: ('AWAY100',),
 1603788: ('CHEM121', 'MECH484', 'CHEM123', 'MECH472', 'MECH407'),
 1604469: ('PSYC353', 'PSYC480', 'PSYC308', 'SOSC302'),
 1606719: ('PSYC332', 'COMP412', 'COLL184', 'MATH101', 'THEA308'),
 1607097: ('ELEC220', 'STAT499', 'COMP182', 'STAT315', 'CMOR302'),
 1607958: ('BIOS341',),
 1608000: ('HIST331', 'PJHC371', 'PLST305', 'LEAD402', 'POLI341', 'HUMA315'),
 1608210: ('PHYS311', 'ASTR350', 'EEPS115', 'PHYS301'),
 1608777: ('ECON200',),
 1608987: ('PSYC332',),
 1609092: ('SMGT320', 'HIST428', 'ENST250', 'HUMA134', 'ENST205'),
 1609287: ('STAT310', 'LPAP172', 'RCEL400', 'MECH472', 'MECH407'),
 1609941: ('COMP430', 'THEA300', 'SPAN142'),
 1609953: ('LING216', 'COMP450', 'COMP442', 'RELI333', 'COMP417'),
 1611006: ('MSNE477', 'CHBE403', 'LPAP170', 'CHBE470', 'CHBE443'),
 1611063: ('CEVE471', 'CEVE432', 'STAT310', 'CEVE431', 'CEVE472'),
 1611792: ('BIOS122', 'KINE300', 'LPAP138', 'NEUR310', 'NEUR383', 'BIOS341'),
 1611801: ('PSYC308', 'BIOS315', 'BIOS449', 'ECON299'),
 1611990: ('BIOS300', 'SOCI101', 'ENST205', 'BIOS332', 'EEPS110', 'ENGL304'),
 1612065: ('COMP430', 'STAT413', 'COMP412', 'STAT450'),
 1612089: ('JAPA301', 'HIST380', 'ASIA495', 'ASIA219', 'ASIA360'),
 1612113: ('ENGL301', 'HIST480', 'BIOE446', 'BIOE420', 'BIOS341'),
 1612188: ('MATH381', 'MATH304'),
 1614030: ('BIOE443', 'BIOE420', 'BIOE446', 'BIOE451'),
 1614294: ('MUSI445', 'MUSI285', 'MUSI413'),
 1616559: ('COMP310', 'COMP341', 'HART202', 'COMP412'),
 1617405: ('RELI334', 'HUMA134', 'HEAL407', 'ENGL301'),
 1618392: ('ARTS400', 'ARTS499'),
 1620102: ('BIOE440',),
 1623966: ('MUSI444',),
 1624902: ('LPAP113',
  'MUSI416',
  'MUSI337',
  'MUSI497',
  'LING305',
  'MUSI339',
  'MUSI338'),
 1625583: ('CHEM301', 'MUSI181', 'MUSI321', 'POLI326', 'CHEM366', 'BIOS301'),
 1627575: ('MUSI441',
  'MUSI337',
  'MUSI461',
  'ENST100',
  'EEPS115',
  'MUSI339',
  'MUSI421'),
 1628310: ('ITAL141',),
 1628364: ('MUSI426', 'MUSI414'),
 1628964: ('COMP430', 'COMP310', 'BUSI310', 'JAPA141'),
 1631604: ('BIOS310',),
 1637712: ('ARCH350',),
 1641042: ('CMOR451', 'CMOR422', 'CMOR441', 'CMOR490', 'ENST301', 'CMOR492'),
 1642536: ('BIOS372', 'BIOS314', 'BIOS310', 'LPAP144', 'BIOS341'),
 1645317: ('LPAP181', 'PHIL400', 'LPAP100', 'POLI359', 'POLI457', 'POLI211'),
 1645530: ('COMP412', 'COMP413', 'LPAP183', 'STAT315', 'COMP480', 'ASTR400'),
 1646148: ('LPAP113', 'MECH454', 'DSCI303', 'BUSI380', 'MECH407'),
 1646472: ('COMP430', 'LPAP108', 'COMP412', 'COMP318'),
 1647090: ('HIST275', 'SOSC444', 'PHIL125', 'HART202', 'POLI211'),
 1647840: ('UNIV212',),
 1648896: ('COMP412', 'BUSI420', 'FILM287', 'BUSI360', 'BUSI390', 'BUSI343'),
 1648980: ('FREN141', 'BIOE401', 'BIOS301'),
 1649298: ('LPAP113',
  'COLL178',
  'BIOS201',
  'AFSC101',
  'ANTH493',
  'LPAP170',
  'BIOS211',
  'ANTH203'),
 1649586: ('ECON437',
  'POLI338',
  'STAT499',
  'ECON299',
  'EEPS480',
  'LPAP100',
  'SOPA309',
  'STAT410',
  'LPAP170'),
 1650615: ('CHIN141', 'COMP341', 'COMP412', 'COMP382'),
 1653879: ('COMP412', 'ENGL301', 'LPAP178', 'COMP413', 'SOCI358'),
 1656129: ('ARTS301', 'ARTS388', 'ENGL360', 'ENGL410', 'ARTS325', 'ARTS499'),
 1658655: ('COMP424', 'ELEC240', 'ELEC494', 'COMP382', 'COMP430', 'ELEC303'),
 1661514: ('MATH300',
  'ARTS312',
  'MECH407',
  'LPAP183',
  'CMOR495',
  'COLL179',
  'LPAP134',
  'MECH477'),
 1662042: ('FREN141', 'GERM141', 'RELI421', 'ARCH225'),
 1663329: ('ARCH350',),
 1665615: ('CMOR451', 'LPAP180', 'CMOR462', 'DSCI435', 'HIST314'),
 1665942: ('SOCI381', 'SOCI101', 'LEAD402', 'SOCI411', 'SOCI380'),
 1666008: ('COMP341',),
 1666347: ('ENGL210', 'ENGL410', 'FILM432', 'ENGL222', 'ASIA380', 'ENGL398'),
 1667454: ('ECON200', 'ARCH105', 'BUSI305', 'ECON203'),
 1673316: ('LING401', 'GLHT201'),
 1675857: ('ENGI330', 'COMP412', 'LPAP100', 'HART202', 'COMP341', 'HIST259'),
 1675968: ('AWAY100',),
 1678683: ('NEUR383', 'BIOS315', 'PSYC332', 'BIOS128', 'COLL179', 'BIOS385'),
 1679589: ('ENGL301', 'ENGL269', 'LPAP138', 'DSCI435', 'SOPA400'),
 1679868: ('CEVE471',
  'CEVE320',
  'LPAP164',
  'CEVE476',
  'ARTS325',
  'CEVE481',
  'ARTS499',
  'CEVE472'),
 1681008: ('COMP382', 'SMGT432', 'COMP341', 'COMP215'),
 1681950: ('BIOS352',),
 1683786: ('PSYC321', 'PSYC461', 'ARTS325', 'PSYC480', 'PSYC485'),
 1684260: ('STAT425', 'STAT413', 'LING303'),
 1686864: ('COLL118',),
 1686894: ('SWGS338', 'HUMA134', 'SOCI380'),
 1686975: ('SMGT440', 'BUSI343', 'BUSI390', 'SMGT377'),
 1686978: ('POLI473', 'POLI416', 'POLI359'),
 1686981: ('BUSI420', 'BUSI450', 'LPAP101', 'BUSI401', 'JAPA141'),
 1686984: ('SMGT440', 'SMGT360', 'BUSI430', 'SMGT377'),
 1687323: ('LING401',
  'BIOS128',
  'LPAP172',
  'BIOS329',
  'BIOS318',
  'ENGL272',
  'BIOS213',
  'STAT305'),
 1688049: ('MUSI472', 'MUSI413'),
 1688550: ('LPAP106', 'RCEL436', 'JAPA141', 'ELEC425', 'ELEC406'),
 1689534: ('STAT487', 'STAT310', 'COMP182', 'BIOE446', 'BIOE451', 'DSCI435'),
 1691613: ('BIOS318', 'FREN263', 'BIOS310', 'BIOS341'),
 1691640: ('CEVE314', 'ENST205', 'BUSI380', 'ARAB141', 'RCEL440', 'BUSI343'),
 1692360: ('CMOR495',),
 1693074: ('ELEC494', 'ELEC424', 'ELEC425', 'ELEC450', 'PHIL383'),
 1694478: ('BIOS470', 'ENGL301', 'SPAN321', 'MDHM402'),
 1694826: ('SPAN321',),
 1694967: ('BIOS128', 'BIOS385', 'BIOS215', 'ENGL272', 'NEUR383', 'PHIL130'),
 1695105: ('HEAL460',
  'BIOS372',
  'HEAL407',
  'STAT280',
  'PHYS125',
  'HONS470',
  'HEAL380'),
 1695576: ('COMP490',
  'MECH343',
  'MECH332',
  'MECH371',
  'THEA331',
  'MATH355',
  'MECH203'),
 1695699: ('BIOE447',
  'UNIV330',
  'SOCI231',
  'BIOE492',
  'BIOE451',
  'BIOE400',
  'BIOE443'),
 1695996: ('AWAY100',),
 1696338: ('CEVE314', 'CEVE432', 'LPAP186', 'CEVE431', 'EEPS101', 'CEVE481'),
 1696617: ('UNIV195',
  'ECON483',
  'DSCI301',
  'ECON300',
  'UNIV194',
  'BUSI296',
  'BUSI310'),
 1696632: ('COMP412', 'COMP301', 'MUSI117', 'CHIN206', 'COMP318'),
 1696860: ('MECH202', 'BIOE383', 'BIOE400', 'BIOE370', 'BIOE341', 'BIOE385'),
 1697631: ('BUSI430', 'SMGT320', 'BUSI420', 'HIST259', 'BUSI343'),
 1698729: ('STAT425', 'DSCI304', 'STAT418', 'STAT487'),
 1699761: ('COLL180',
  'ENGL493',
  'ENGL383',
  'ENGL410',
  'ENST205',
  'BIOS330',
  'LPAP144'),
 1702512: ('BIOS122', 'PSYC202', 'PSYC375', 'PSYC351'),
 1703094: ('SPAN264', 'PLST401', 'HIST428', 'SOCI358'),
 1703124: ('LPAP175',
  'HEAL460',
  'HEAL407',
  'MDHM359',
  'BUSI360',
  'LPAP170',
  'KINE301',
  'HEAL380'),
 1703220: ('PHYS461', 'PHYS413', 'PHYS301', 'MATH381', 'PHYS311'),
 1703286: ('BIOE447', 'MDHM430', 'BIOE392', 'ENGL272', 'BIOE451', 'ANTH381'),
 1703352: ('ASTR101', 'FREN402', 'PLST305', 'PHIL373', 'BUSI343'),
 1703484: ('SOPA309', 'POLI210', 'HONS470', 'DSCI304', 'SOPA400'),
 1703559: ('COMP382', 'STAT482', 'STAT410', 'COMP215', 'BUSI343'),
 1703604: ('HIST275',
  'MSNE304',
  'MSNE477',
  'MSNE402',
  'LPAP180',
  'PSYC101',
  'CHBE468'),
 1703673: ('ELEC326', 'SPAN368', 'BIOE451', 'BIOE400', 'BIOE420'),
 1703679: ('ENGL301', 'COMP412', 'COMP490', 'NEUR383', 'LPAP144'),
 1703718: ('BIOS385', 'NEUR310', 'HART202', 'BIOS372'),
 1703826: ('SOCI325', 'SMGT376', 'SMGT440', 'BUSI401', 'HUMA309', 'LPAP110'),
 1703907: ('COMP412', 'STAT413', 'LPAP182', 'COMP301', 'STAT418', 'STAT449'),
 1703931: ('HIST438', 'POLI321', 'HIST372', 'POLI341', 'PLST307'),
 1704045: ('LPAP106', 'HIST438', 'HIST332', 'EEPS480', 'ECON481', 'STAT487'),
 1704087: ('FREN263',
  'MUSI441',
  'MUSI337',
  'BIOS329',
  'LPAP144',
  'MUSI493',
  'MUSI339'),
 1704282: ('ENGL305', 'BIOS318', 'BIOS310', 'LPAP170', 'BIOS344', 'BIOS341'),
 1704336: ('MATH300', 'LPAP194', 'LPAP172', 'ELEC424', 'ELEC425', 'MUSI317'),
 1704339: ('LING300', 'RELI120', 'LEAD402', 'BUSI380', 'ARAB263'),
 1704351: ('AWAY100',),
 1704513: ('SWGS345', 'LPAP164', 'BIOS353', 'BIOS318', 'SWGS477'),
 1704561: ('STAT310', 'ENGI355', 'MECH484', 'MECH472', 'MECH407'),
 1704582: ('MECH490', 'MECH472', 'STAT487', 'MECH407', 'MECH477'),
 1704600: ('ASIA378',
  'LPAP172',
  'ASIA380',
  'ASIA495',
  'ASIA305',
  'JAPA401',
  'KORE141'),
 1704633: ('CHEM492', 'CHEM330', 'CMOR495', 'CHEM415', 'CHEM462', 'CHEM452'),
 1704648: ('ECON437', 'CMOR422', 'CMOR420', 'LPAP186', 'SOSC445', 'CMOR492'),
 1704654: ('COMP480', 'LPAP113', 'MATH356', 'DSCI435'),
 1704660: ('BIOE400', 'BIOE447', 'BIOE420', 'BIOE451'),
 1704729: ('SMGT364', 'ENGL305', 'ANTH324', 'SMGT379', 'LPAP110', 'SPAN263'),
 1704756: ('BIOS372',
  'CHEM215',
  'KINE320',
  'BIOS311',
  'BIOS310',
  'BIOS344',
  'BIOS341'),
 1704771: ('CMST203', 'COMP412', 'PSYC409', 'COMP301', 'COMP318'),
 1704837: ('ENGL301', 'STAT280', 'KINE302', 'KINE441', 'KINE321'),
 1704843: ('CMOR220', 'MATH300', 'CMOR302', 'ITAL301'),
 1704873: ('COLL175',
  'LPAP113',
  'ELEC494',
  'ELEC461',
  'ELEC462',
  'COLL156',
  'ELEC361'),
 1704984: ('ARTS311', 'LPAP178', 'ARTS499', 'BIOS341', 'BIOS211', 'MATH102'),
 1705275: ('LPAP181', 'ASTR101', 'LATI310', 'ENGL304', 'ARTS225'),
 1705290: ('BIOS372', 'MDHM430', 'BIOS314', 'LPAP144', 'ANTH205', 'MDHM238'),
 1705404: ('KINE440', 'STAT280', 'BIOS318', 'LPAP138', 'POLI326', 'BIOS344'),
 1705419: ('LPAP181',
  'ENST250',
  'COLL167',
  'THEA308',
  'GLHT201',
  'COLL179',
  'ARCH311',
  'PSYC485'),
 1705452: ('ECON437', 'BIOS341', 'BUSI380', 'SMGT362'),
 1705518: ('STAT310', 'LPAP100', 'MECH472', 'MECH407', 'BUSI310', 'MECH477'),
 1705539: ('SPAN436', 'LING216', 'ARCH105', 'GLHT201', 'CHIN301'),
 1705566: ('MECH407', 'CMST203', 'STAT310', 'MECH472'),
 1705605: ('COMP413', 'COMP341', 'COMP429', 'COMP412'),
 1705770: ('MECH490',
  'ITAL141',
  'LPAP100',
  'MECH472',
  'ENGL398',
  'MECH407',
  'MECH477'),
 1705773: ('MECH407', 'CMOR420', 'MECH484', 'MECH472'),
 1705821: ('LPAP105', 'HART321', 'THEA309', 'THEA314', 'BIOS423'),
 1705833: ('ARCH401', 'SPAN406', 'COLL156', 'ARCH403', 'COLL300'),
 1705851: ('KINE310', 'KINE499', 'PHYS125', 'KINE441', 'BIOS301'),
 1705854: ('HIST275', 'HIST372', 'HIST319', 'LPAP118', 'HIST314'),
 1705977: ('LPAP108', 'RELI307', 'THEA309', 'THEA300', 'THEA314'),
 1706034: ('MUSI335',
  'MUSI416',
  'MUSI403',
  'MUSI303',
  'MUSI381',
  'MUSI401',
  'RELI101'),
 1706124: ('NEUR383',
  'SPAN322',
  'BIOS128',
  'HIST312',
  'BIOS385',
  'LPAP134',
  'HEAL380'),
 1706172: ('LPAP182', 'STAT310', 'ENGL308', 'MECH472', 'MECH407'),
 1706376: ('PSYC332',
  'CMOR422',
  'SPAN141',
  'COLL184',
  'LPAP138',
  'STAT449',
  'COLL179',
  'CMOR492'),
 1706379: ('COMP424', 'COLL180', 'COMP382', 'COMP341', 'PSYC101', 'BUSI310'),
 1706592: ('LPAP106',
  'UNIV212',
  'BIOS318',
  'SPAN368',
  'CHEM330',
  'BIOS344',
  'BIOS341'),
 1706610: ('CEVE302', 'CEVE400', 'CEVE481', 'JAPA401', 'ASIA219'),
 1706628: ('KINE440', 'PSYC321', 'KINE310', 'KINE320', 'BIOS329', 'KINE311'),
 1706688: ('ENGL493',
  'ENGL305',
  'ENGL410',
  'ANTH344',
  'MDHM359',
  'LPAP183',
  'MDHM201'),
 1706691: ('COLL180', 'LPAP108', 'ENGL301', 'COMP412', 'COMP382'),
 1706706: ('STAT425', 'SOCI411', 'STAT418', 'SOCI492'),
 1706736: ('COLL186',
  'ASTR102',
  'DSCI305',
  'MUSI334',
  'STAT487',
  'DSCI435',
  'RELI111'),
 1706751: ('STAT425', 'JAPA301', 'STAT413', 'STAT449', 'DSCI304'),
 1706796: ('COMP412', 'DSCI305', 'LPAP182', 'COMP416', 'COMP449'),
 1706919: ('ARTS311', 'ENGL410', 'POLI210', 'ENGL308', 'ARTS325', 'ARTS499'),
 1707003: ('PSYC430', 'PSYC461', 'DSCI303', 'LPAP135', 'PSYC499'),
 1707015: ('SOCI409', 'SOCI459', 'BUSI380', 'SOCI411'),
 1707060: ('LING200',
  'LPAP194',
  'EEPS481',
  'EEPS401',
  'ENST100',
  'FILM327',
  'EEPS322'),
 1707069: ('CHEM391', 'BIOS352', 'LPAP183', 'CHEM415', 'BIOS341', 'MDHM201'),
 1707105: ('LPAP164', 'LPAP172', 'BUSI450', 'BUSI401', 'ARCH311', 'BUSI222'),
 1707153: ('ELEC326', 'ELEC494', 'COLL184', 'LPAP135', 'ELEC303', 'ELEC425'),
 1707159: ('PSYC461', 'PSYC340', 'PSYC480', 'ENGL274', 'PSYC485'),
 1707168: ('COMP382', 'ENGL410', 'COMP412', 'ENGL398'),
 1707201: ('BIOS470', 'SPAN436', 'CHEM330', 'BIOS327', 'KORE263', 'BIOS301'),
 1707309: ('HEAL460',
  'CHEM313',
  'HEAL407',
  'BIOS329',
  'CHEM314',
  'BIOS310',
  'BIOS341'),
 1707324: ('BIOE392', 'ENGI301', 'BIOE492', 'LPAP183', 'BIOE451'),
 1707345: ('PSYC480', 'PLST401', 'PSYC332', 'PSYC485'),
 1707426: ('COMP430', 'LPAP194', 'COMP412', 'COMP429'),
 1707510: ('ENGL301',
  'ASTR101',
  'CMST201',
  'LPAP172',
  'ENGL308',
  'SPAN406',
  'COLL167'),
 1707525: ('PSYC332', 'PSYC353', 'PSYC480', 'PSYC330', 'ARAB141', 'KORE263'),
 1707534: ('COMP490', 'COMP430', 'ENST301', 'MDHM359', 'COMP318'),
 1707642: ('CHEM491', 'JAPA301', 'CHEM367', 'CHEM330', 'CHEM452'),
 1707651: ('COMP382', 'COMP490', 'COMP301', 'STAT310', 'LPAP101'),
 1707702: ('BIOS352', 'ENGL113', 'BIOS310', 'PHIL470', 'PHIL220'),
 1707783: ('LING300', 'PSYC321', 'LING401', 'LING397', 'HIST101'),
 1707897: ('LING200', 'PSYC353', 'PSYC308', 'PSYC485', 'MDHM238'),
 1707921: ('SPAN350', 'CMOR492', 'SPAN453', 'LPAP110'),
 1707963: ('BIOS352', 'BIOS311', 'PHIL460', 'BIOS318', 'BIOS344'),
 1707999: ('ENGL493', 'ANTH346', 'ENGL383', 'ENGL410', 'ENGL304'),
 1708092: ('COMP140', 'CEVE310', 'STAT315', 'EEPS110', 'MATH355'),
 1708164: ('BIOS204', 'HEAL460', 'LPAP190'),
 1708230: ('BUSI430',
  'BUSI420',
  'LPAP180',
  'BUSI499',
  'PSYC308',
  'ECON210',
  'COLL200',
  'PHIL130'),
 1708290: ('MUSI335',
  'ARTS388',
  'CMOR304',
  'MECH332',
  'HART366',
  'MECH371',
  'MECH477'),
 1708323: ('COMP424', 'COMP412', 'COMP416', 'THEA309', 'COMP390'),
 1708359: ('LPAP181', 'MECH454', 'MECH332', 'MECH407', 'HIST101', 'RELI101'),
 1708389: ('MECH400', 'MECH343', 'MECH454', 'STAT315', 'CMOR360'),
 1708437: ('ECON422', 'LING205', 'ECON209', 'LPAP134', 'SOPA400'),
 1708578: ('HART358', 'ARCH401', 'HIST340', 'ARCH403'),
 1708632: ('MECH454', 'LPAP190', 'MECH407', 'KORE141', 'MECH477'),
 1708653: ('BUSI420', 'STAT499', 'FILM373', 'ENGL362', 'LPAP110', 'SOCI358'),
 1708668: ('COMP311', 'COMP310', 'COMP382', 'COMP490'),
 1708833: ('KINE320', 'SOCI309', 'BIOS310', 'KINE302', 'KINE311', 'LALX158'),
 1708848: ('LALX332',
  'BIOS128',
  'BIOS314',
  'BIOS332',
  'BIOS310',
  'COLL179',
  'BIOS341'),
 1708884: ('FREN141', 'COMP412', 'COMP382', 'COLL108', 'COMP318'),
 1708920: ('XCHG100',),
 1708968: ('RELI219', 'CHBE403', 'CHBE470', 'CHBE443'),
 1708980: ('COMP412', 'COMP430', 'COLL185', 'COLL172', 'BUSI222'),
 1709067: ('BUSI461', 'COMP431', 'COMP215', 'COMP382'),
 1709136: ('ANTH340', 'LPAP118', 'BIOS344', 'BIOS341', 'ANTH321'),
 1709280: ('LPAP102', 'PLST401', 'ECON210', 'ANTH203', 'ANTH303', 'SOPA400'),
 1709313: ('HEAL407', 'KINE440', 'KINE498', 'KINE375'),
 1709385: ('STAT425', 'MATH300', 'COMP490', 'MATH370', 'COMP442'),
 1709388: ('ARCH401', 'SPAN406', 'ARCH403'),
 1709526: ('ELEC478', 'COMP442', 'COMP412', 'BUSI222'),
 1709733: ('LPAP118', 'STAT310', 'MECH484', 'MECH472', 'MECH407'),
 1709781: ('CEVE302',
  'CEVE314',
  'LPAP120',
  'LPAP100',
  'CEVE481',
  'EEPS115',
  'ARCH225'),
 1710000: ('STAT425', 'LING200', 'LPAP172', 'MATH425', 'PHIL130'),
 1710018: ('STAT405', 'ECON483', 'ECON481', 'SOPA400', 'ECON441', 'RELI101'),
 1710177: ('MECH407', 'ARCH311', 'MECH484', 'MECH472'),
 1710267: ('HEAL460', 'PSYC321', 'MDHM430', 'EMSP281', 'KINE302', 'KINE321'),
 1710303: ('MECH371', 'CMOR304', 'BUSI310', 'ANTH344'),
 1710315: ('NEUR383', 'SPAN356', 'SPAN368', 'PSYC351', 'BIOS385'),
 1710339: ('STAT425', 'LPAP164', 'PSYC231', 'STAT487', 'LPAP118', 'STAT450'),
 1710375: ('ECON437', 'HIST331', 'BUSI305', 'HUMA310', 'CMOR360'),
 1710408: ('LPAP183', 'MECH484', 'MECH472', 'MECH407', 'STAT305'),
 1710471: ('COMP412', 'COLL183', 'SMGT432', 'LPAP110'),
 1710474: ('MATH211', 'CHEM301', 'MATH212', 'BIOS301'),
 1710561: ('ECON305', 'ENGL301', 'ECON310', 'ECON481'),
 1710645: ('HIST331', 'LPAP182', 'SPAN436', 'ARTS401', 'SOCI309'),
 1710654: ('LPAP120', 'MECH454', 'STAT310', 'PSYC202', 'MECH407', 'ANTH203'),
 1710732: ('KINE440',
  'BIOS352',
  'KINE310',
  'LPAP101',
  'BIOS318',
  'BIOS310',
  'KINE321'),
 1710894: ('STAT425', 'STAT413', 'LPAP186', 'LPAP170', 'COLL167', 'DSCI304'),
 1710972: ('ELEC494', 'ELEC430', 'ELEC424', 'ELEC425', 'COLL200'),
 1710996: ('UNIV330', 'ENGI301', 'PSYC203', 'BIOE446', 'BIOE451'),
 1711143: ('HIST331', 'HIST291', 'BUSI450', 'PSYC202', 'BUSI401'),
 1711311: ('STAT425', 'MDHM359', 'HONS470', 'MATH425', 'COMP318'),
 1711326: ('STAT425', 'MATH356', 'STAT413', 'STAT418', 'STAT487'),
 1711362: ('ANTH493', 'SPAN142', 'ASIA305', 'BIOS341', 'BIOS211', 'ANTH357'),
 1711368: ('PHYS425', 'PHIL125', 'PHYS491', 'PHIL230', 'PHYS493', 'CMOR302'),
 1711383: ('SMGT440', 'SMGT364', 'BUSI430', 'BUSI450'),
 1711557: ('HEAL132', 'BIOS341', 'KINE440', 'BIOS310', 'LPAP110', 'ARCH311'),
 1711602: ('SMGT377', 'SMGT440', 'ARCH225', 'SMGT362', 'BUSI343'),
 1711650: ('CHEM313', 'BIOS312', 'BIOS329', 'LPAP138', 'CHEM314', 'FILM324'),

In [7]:
schedule_counts = {}

for schedule in person_schedule_map.values():
    # Sort the schedules to ensure that the same courses in different orders are considered the same
    sorted_schedule = tuple(sorted(schedule))
    if sorted_schedule in schedule_counts:
        schedule_counts[sorted_schedule] += 1
    else:
        schedule_counts[sorted_schedule] = 1

# Count of unique schedules
num_of_unique_schedules = len(schedule_counts)
print(schedule_counts)
print(num_of_unique_schedules)

{('THEA303',): 1, ('MUSI335',): 2, ('PORT106',): 2, ('JAPA141',): 5, ('FWIS184', 'RELI421'): 1, ('ENST312', 'HIST340', 'LPAP171', 'LPAP183', 'PHIL400', 'SOCI325'): 1, ('HART358', 'HIST438'): 1, ('ANTH200',): 1, ('KINE302', 'KINE321', 'KINE498', 'PSYC202'): 1, ('ASIA223',): 1, ('COMP140', 'ENGL210', 'FWIS100', 'HART203', 'MATH101'): 1, ('KINE302', 'KINE321', 'KINE375', 'KINE498', 'NAVA302', 'SMGT450'): 1, ('MATH321', 'MATH356'): 1, ('STAT413', 'STAT482', 'STAT487'): 1, ('FREN263',): 5, ('MUSI414', 'MUSI426'): 2, ('KORE401',): 1, ('COMP310', 'COMP382', 'COMP480', 'COMP490'): 1, ('BUSI380', 'BUSI440', 'ECON300', 'ECON441', 'ECON483'): 1, ('ARCH450',): 18, ('GERM301',): 1, ('CMOR420', 'HIST237', 'PHYS301', 'PHYS311'): 1, ('ARCH327', 'ARCH450'): 1, ('ASTR101', 'SMGT360', 'SMGT364', 'SMGT450', 'SOCI102', 'SOSC302'): 1, ('ENGL382',): 1, ('MUSI334',): 1, ('HUMA315', 'LING327', 'PSYC308', 'PSYC340'): 1, ('ARCH311', 'ARCH327'): 1, ('ARCH327',): 4, ('RELI334',): 1, ('BUSI401', 'ECON210', 'ECON481', 'MUSI117', 'SMGT450'): 1, ('ARCH327', 'ARTS312'): 1, ('COMP412', 'COMP430', 'COMP431', 'HIST314'): 1, ('HART203', 'LALX238', 'PSYC351', 'SWGS101', 'SWGS338'): 1, ('CMOR495',): 6, ('ARCH350', 'ARCH450'): 1, ('COLL114', 'LING300', 'LING327', 'PSYC375', 'PSYC467'): 1, ('BUSI221', 'COMP215', 'COMP382', 'LPAP183', 'LPAP186'): 1, ('COLL178', 'PSYC308', 'PSYC340', 'PSYC409'): 1, ('BUSI401',): 1, ('ENGL341', 'ENGL410', 'PSYC485', 'RELI334'): 1, ('MUSI141',): 2, ('ARCH311', 'ARCH450'): 1, ('COMP215', 'COMP341', 'COMP382', 'ECON437', 'ECON483'): 1, ('ARCH311', 'FREN141'): 1, ('BUSI360', 'COLL178', 'COLL186', 'LPAP101', 'MUSI317', 'MUSI403', 'SMGT376'): 1, ('KORE263', 'MUSI417'): 1, ('MUSI413',): 6, ('MUSI416',): 1, ('CHBE403', 'CHBE443', 'CHBE470', 'RCEL410', 'STAT305'): 1, ('ENGL308', 'ENGL341', 'ENGL362', 'ENGL383'): 1, ('ELEC326', 'ELEC494', 'PHIL130', 'PSYC203'): 1, ('BUSI440', 'ECON441', 'SWGS101'): 1, ('ASIA360', 'ECON100', 'HIST340', 'HIST438', 'LPAP171', 'PHIL383'): 1, ('RELI101', 'STAT305'): 1, ('CEVE310', 'COMP450', 'COMP462', 'EEPS471'): 1, ('MUCH238',): 1, ('PHYS311',): 2, ('CMOR422', 'CMOR441', 'ENST301', 'SPAN322'): 1, ('ANTH381', 'HEAL222', 'HEAL379', 'HEAL380', 'HEAL407', 'KINE319'): 1, ('BIOS341', 'EDUC304', 'LPAP134', 'SPAN263', 'SWGS345'): 1, ('BUSI450', 'RELI334'): 1, ('EEPS480',): 1, ('KORE141',): 4, ('CHEM415', 'CHEM462', 'CHEM492', 'HART358'): 1, ('BIOS341', 'BIOS372', 'CHEM301', 'CHEM366', 'CHEM491', 'CMOR220'): 1, ('COMP301', 'COMP311', 'COMP382', 'COMP490'): 1, ('ARTS312', 'CMOR302', 'MUSI342', 'PHYS411', 'PHYS425', 'PHYS492', 'PHYS494'): 1, ('EEPS101', 'EEPS115', 'ENST265', 'LPAP113', 'THEA308'): 1, ('AWAY100',): 58, ('CHEM121', 'CHEM123', 'MECH407', 'MECH472', 'MECH484'): 1, ('PSYC308', 'PSYC353', 'PSYC480', 'SOSC302'): 1, ('COLL184', 'COMP412', 'MATH101', 'PSYC332', 'THEA308'): 1, ('CMOR302', 'COMP182', 'ELEC220', 'STAT315', 'STAT499'): 1, ('BIOS341',): 2, ('HIST331', 'HUMA315', 'LEAD402', 'PJHC371', 'PLST305', 'POLI341'): 1, ('ASTR350', 'EEPS115', 'PHYS301', 'PHYS311'): 1, ('ECON200',): 1, ('PSYC332',): 1, ('ENST205', 'ENST250', 'HIST428', 'HUMA134', 'SMGT320'): 1, ('LPAP172', 'MECH407', 'MECH472', 'RCEL400', 'STAT310'): 1, ('COMP430', 'SPAN142', 'THEA300'): 1, ('COMP417', 'COMP442', 'COMP450', 'LING216', 'RELI333'): 1, ('CHBE403', 'CHBE443', 'CHBE470', 'LPAP170', 'MSNE477'): 1, ('CEVE431', 'CEVE432', 'CEVE471', 'CEVE472', 'STAT310'): 1, ('BIOS122', 'BIOS341', 'KINE300', 'LPAP138', 'NEUR310', 'NEUR383'): 1, ('BIOS315', 'BIOS449', 'ECON299', 'PSYC308'): 1, ('BIOS300', 'BIOS332', 'EEPS110', 'ENGL304', 'ENST205', 'SOCI101'): 1, ('COMP412', 'COMP430', 'STAT413', 'STAT450'): 1, ('ASIA219', 'ASIA360', 'ASIA495', 'HIST380', 'JAPA301'): 1, ('BIOE420', 'BIOE446', 'BIOS341', 'ENGL301', 'HIST480'): 1, ('MATH304', 'MATH381'): 1, ('BIOE420', 'BIOE443', 'BIOE446', 'BIOE451'): 1, ('MUSI285', 'MUSI413', 'MUSI445'): 1, ('COMP310', 'COMP341', 'COMP412', 'HART202'): 1, ('ENGL301', 'HEAL407', 'HUMA134', 'RELI334'): 1, ('ARTS400', 'ARTS499'): 1, ('BIOE440',): 2, ('MUSI444',): 9, ('LING305', 'LPAP113', 'MUSI337', 'MUSI338', 'MUSI339', 'MUSI416', 'MUSI497'): 1, ('BIOS301', 'CHEM301', 'CHEM366', 'MUSI181', 'MUSI321', 'POLI326'): 1, ('EEPS115', 'ENST100', 'MUSI337', 'MUSI339', 'MUSI421', 'MUSI441', 'MUSI461'): 1, ('ITAL141',): 4, ('BUSI310', 'COMP310', 'COMP430', 'JAPA141'): 1, ('BIOS310',): 1, ('ARCH350',): 9, ('CMOR422', 'CMOR441', 'CMOR451', 'CMOR490', 'CMOR492', 'ENST301'): 1, ('BIOS310', 'BIOS314', 'BIOS341', 'BIOS372', 'LPAP144'): 1, ('LPAP100', 'LPAP181', 'PHIL400', 'POLI211', 'POLI359', 'POLI457'): 1, ('ASTR400', 'COMP412', 'COMP413', 'COMP480', 'LPAP183', 'STAT315'): 1, ('BUSI380', 'DSCI303', 'LPAP113', 'MECH407', 'MECH454'): 1, ('COMP318', 'COMP412', 'COMP430', 'LPAP108'): 1, ('HART202', 'HIST275', 'PHIL125', 'POLI211', 'SOSC444'): 1, ('UNIV212',): 1, ('BUSI343', 'BUSI360', 'BUSI390', 'BUSI420', 'COMP412', 'FILM287'): 1, ('BIOE401', 'BIOS301', 'FREN141'): 1, ('AFSC101', 'ANTH203', 'ANTH493', 'BIOS201', 'BIOS211', 'COLL178', 'LPAP113', 'LPAP170'): 1, ('ECON299', 'ECON437', 'EEPS480', 'LPAP100', 'LPAP170', 'POLI338', 'SOPA309', 'STAT410', 'STAT499'): 1, ('CHIN141', 'COMP341', 'COMP382', 'COMP412'): 1, ('COMP412', 'COMP413', 'ENGL301', 'LPAP178', 'SOCI358'): 1, ('ARTS301', 'ARTS325', 'ARTS388', 'ARTS499', 'ENGL360', 'ENGL410'): 1, ('COMP382', 'COMP424', 'COMP430', 'ELEC240', 'ELEC303', 'ELEC494'): 1, ('ARTS312', 'CMOR495', 'COLL179', 'LPAP134', 'LPAP183', 'MATH300', 'MECH407', 'MECH477'): 1, ('ARCH225', 'FREN141', 'GERM141', 'RELI421'): 1, ('CMOR451', 'CMOR462', 'DSCI435', 'HIST314', 'LPAP180'): 1, ('LEAD402', 'SOCI101', 'SOCI380', 'SOCI381', 'SOCI411'): 1, ('COMP341',): 2, ('ASIA380', 'ENGL210', 'ENGL222', 'ENGL398', 'ENGL410', 'FILM432'): 1, ('ARCH105', 'BUSI305', 'ECON200', 'ECON203'): 1, ('GLHT201', 'LING401'): 1, ('COMP341', 'COMP412', 'ENGI330', 'HART202', 'HIST259', 'LPAP100'): 1, ('BIOS128', 'BIOS315', 'BIOS385', 'COLL179', 'NEUR383', 'PSYC332'): 1, ('DSCI435', 'ENGL269', 'ENGL301', 'LPAP138', 'SOPA400'): 1, ('ARTS325', 'ARTS499', 'CEVE320', 'CEVE471', 'CEVE472', 'CEVE476', 'CEVE481', 'LPAP164'): 1, ('COMP215', 'COMP341', 'COMP382', 'SMGT432'): 1, ('BIOS352',): 3, ('ARTS325', 'PSYC321', 'PSYC461', 'PSYC480', 'PSYC485'): 1, ('LING303', 'STAT413', 'STAT425'): 1, ('COLL118',): 1, ('HUMA134', 'SOCI380', 'SWGS338'): 1, ('BUSI343', 'BUSI390', 'SMGT377', 'SMGT440'): 1, ('POLI359', 'POLI416', 'POLI473'): 1, ('BUSI401', 'BUSI420', 'BUSI450', 'JAPA141', 'LPAP101'): 1, ('BUSI430', 'SMGT360', 'SMGT377', 'SMGT440'): 1, ('BIOS128', 'BIOS213', 'BIOS318', 'BIOS329', 'ENGL272', 'LING401', 'LPAP172', 'STAT305'): 1, ('MUSI413', 'MUSI472'): 1, ('ELEC406', 'ELEC425', 'JAPA141', 'LPAP106', 'RCEL436'): 1, ('BIOE446', 'BIOE451', 'COMP182', 'DSCI435', 'STAT310', 'STAT487'): 1, ('BIOS310', 'BIOS318', 'BIOS341', 'FREN263'): 1, ('ARAB141', 'BUSI343', 'BUSI380', 'CEVE314', 'ENST205', 'RCEL440'): 1, ('ELEC424', 'ELEC425', 'ELEC450', 'ELEC494', 'PHIL383'): 1, ('BIOS470', 'ENGL301', 'MDHM402', 'SPAN321'): 1, ('SPAN321',): 1, ('BIOS128', 'BIOS215', 'BIOS385', 'ENGL272', 'NEUR383', 'PHIL130'): 1, ('BIOS372', 'HEAL380', 'HEAL407', 'HEAL460', 'HONS470', 'PHYS125', 'STAT280'): 1, ('COMP490', 'MATH355', 'MECH203', 'MECH332', 'MECH343', 'MECH371', 'THEA331'): 1, ('BIOE400', 'BIOE443', 'BIOE447', 'BIOE451', 'BIOE492', 'SOCI231', 'UNIV330'): 1, ('CEVE314', 'CEVE431', 'CEVE432', 'CEVE481', 'EEPS101', 'LPAP186'): 1, ('BUSI296', 'BUSI310', 'DSCI301', 'ECON300', 'ECON483', 'UNIV194', 'UNIV195'): 1, ('CHIN206', 'COMP301', 'COMP318', 'COMP412', 'MUSI117'): 1, ('BIOE341', 'BIOE370', 'BIOE383', 'BIOE385', 'BIOE400', 'MECH202'): 3, ('BUSI343', 'BUSI420', 'BUSI430', 'HIST259', 'SMGT320'): 1, ('DSCI304', 'STAT418', 'STAT425', 'STAT487'): 1, ('BIOS330', 'COLL180', 'ENGL383', 'ENGL410', 'ENGL493', 'ENST205', 'LPAP144'): 1, ('BIOS122', 'PSYC202', 'PSYC351', 'PSYC375'): 1, ('HIST428', 'PLST401', 'SOCI358', 'SPAN264'): 1, ('BUSI360', 'HEAL380', 'HEAL407', 'HEAL460', 'KINE301', 'LPAP170', 'LPAP175', 'MDHM359'): 1, ('MATH381', 'PHYS301', 'PHYS311', 'PHYS413', 'PHYS461'): 1, ('ANTH381', 'BIOE392', 'BIOE447', 'BIOE451', 'ENGL272', 'MDHM430'): 1, ('ASTR101', 'BUSI343', 'FREN402', 'PHIL373', 'PLST305'): 1, ('DSCI304', 'HONS470', 'POLI210', 'SOPA309', 'SOPA400'): 1, ('BUSI343', 'COMP215', 'COMP382', 'STAT410', 'STAT482'): 1, ('CHBE468', 'HIST275', 'LPAP180', 'MSNE304', 'MSNE402', 'MSNE477', 'PSYC101'): 1, ('BIOE400', 'BIOE420', 'BIOE451', 'ELEC326', 'SPAN368'): 1, ('COMP412', 'COMP490', 'ENGL301', 'LPAP144', 'NEUR383'): 1, ('BIOS372', 'BIOS385', 'HART202', 'NEUR310'): 1, ('BUSI401', 'HUMA309', 'LPAP110', 'SMGT376', 'SMGT440', 'SOCI325'): 1, ('COMP301', 'COMP412', 'LPAP182', 'STAT413', 'STAT418', 'STAT449'): 1, ('HIST372', 'HIST438', 'PLST307', 'POLI321', 'POLI341'): 1, ('ECON481', 'EEPS480', 'HIST332', 'HIST438', 'LPAP106', 'STAT487'): 1, ('BIOS329', 'FREN263', 'LPAP144', 'MUSI337', 'MUSI339', 'MUSI441', 'MUSI493'): 1, ('BIOS310', 'BIOS318', 'BIOS341', 'BIOS344', 'ENGL305', 'LPAP170'): 1, ('ELEC424', 'ELEC425', 'LPAP172', 'LPAP194', 'MATH300', 'MUSI317'): 1, ('ARAB263', 'BUSI380', 'LEAD402', 'LING300', 'RELI120'): 1, ('BIOS318', 'BIOS353', 'LPAP164', 'SWGS345', 'SWGS477'): 1, ('ENGI355', 'MECH407', 'MECH472', 'MECH484', 'STAT310'): 1, ('MECH407', 'MECH472', 'MECH477', 'MECH490', 'STAT487'): 1, ('ASIA305', 'ASIA378', 'ASIA380', 'ASIA495', 'JAPA401', 'KORE141', 'LPAP172'): 1, ('CHEM330', 'CHEM415', 'CHEM452', 'CHEM462', 'CHEM492', 'CMOR495'): 1, ('CMOR420', 'CMOR422', 'CMOR492', 'ECON437', 'LPAP186', 'SOSC445'): 1, ('COMP480', 'DSCI435', 'LPAP113', 'MATH356'): 1, ('BIOE400', 'BIOE420', 'BIOE447', 'BIOE451'): 1, ('ANTH324', 'ENGL305', 'LPAP110', 'SMGT364', 'SMGT379', 'SPAN263'): 1, ('BIOS310', 'BIOS311', 'BIOS341', 'BIOS344', 'BIOS372', 'CHEM215', 'KINE320'): 1, ('CMST203', 'COMP301', 'COMP318', 'COMP412', 'PSYC409'): 1, ('ENGL301', 'KINE302', 'KINE321', 'KINE441', 'STAT280'): 1, ('CMOR220', 'CMOR302', 'ITAL301', 'MATH300'): 1, ('COLL156', 'COLL175', 'ELEC361', 'ELEC461', 'ELEC462', 'ELEC494', 'LPAP113'): 1, ('ARTS311', 'ARTS499', 'BIOS211', 'BIOS341', 'LPAP178', 'MATH102'): 1, ('ARTS225', 'ASTR101', 'ENGL304', 'LATI310', 'LPAP181'): 1, ('ANTH205', 'BIOS314', 'BIOS372', 'LPAP144', 'MDHM238', 'MDHM430'): 1, ('BIOS318', 'BIOS344', 'KINE440', 'LPAP138', 'POLI326', 'STAT280'): 1, ('ARCH311', 'COLL167', 'COLL179', 'ENST250', 'GLHT201', 'LPAP181', 'PSYC485', 'THEA308'): 1, ('BIOS341', 'BUSI380', 'ECON437', 'SMGT362'): 1, ('BUSI310', 'LPAP100', 'MECH407', 'MECH472', 'MECH477', 'STAT310'): 1, ('ARCH105', 'CHIN301', 'GLHT201', 'LING216', 'SPAN436'): 1, ('CMST203', 'MECH407', 'MECH472', 'STAT310'): 1, ('COMP341', 'COMP412', 'COMP413', 'COMP429'): 1, ('ENGL398', 'ITAL141', 'LPAP100', 'MECH407', 'MECH472', 'MECH477', 'MECH490'): 1, ('CMOR420', 'MECH407', 'MECH472', 'MECH484'): 1, ('BIOS423', 'HART321', 'LPAP105', 'THEA309', 'THEA314'): 1, ('ARCH401', 'ARCH403', 'COLL156', 'COLL300', 'SPAN406'): 1, ('BIOS301', 'KINE310', 'KINE441', 'KINE499', 'PHYS125'): 1, ('HIST275', 'HIST314', 'HIST319', 'HIST372', 'LPAP118'): 1, ('LPAP108', 'RELI307', 'THEA300', 'THEA309', 'THEA314'): 1, ('MUSI303', 'MUSI335', 'MUSI381', 'MUSI401', 'MUSI403', 'MUSI416', 'RELI101'): 1, ('BIOS128', 'BIOS385', 'HEAL380', 'HIST312', 'LPAP134', 'NEUR383', 'SPAN322'): 1, ('ENGL308', 'LPAP182', 'MECH407', 'MECH472', 'STAT310'): 1, ('CMOR422', 'CMOR492', 'COLL179', 'COLL184', 'LPAP138', 'PSYC332', 'SPAN141', 'STAT449'): 1, ('BUSI310', 'COLL180', 'COMP341', 'COMP382', 'COMP424', 'PSYC101'): 1, ('BIOS318', 'BIOS341', 'BIOS344', 'CHEM330', 'LPAP106', 'SPAN368', 'UNIV212'): 1, ('ASIA219', 'CEVE302', 'CEVE400', 'CEVE481', 'JAPA401'): 1, ('BIOS329', 'KINE310', 'KINE311', 'KINE320', 'KINE440', 'PSYC321'): 1, ('ANTH344', 'ENGL305', 'ENGL410', 'ENGL493', 'LPAP183', 'MDHM201', 'MDHM359'): 1, ('COLL180', 'COMP382', 'COMP412', 'ENGL301', 'LPAP108'): 1, ('SOCI411', 'SOCI492', 'STAT418', 'STAT425'): 1, ('ASTR102', 'COLL186', 'DSCI305', 'DSCI435', 'MUSI334', 'RELI111', 'STAT487'): 1, ('DSCI304', 'JAPA301', 'STAT413', 'STAT425', 'STAT449'): 1, ('COMP412', 'COMP416', 'COMP449', 'DSCI305', 'LPAP182'): 1, ('ARTS311', 'ARTS325', 'ARTS499', 'ENGL308', 'ENGL410', 'POLI210'): 1, ('DSCI303', 'LPAP135', 'PSYC430', 'PSYC461', 'PSYC499'): 1, ('BUSI380', 'SOCI409', 'SOCI411', 'SOCI459'): 1, ('EEPS322', 'EEPS401', 'EEPS481', 'ENST100', 'FILM327', 'LING200', 'LPAP194'): 1, ('BIOS341', 'BIOS352', 'CHEM391', 'CHEM415', 'LPAP183', 'MDHM201'): 1, ('ARCH311', 'BUSI222', 'BUSI401', 'BUSI450', 'LPAP164', 'LPAP172'): 1, ('COLL184', 'ELEC303', 'ELEC326', 'ELEC425', 'ELEC494', 'LPAP135'): 1, ('ENGL274', 'PSYC340', 'PSYC461', 'PSYC480', 'PSYC485'): 1, ('COMP382', 'COMP412', 'ENGL398', 'ENGL410'): 1, ('BIOS301', 'BIOS327', 'BIOS470', 'CHEM330', 'KORE263', 'SPAN436'): 1, ('BIOS310', 'BIOS329', 'BIOS341', 'CHEM313', 'CHEM314', 'HEAL407', 'HEAL460'): 1, ('BIOE392', 'BIOE451', 'BIOE492', 'ENGI301', 'LPAP183'): 1, ('PLST401', 'PSYC332', 'PSYC480', 'PSYC485'): 1, ('COMP412', 'COMP429', 'COMP430', 'LPAP194'): 1, ('ASTR101', 'CMST201', 'COLL167', 'ENGL301', 'ENGL308', 'LPAP172', 'SPAN406'): 1, ('ARAB141', 'KORE263', 'PSYC330', 'PSYC332', 'PSYC353', 'PSYC480'): 1, ('COMP318', 'COMP430', 'COMP490', 'ENST301', 'MDHM359'): 1, ('CHEM330', 'CHEM367', 'CHEM452', 'CHEM491', 'JAPA301'): 1, ('COMP301', 'COMP382', 'COMP490', 'LPAP101', 'STAT310'): 1, ('BIOS310', 'BIOS352', 'ENGL113', 'PHIL220', 'PHIL470'): 1, ('HIST101', 'LING300', 'LING397', 'LING401', 'PSYC321'): 1, ('LING200', 'MDHM238', 'PSYC308', 'PSYC353', 'PSYC485'): 1, ('CMOR492', 'LPAP110', 'SPAN350', 'SPAN453'): 1, ('BIOS311', 'BIOS318', 'BIOS344', 'BIOS352', 'PHIL460'): 1, ('ANTH346', 'ENGL304', 'ENGL383', 'ENGL410', 'ENGL493'): 1, ('CEVE310', 'COMP140', 'EEPS110', 'MATH355', 'STAT315'): 1, ('BIOS204', 'HEAL460', 'LPAP190'): 1, ('BUSI420', 'BUSI430', 'BUSI499', 'COLL200', 'ECON210', 'LPAP180', 'PHIL130', 'PSYC308'): 1, ('ARTS388', 'CMOR304', 'HART366', 'MECH332', 'MECH371', 'MECH477', 'MUSI335'): 1, ('COMP390', 'COMP412', 'COMP416', 'COMP424', 'THEA309'): 1, ('HIST101', 'LPAP181', 'MECH332', 'MECH407', 'MECH454', 'RELI101'): 1, ('CMOR360', 'MECH343', 'MECH400', 'MECH454', 'STAT315'): 1, ('ECON209', 'ECON422', 'LING205', 'LPAP134', 'SOPA400'): 1, ('ARCH401', 'ARCH403', 'HART358', 'HIST340'): 1, ('KORE141', 'LPAP190', 'MECH407', 'MECH454', 'MECH477'): 1, ('BUSI420', 'ENGL362', 'FILM373', 'LPAP110', 'SOCI358', 'STAT499'): 1, ('COMP310', 'COMP311', 'COMP382', 'COMP490'): 1, ('BIOS310', 'KINE302', 'KINE311', 'KINE320', 'LALX158', 'SOCI309'): 1, ('BIOS128', 'BIOS310', 'BIOS314', 'BIOS332', 'BIOS341', 'COLL179', 'LALX332'): 1, ('COLL108', 'COMP318', 'COMP382', 'COMP412', 'FREN141'): 1, ('XCHG100',): 16, ('CHBE403', 'CHBE443', 'CHBE470', 'RELI219'): 1, ('BUSI222', 'COLL172', 'COLL185', 'COMP412', 'COMP430'): 1, ('BUSI461', 'COMP215', 'COMP382', 'COMP431'): 1, ('ANTH321', 'ANTH340', 'BIOS341', 'BIOS344', 'LPAP118'): 1, ('ANTH203', 'ANTH303', 'ECON210', 'LPAP102', 'PLST401', 'SOPA400'): 1, ('HEAL407', 'KINE375', 'KINE440', 'KINE498'): 1, ('COMP442', 'COMP490', 'MATH300', 'MATH370', 'STAT425'): 1, ('ARCH401', 'ARCH403', 'SPAN406'): 1, ('BUSI222', 'COMP412', 'COMP442', 'ELEC478'): 1, ('LPAP118', 'MECH407', 'MECH472', 'MECH484', 'STAT310'): 1, ('ARCH225', 'CEVE302', 'CEVE314', 'CEVE481', 'EEPS115', 'LPAP100', 'LPAP120'): 1, ('LING200', 'LPAP172', 'MATH425', 'PHIL130', 'STAT425'): 1, ('ECON441', 'ECON481', 'ECON483', 'RELI101', 'SOPA400', 'STAT405'): 1, ('ARCH311', 'MECH407', 'MECH472', 'MECH484'): 1, ('EMSP281', 'HEAL460', 'KINE302', 'KINE321', 'MDHM430', 'PSYC321'): 1, ('ANTH344', 'BUSI310', 'CMOR304', 'MECH371'): 1, ('BIOS385', 'NEUR383', 'PSYC351', 'SPAN356', 'SPAN368'): 1, ('LPAP118', 'LPAP164', 'PSYC231', 'STAT425', 'STAT450', 'STAT487'): 1, ('BUSI305', 'CMOR360', 'ECON437', 'HIST331', 'HUMA310'): 1, ('LPAP183', 'MECH407', 'MECH472', 'MECH484', 'STAT305'): 1, ('COLL183', 'COMP412', 'LPAP110', 'SMGT432'): 1, ('BIOS301', 'CHEM301', 'MATH211', 'MATH212'): 1, ('ECON305', 'ECON310', 'ECON481', 'ENGL301'): 1, ('ARTS401', 'HIST331', 'LPAP182', 'SOCI309', 'SPAN436'): 1, ('ANTH203', 'LPAP120', 'MECH407', 'MECH454', 'PSYC202', 'STAT310'): 1, ('BIOS310', 'BIOS318', 'BIOS352', 'KINE310', 'KINE321', 'KINE440', 'LPAP101'): 1, ('COLL167', 'DSCI304', 'LPAP170', 'LPAP186', 'STAT413', 'STAT425'): 1, ('COLL200', 'ELEC424', 'ELEC425', 'ELEC430', 'ELEC494'): 1, ('BIOE446', 'BIOE451', 'ENGI301', 'PSYC203', 'UNIV330'): 1, ('BUSI401', 'BUSI450', 'HIST291', 'HIST331', 'PSYC202'): 1, ('COMP318', 'HONS470', 'MATH425', 'MDHM359', 'STAT425'): 1, ('MATH356', 'STAT413', 'STAT418', 'STAT425', 'STAT487'): 1, ('ANTH357', 'ANTH493', 'ASIA305', 'BIOS211', 'BIOS341', 'SPAN142'): 1, ('CMOR302', 'PHIL125', 'PHIL230', 'PHYS425', 'PHYS491', 'PHYS493'): 1, ('BUSI430', 'BUSI450', 'SMGT364', 'SMGT440'): 1, ('ARCH311', 'BIOS310', 'BIOS341', 'HEAL132', 'KINE440', 'LPAP110'): 1, ('ARCH225', 'BUSI343', 'SMGT362', 'SMGT377', 'SMGT440'): 1, ('BIOS312', 'BIOS329', 'CHEM313', 'CHEM314', 'FILM324', 'LPAP138'): 1, ('BIOS310', 'BIOS314', 'COLL200', 'KINE301', 'MDHM238'): 1, ('ANTH303', 'ANTH315', 'BIOS318', 'BIOS341', 'ENGL272', 'LPAP194'): 1, ('ENGL210', 'ENGL272', 'ENGL341', 'ENGL410'): 1, ('ECON209', 'ECON483', 'EEPS480', 'HIST120', 'HIST331', 'HIST438', 'STAT310'): 1, ('EEPS480', 'MECH400', 'MECH407', 'STAT305'): 1, ('BUSI222', 'COMP412', 'COMP431', 'LPAP118', 'MDHM359'): 1, ('BUSI343', 'BUSI390', 'MECH407', 'MECH472', 'MECH482'): 1, ('COMP318', 'COMP412', 'COMP430', 'MUSI117'): 1, ('BIOS301', 'BIOS310', 'BIOS341', 'CHEM313', 'CHEM314', 'PSYC485'): 1, ('EDUC304', 'MUSI303', 'MUSI335', 'MUSI381', 'MUSI401', 'MUSI416', 'MUSI421', 'PSYC101'): 1, ('COMP412', 'COMP481', 'GERM141', 'LPAP170', 'MATH463'): 1, ('HEAL380', 'HEAL499', 'KINE301', 'KINE320'): 1, ('BIOS385', 'GLHT451', 'LPAP164', 'MDHM430', 'NEUR383'): 1, ('ARTS280', 'ARTS432', 'FOTO205', 'SOCI309', 'SOCI380'): 1, ('COMP412', 'COMP431', 'LPAP170'): 1, ('COMP301', 'COMP318', 'COMP412', 'FILM432', 'LPAP164', 'POLI354', 'STAT310'): 1, ('ECON100', 'MATH321', 'MATH356', 'STAT310'): 1, ('BUSI450', 'DSCI304', 'ECON441', 'LPAP172', 'STAT405', 'STAT449'): 1, ('ANTH303', 'ANTH490', 'ANTH493', 'BIOS423', 'GLHT201'): 1, ('BUSI420', 'BUSI430', 'COLL183', 'LPAP110', 'SMGT320', 'SMGT440'): 1, ('COLL180', 'ENGL382', 'ENGL410', 'SOCI325', 'SOPA400'): 1, ('BUSI390', 'ECON498', 'HEAL103', 'LPAP108', 'SPAN263'): 1, ('BIOS318', 'BIOS341', 'BIOS352', 'ENGL301', 'MUSI334', 'SPAN141'): 1, ('BIOS215', 'BIOS310', 'BIOS314', 'BIOS353', 'BIOS372', 'LPAP170'): 1, ('COMP412', 'COMP430', 'COMP431', 'PSYC203'): 1, ('BIOS310', 'BIOS329', 'BIOS332', 'BIOS423', 'BUSI390', 'LEAD402'): 1, ('ELEC361', 'HIST101', 'MSNE304', 'MSNE402'): 1, ('BIOS310', 'BIOS318', 'BIOS341', 'BIOS470', 'LPAP178', 'SPAN263'): 1, ('BIOE420', 'BIOE447', 'BIOE449', 'BIOE451', 'PSYC101'): 1, ('ELEC425', 'ELEC450', 'ELEC494', 'ENGL308', 'LPAP182', 'MUSI340'): 1, ('CMOR422', 'ENST265', 'LPAP171', 'MECH407', 'MECH454', 'MECH484'): 1, ('BIOE420', 'BIOE443', 'BIOE451', 'HEAL103', 'LPAP144', 'MUSI334'): 1, ('ARCH311', 'BUSI401', 'COLL156', 'ENST205', 'LPAP170', 'MUSI117'): 1, ('ARCH225', 'HART241', 'LPAP118', 'MATH304', 'SOSC444'): 1, ('ARCH311', 'BIOS315', 'BIOS353'): 1, ('BIOS310', 'BIOS312', 'BIOS423', 'ENST100', 'LPAP101', 'PSYC202'): 1, ('COLL200', 'COMP318', 'COMP412', 'DSCI303', 'HONS470', 'LPAP170'): 1, ('CHEM301', 'CMOR422', 'ELEC468', 'LPAP183', 'LPAP186', 'PHYS491', 'PHYS493'): 1, ('CSCI477', 'LING303', 'LING401', 'PSYC321', 'PSYC353', 'PSYC485'): 1, ('ARCH311', 'CHEM215', 'CHEM313', 'CHEM314', 'KINE310', 'KINE498'): 1, ('COMP318', 'COMP412', 'COMP490', 'HONS470', 'LPAP118', 'STAT413', 'STAT425'): 1, ('COMP412', 'COMP430', 'FREN402', 'FREN478', 'LPAP110'): 1, ('BIOE420', 'BIOE451', 'BIOS341', 'MATH355'): 1, ('BIOS215', 'BIOS314', 'COLL153', 'COLL172', 'LPAP172', 'LPAP178', 'MDHM430', 'PSYC202'): 1, ('COMP341', 'COMP382', 'MATH370', 'MATH463'): 1, ('COLL172', 'COLL183', 'COMP318', 'COMP412', 'ENGL305', 'LPAP186'): 1, ('COMP341', 'COMP412', 'COMP413', 'DSCI305', 'MATH212'): 1, ('COLL188', 'COMP412',

In [8]:
exam_df = exam_info2023[exam_info2023['EXAM_TYPE'].isin(['Scheduled Final Exam-OTR Room', 'Scheduled Final Exam-Dept Room', 'Scheduled Online Final Exam'])]
exam_demand = {}
for index, row in exam_df.iterrows():
    exam_key = row['SUBJECT'] + str(row['COURSE_NUMBER'])
    if exam_key in exam_demand.keys():
        exam_demand[exam_key] += row['SECTION_ENROLLMENT']
    else:
       exam_demand[exam_key] = row['SECTION_ENROLLMENT'] 

online_exams = []
in_person_exams = []
for index, row in exam_df.iterrows():
    exam_key = row['SUBJECT'] + str(row['COURSE_NUMBER'])
    if row['EXAM_TYPE'] == 'Scheduled Online Final Exam':
        online_exams.append(exam_key)
    else:
        in_person_exams.append(exam_key)

set_of_exams = []
for item in online_exams:
    set_of_exams.append(item)
for item in in_person_exams:
    set_of_exams.append(item)
    
print(in_person_exams)
print(online_exams)

['ANTH205', 'ASIA322', 'ASTR470', 'ASTR451', 'ASTR101', 'ASTR350', 'ASTR102', 'BIOE252', 'BIOE451', 'BIOE440', 'BIOE422', 'BIOE420', 'BIOE341', 'BIOE446', 'BIOE383', 'BIOS201', 'BIOS301', 'BIOS312', 'BIOS341', 'BIOS352', 'BIOS300', 'BIOS372', 'BIOS312', 'BIOS385', 'BIOS329', 'BIOS122', 'BIOS353', 'BIOS441', 'BIOS344', 'CHEM430', 'CHEM211', 'CHEM201', 'CHEM401', 'CHEM121', 'CHEM121', 'CHEM121', 'CHEM452', 'CHEM462', 'CHEM496', 'CHEM219', 'CHEM313', 'COMP450', 'COMP326', 'COMP311', 'COMP490', 'COMP390', 'COMP301', 'COMP417', 'COMP310', 'COMP310', 'COMP442', 'COMP480', 'COMP182', 'COMP413', 'COMP431', 'COMP429', 'COMP462', 'COMP416', 'ECON307', 'ECON437', 'ECON203', 'ECON308', 'ECON210', 'ECON300', 'ECON305', 'ECON200', 'ECON483', 'ECON200', 'ECON203', 'ECON497', 'ECON209', 'ECON209', 'ECON209', 'ECON209', 'ECON209', 'ECON481', 'ECON307', 'ELEC261', 'ELEC326', 'ELEC450', 'ELEC303', 'ELEC434', 'ELEC429', 'ELEC361', 'ENGI302', 'ENST437', 'ENST315', 'FREN424', 'HEAL103', 'HEAL103', 'HIST391', 'HIST340', 'HIST319', 'HIST256', 'MATH102', 'MATH212', 'MATH321', 'MATH355', 'MATH101', 'MATH101', 'MATH102', 'MATH212', 'MATH101', 'MATH211', 'MATH211', 'MATH102', 'MATH212', 'MATH355', 'MATH212', 'MATH211', 'MATH354', 'MATH101', 'MATH101', 'MATH212', 'MATH300', 'MATH302', 'MATH355', 'MATH304', 'MATH111', 'MECH450', 'MECH371', 'MECH202', 'MECH202', 'MECH211', 'MECH343', 'MECH371', 'MECH400', 'MECH343', 'MECH343', 'MECH343', 'MECH477', 'NEUR441', 'NEUR362', 'PHYS111', 'PHYS125', 'PHYS425', 'PHYS101', 'PHYS101', 'PHYS411', 'PHYS413', 'POLI210', 'POLI212', 'POLI211', 'POLI395', 'POLI210', 'POLI210', 'POLI211', 'POLI211', 'POLI211', 'POLI212', 'POLI212', 'POLI260', 'POLI354', 'POLI339', 'PSYC101', 'PSYC101', 'PSYC203', 'PSYC351', 'PSYC203', 'PSYC101', 'PSYC353', 'PSYC467', 'PSYC308', 'PSYC101', 'PSYC340', 'PSYC321', 'PSYC362', 'PSYC203', 'RELI307', 'RELI322', 'SOCI231', 'SOCI301', 'SOSC444', 'SOSC302', 'SOSC302', 'STAT280', 'STAT305', 'STAT310', 'STAT280', 'STAT305', 'STAT418', 'STAT440', 'STAT425', 'STAT413', 'STAT315', 'STAT450', 'STAT310', 'CEVE302', 'CEVE471', 'CEVE431', 'CEVE211', 'CEVE325', 'CEVE400', 'CEVE426', 'CEVE460', 'CEVE476', 'GLHT451', 'CHBE301', 'CHBE390', 'CHBE401', 'CHBE420', 'CHBE468', 'CHBE418', 'CHBE470', 'CHBE412', 'SWGS101', 'SWGS424', 'SWGS345', 'SWGS318', 'SMGT360', 'JWST318', 'LEAD260', 'PLST315', 'CMST203', 'DSCI304', 'DSCI304', 'DSCI301', 'DSCI303', 'EMSP282', 'EMSP281', 'EEPS468', 'EEPS471', 'EEPS110', 'EEPS322', 'EEPS410', 'EEPS418', 'EEPS115', 'EEPS412', 'EEPS445', 'EEPS465', 'EEPS101', 'EEPS454', 'EEPS459', 'EEPS106', 'EEPS438', 'SOPA200', 'SOPA400', 'SOPA309', 'MSNE402', 'MSNE406', 'CMOR422', 'CMOR360', 'CMOR451', 'CMOR462', 'CMOR302', 'CMOR410', 'CMOR420', 'CMOR494', 'CMOR441', 'CMOR304', 'FWIS188', 'FWIS188', 'FWIS188', 'FWIS195', 'FWIS166', 'ARCH423', 'ARCH311', 'BIOE385', 'BIOE385', 'BIOE449', 'BIOE385', 'BIOE123', 'BIOS202', 'COMP390', 'COMP490', 'COMP490', 'COMP491', 'ELEC426', 'ENGI120', 'ENGI120', 'ENGI200', 'ENGI220', 'ENGI220', 'ENGI300', 'ENGI355', 'ENGI120', 'ENGI220', 'MATH423', 'MECH490', 'MECH490', 'MECH490', 'MECH203', 'MECH203', 'MUSI421', 'NAVA101', 'NAVA403', 'NAVA203', 'FILM434', 'BUSI310', 'BUSI310', 'BUSI343', 'BUSI343', 'BUSI390', 'BUSI461', 'BUSI305', 'BUSI401', 'BUSI395', 'BUSI395', 'BUSI395', 'BUSI222', 'BUSI224', 'BUSI430', 'BUSI440', 'BUSI305', 'BUSI343', 'BUSI310', 'GLHT449', 'MDHM359', 'EEPS430', 'CMOR405', 'FWIS188']
['ANTH200', 'COMP382', 'COMP382', 'COMP140', 'COMP140', 'COMP140', 'COMP140', 'COMP140', 'HIST372', 'HUMA315', 'ITAL141', 'ITAL141', 'ITAL301', 'LING401', 'LING200', 'LING397', 'LING305', 'POLI321']

In [9]:
room_capacity = {}
for index, row in class_info2023.iterrows():
    room = row['BUILDING_CODE'] + str(row['ROOM_NUMBER'])
    room_capacity[room] = row['ROOM_CAPACITY']

room_capacity['Online'] = float('inf')

print(room_capacity)

{'RZR227': 12, 'RZR302': 12, 'RZR304': 20, 'RZR205': 20, 'RZR305': 20, 'RZR310': 12, 'SEW133': 24, 'SEW301': 168, 'SEW101': 36, 'SEW305': 45, 'SEW307': 45, 'SEW303': 45, 'SEW460': 20, 'SEW462': 17, 'SEW309': 82, 'ABL131': 140, 'ANH117': 59, 'ABL130': 52, 'BKH116': 37, 'BKH229': 24, 'BKH102': 37, 'BRK103': 30, 'DCH1042': 46, 'BKH233': 24, 'BRC282': 66, 'BRC285': 24, 'BRC286': 32, 'DBH180': 87, 'DCH1046': 46, 'BRC284': 50, 'BRK101': 150, 'DCC113': 99, 'GRBW212': 32, 'HBH227': 46, 'DCH1064': 73, 'DCH1020 / SYM II': 66, 'GRW220': 26, 'HBH423': 16, 'DCH1070': 73, 'GRBW211': 32, 'GRW160A': 30, 'DCH1055': 240, 'DCH1075': 35, 'HRG224': 22, 'HRZ211': 20, 'HRZ212': 123, 'HBH453': 16, 'HRG125': 24, 'HBHB21': 24, 'HRG126': 24, 'HRZ210': 125, 'HRZAMP': 300, 'HBH427': 27, 'HRG100': 197, 'HRG128': 7, 'HUM327': 24, 'KCK101': 30, 'HUM117': 75, 'HUM118': 30, 'HUM120': 17, 'HUM226': 24, 'HUM328': 42, 'KCK102': 69, 'HUM119': 42, 'HUM227': 24, 'KCK100': 265, 'KWG100': 68, 'LVCCOMMNS': 184, 'KCK107': 20, 'KRF110': 86, 'KRF102': 15, 'KRF120': 17, 'KWG128': 18, 'MCA103': 18, 'KCK105': 20, 'KRF105': 34, 'KRF125': 48, 'KWG130': 18, 'RYN201': 78, 'RZR119': 66, 'MCA210': 20, 'MCA237': 24, 'MXF251': 56, 'MXF252': 48, 'RZR106': 28, 'RZR123': 36, 'MEB128': 48, 'RYN102': 20, 'RZR113': 36, 'RZR202': 12, 'RZR204': 20, 'SEW562': 17, 'SEW207 / SYM I': 36, 'SEW560': 20, 'SST106': 54, 'TUD201': 30, 'WSC123': 14, 'WSC146': 36, 'PCF2': 0, 'PCF3': 158, 'PCF4': 90, 'OES130': 108, 'OES132': 108, 'Online': inf}

In [10]:
in_person_slots = []
for index, row in available_slots.iterrows():
    slot = f"{row['BUILDING_CODE']}{row['ROOM_NUMBER']}_Day{row['DAY_OF_WEEK']}"
    in_person_slots.append((slot, row['TIME_OF_DAY']))
in_person_slots

[('RZR227_Day7', 'Morning'),
 ('RZR227_Day7', 'Afternoon'),
 ('RZR227_Day7', 'Evening'),
 ('RZR227_Day3', 'Morning'),
 ('RZR227_Day3', 'Afternoon'),
 ('RZR227_Day3', 'Evening'),
 ('RZR302_Day5', 'Morning'),
 ('RZR302_Day5', 'Evening'),
 ('RZR302_Day1', 'Morning'),
 ('RZR302_Day1', 'Evening'),
 ('RZR302_Day4', 'Morning'),
 ('RZR302_Day4', 'Evening'),
 ('RZR302_Day6', 'Morning'),
 ('RZR302_Day6', 'Afternoon'),
 ('RZR302_Day6', 'Evening'),
 ('RZR302_Day2', 'Morning'),
 ('RZR302_Day2', 'Evening'),
 ('RZR302_Day7', 'Morning'),
 ('RZR302_Day7', 'Afternoon'),
 ('RZR302_Day7', 'Evening'),
 ('RZR302_Day3', 'Morning'),
 ('RZR302_Day3', 'Evening'),
 ('RZR304_Day5', 'Morning'),
 ('RZR304_Day5', 'Afternoon'),
 ('RZR304_Day5', 'Evening'),
 ('RZR304_Day1', 'Morning'),
 ('RZR205_Day3', 'Morning'),
 ('RZR205_Day3', 'Afternoon'),
 ('RZR205_Day3', 'Evening'),
 ('RZR227_Day5', 'Morning'),
 ('RZR227_Day5', 'Afternoon'),
 ('RZR227_Day5', 'Evening'),
 ('RZR227_Day1', 'Morning'),
 ('RZR227_Day1', 'Afternoon'),
 ('RZR227_Day1', 'Evening'),
 ('RZR227_Day4', 'Morning'),
 ('RZR227_Day4', 'Afternoon'),
 ('RZR227_Day4', 'Evening'),
 ('RZR227_Day6', 'Morning'),
 ('RZR227_Day6', 'Afternoon'),
 ('RZR227_Day6', 'Evening'),
 ('RZR227_Day2', 'Morning'),
 ('RZR227_Day2', 'Afternoon'),
 ('RZR227_Day2', 'Evening'),
 ('RZR305_Day3', 'Morning'),
 ('RZR305_Day3', 'Afternoon'),
 ('RZR305_Day3', 'Evening'),
 ('RZR310_Day5', 'Morning'),
 ('RZR310_Day5', 'Evening'),
 ('RZR310_Day1', 'Morning'),
 ('RZR310_Day1', 'Evening'),
 ('RZR310_Day4', 'Morning'),
 ('RZR310_Day4', 'Evening'),
 ('RZR310_Day6', 'Morning'),
 ('RZR310_Day6', 'Afternoon'),
 ('RZR310_Day6', 'Evening'),
 ('RZR310_Day2', 'Morning'),
 ('RZR310_Day2', 'Evening'),
 ('RZR310_Day7', 'Morning'),
 ('RZR310_Day7', 'Afternoon'),
 ('RZR310_Day7', 'Evening'),
 ('RZR310_Day3', 'Morning'),
 ('RZR304_Day1', 'Afternoon'),
 ('RZR304_Day1', 'Evening'),
 ('RZR304_Day4', 'Morning'),
 ('RZR304_Day4', 'Afternoon'),
 ('RZR304_Day4', 'Evening'),
 ('RZR304_Day6', 'Morning'),
 ('RZR304_Day6', 'Afternoon'),
 ('RZR304_Day6', 'Evening'),
 ('RZR304_Day2', 'Morning'),
 ('RZR304_Day2', 'Afternoon'),
 ('RZR304_Day2', 'Evening'),
 ('RZR304_Day7', 'Morning'),
 ('RZR304_Day7', 'Afternoon'),
 ('RZR304_Day7', 'Evening'),
 ('RZR304_Day3', 'Morning'),
 ('RZR304_Day3', 'Afternoon'),
 ('RZR304_Day3', 'Evening'),
 ('RZR305_Day5', 'Morning'),
 ('RZR305_Day5', 'Afternoon'),
 ('RZR305_Day5', 'Evening'),
 ('RZR305_Day1', 'Morning'),
 ('RZR305_Day1', 'Afternoon'),
 ('RZR305_Day1', 'Evening'),
 ('RZR305_Day4', 'Morning'),
 ('RZR305_Day4', 'Afternoon'),
 ('RZR305_Day4', 'Evening'),
 ('RZR305_Day6', 'Morning'),
 ('RZR305_Day6', 'Afternoon'),
 ('RZR305_Day6', 'Evening'),
 ('RZR305_Day2', 'Morning'),
 ('RZR305_Day2', 'Afternoon'),
 ('RZR305_Day2', 'Evening'),
 ('RZR305_Day7', 'Morning'),
 ('RZR305_Day7', 'Afternoon'),
 ('RZR305_Day7', 'Evening'),
 ('SEW133_Day2', 'Morning'),
 ('SEW133_Day2', 'Afternoon'),
 ('SEW133_Day2', 'Evening'),
 ('SEW133_Day7', 'Morning'),
 ('SEW133_Day7', 'Afternoon'),
 ('SEW133_Day7', 'Evening'),
 ('SEW133_Day3', 'Morning'),
 ('SEW133_Day3', 'Afternoon'),
 ('SEW133_Day3', 'Evening'),
 ('SEW301_Day5', 'Morning'),
 ('SEW301_Day5', 'Afternoon'),
 ('SEW301_Day5', 'Evening'),
 ('SEW301_Day1', 'Morning'),
 ('SEW301_Day1', 'Afternoon'),
 ('SEW301_Day1', 'Evening'),
 ('SEW301_Day4', 'Morning'),
 ('SEW301_Day4', 'Afternoon'),
 ('SEW301_Day4', 'Evening'),
 ('SEW301_Day6', 'Morning'),
 ('SEW301_Day6', 'Afternoon'),
 ('SEW301_Day6', 'Evening'),
 ('SEW301_Day2', 'Morning'),
 ('SEW301_Day2', 'Afternoon'),
 ('SEW301_Day2', 'Evening'),
 ('RZR310_Day3', 'Evening'),
 ('SEW101_Day5', 'Morning'),
 ('SEW101_Day5', 'Afternoon'),
 ('SEW101_Day5', 'Evening'),
 ('SEW101_Day1', 'Morning'),
 ('SEW101_Day1', 'Afternoon'),
 ('SEW101_Day1', 'Evening'),
 ('SEW101_Day4', 'Morning'),
 ('SEW101_Day4', 'Afternoon'),
 ('SEW101_Day4', 'Evening'),
 ('SEW101_Day6', 'Morning'),
 ('SEW101_Day6', 'Afternoon'),
 ('SEW101_Day6', 'Evening'),
 ('SEW101_Day2', 'Morning'),
 ('SEW101_Day2', 'Afternoon'),
 ('SEW101_Day2', 'Evening'),
 ('SEW101_Day7', 'Morning'),
 ('SEW101_Day7', 'Afternoon'),
 ('SEW101_Day7', 'Evening'),
 ('SEW101_Day3', 'Morning'),
 ('SEW101_Day3', 'Afternoon'),
 ('SEW101_Day3', 'Evening'),
 ('SEW133_Day5', 'Morning'),
 ('SEW133_Day5', 'Afternoon'),
 ('SEW133_Day5', 'Evening'),
 ('SEW133_Day1', 'Morning'),
 ('SEW133_Day1', 'Afternoon'),
 ('SEW133_Day1', 'Evening'),
 ('SEW133_Day4', 'Morning'),
 ('SEW133_Day4', 'Afternoon'),
 ('SEW133_Day4', 'Evening'),
 ('SEW133_Day6', 'Morning'),
 ('SEW133_Day6', 'Afternoon'),
 ('SEW133_Day6', 'Evening'),
 ('SEW305_Day4', 'Morning'),
 ('SEW305_Day4', 'Afternoon'),
 ('SEW305_Day4', 'Evening'),
 ('SEW305_Day6', 'Morning'),
 ('SEW305_Day6', 'Afternoon'),
 ('SEW305_Day6', 'Evening'),
 ('SEW305_Day2', 'Morning'),
 ('SEW305_Day2', 'Afternoon'),
 ('SEW305_Day2', 'Evening'),
 ('SEW305_Day7', 'Morning'),
 ('SEW305_Day7', 'Afternoon'),
 ('SEW305_Day7', 'Evening'),
 ('SEW305_Day3', 'Morning'),
 ('SEW305_Day3', 'Afternoon'),
 ('SEW305_Day3', 'Evening'),
 ('SEW307_Day5', 'Morning'),
 ('SEW307_Day5', 'Afternoon'),
 ('SEW307_Day5', 'Evening'),
 ('SEW307_Day1', 'Morning'),
 ('SEW307_Day1', 'Afternoon'),
 ('SEW307_Day1', 'Evening'),
 ('SEW307_Day4', 'Morning'),
 ('SEW307_Day4', 'Afternoon'),
 ('SEW307_Day4', 'Evening'),
 ('SEW301_Day7', 'Morning'),
 ('SEW301_Day7', 'Afternoon'),
 ('SEW301_Day7', 'Evening'),
 ('SEW301_Day3', 'Morning'),
 ('SEW301_Day3', 'Afternoon'),
 ('SEW301_Day3', 'Evening'),
 ('SEW303_Day5', 'Morning'),
 ('SEW303_Day5', 'Afternoon'),
 ('SEW303_Day5', 'Evening'),
 ('SEW303_Day1', 'Morning'),
 ('SEW303_Day1', 'Afternoon'),
 ('SEW303_Day1', 'Evening'),
 ('SEW303_Day4', 'Morning'),
 ('SEW303_Day4', 'Afternoon'),
 ('SEW303_Day4', 'Evening'),
 ('SEW303_Day6', 'Morning'),
 ('SEW303_Day6', 'Afternoon'),
 ('SEW303_Day6', 'Evening'),
 ('SEW303_Day2', 'Morning'),
 ('SEW303_Day2', 'Afternoon'),
 ('SEW303_Day2', 'Evening'),
 ('SEW303_Day7', 'Morning'),
 ('SEW303_Day7', 'Afternoon'),
 ('SEW303_Day7', 'Evening'),
 ('SEW303_Day3', 'Morning'),
 ('SEW303_Day3', 'Afternoon'),
 ('SEW303_Day3', 'Evening'),
 ('SEW305_Day5', 'Morning'),
 ('SEW305_Day5', 'Afternoon'),
 ('SEW305_Day5', 'Evening'),
 ('SEW305_Day1', 'Morning'),
 ('SEW305_Day1', 'Afternoon'),
 ('SEW305_Day1', 'Evening'),
 ('SEW460_Day5', 'Evening'),
 ('SEW460_Day1', 'Morning'),
 ('SEW460_Day1', 'Afternoon'),
 ('SEW460_Day1', 'Evening'),
 ('SEW460_Day4', 'Morning'),
 ('SEW460_Day4', 'Afternoon'),
 ('SEW460_Day4', 'Evening'),
 ('SEW460_Day6', 'Morning'),
 ('SEW460_Day6', 'Afternoon'),
 ('SEW460_Day6', 'Evening'),
 ('SEW460_Day2', 'Morning'),
 ('SEW460_Day2', 'Afternoon'),
 ('SEW460_Day2', 'Evening'),
 ('SEW460_Day7', 'Morning'),
 ('SEW460_Day7', 'Afternoon'),
 ('SEW460_Day7', 'Evening'),
 ('SEW460_Day3', 'Morning'),
 ('SEW460_Day3', 'Afternoon'),
 ('SEW460_Day3', 'Evening'),
 ('SEW462_Day5', 'Morning'),
 ('SEW462_Day5', 'Evening'),
 ('SEW307_Day6', 'Morning'),
 ('SEW307_Day6', 'Afternoon'),
 ('SEW307_Day6', 'Evening'),
 ('SEW307_Day2', 'Morning'),
 ('SEW307_Day2', 'Afternoon'),
 ('SEW307_Day2', 'Evening'),
 ('SEW307_Day7', 'Morning'),
 ('SEW307_Day7', 'Afternoon'),
 ('SEW307_Day7', 'Evening'),
 ('SEW307_Day3', 'Morning'),
 ('SEW307_Day3', 'Afternoon'),
 ('SEW307_Day3', 'Evening'),
 ('SEW309_Day5', 'Morning'),
 ('SEW309_Day5', 'Afternoon'),
 ('SEW309_Day5', 'Evening'),
 ('SEW309_Day1', 'Morning'),
 ('SEW309_Day1', 'Afternoon'),
 ('SEW309_Day1', 'Evening'),
 ('SEW309_Day4', 'Morning'),
 ('SEW309_Day4', 'Afternoon'),
 ('SEW309_Day4', 'Evening'),
 ('SEW309_Day6', 'Morning'),
 ('SEW309_Day6', 'Afternoon'),
 ('SEW309_Day6', 'Evening'),
 ('SEW309_Day2', 'Morning'),
 ('SEW309_Day2', 'Afternoon'),
 ('SEW309_Day2', 'Evening'),
 ('SEW309_Day7', 'Morning'),
 ('SEW309_Day7', 'Afternoon'),
 ('SEW309_Day7', 'Evening'),
 ('SEW309_Day3', 'Morning'),
 ('SEW309_Day3', 'Afternoon'),
 ('SEW309_Day3', 'Evening'),
 ('SEW460_Day5', 'Morning'),
 ('SEW460_Day5', 'Afternoon'),
 ('ABL131_Day2', 'Afternoon'),
 ('ABL131_Day2', 'Evening'),
 ('ABL131_Day7', 'Morning'),
 ('ABL131_Day7', 'Afternoon'),
 ('ABL131_Day7', 'Evening'),
 ('ABL131_Day3', 'Morning'),
 ('ABL131_Day3', 'Afternoon'),
 ('ABL131_Day3', 'Evening'),
 ('ANH117_Day5', 'Morning'),
 ('ANH117_Day5', 'Afternoon'),
 ('ANH117_Day5', 'Evening'),
 ('ANH117_Day1', 'Morning'),
 ('ANH117_Day1', 'Afternoon'),
 ('ANH117_Day1', 'Evening'),
 ('ANH117_Day4', 'Morning'),
 ('ANH117_Day4', 'Afternoon'),
 ('ANH117_Day4', 'Evening'),
 ('ANH117_Day6', 'Morning'),
 ('ANH117_Day6', 'Afternoon'),
 ('ANH117_Day6', 'Evening'),
 ('ANH117_Day2', 'Morning'),
 ('ANH117_Day2', 'Afternoon'),
 ('ANH117_Day2', 'Evening'),
 ('ABL130_Day5', 'Morning'),
 ('ABL130_Day5', 'Afternoon'),
 ('ABL130_Day5', 'Evening'),
 ('ABL130_Day1', 'Morning'),
 ('ABL130_Day1', 'Afternoon'),
 ('ABL130_Day1', 'Evening'),
 ('ABL130_Day4', 'Morning'),
 ('ABL130_Day4', 'Afternoon'),
 ('ABL130_Day4', 'Evening'),
 ('ABL130_Day6', 'Morning'),
 ('ABL130_Day6', 'Afternoon'),
 ('ABL130_Day6', 'Evening'),
 ('ABL130_Day2', 'Morning'),
 ('ABL130_Day2', 'Afternoon'),
 ('ABL130_Day2', 'Evening'),
 ('ABL130_Day7', 'Morning'),
 ('ABL130_Day7', 'Afternoon'),
 ('ABL130_Day7', 'Evening'),
 ('ABL130_Day3', 'Morning'),
 ('ABL130_Day3', 'Afternoon'),
 ('ABL130_Day3', 'Evening'),
 ('ABL131_Day5', 'Morning'),
 ('ABL131_Day5', 'Afternoon'),
 ('ABL131_Day5', 'Evening'),
 ('ABL131_Day1', 'Morning'),
 ('ABL131_Day1', 'Afternoon'),
 ('ABL131_Day1', 'Evening'),
 ('ABL131_Day4', 'Morning'),
 ('ABL131_Day4', 'Afternoon'),
 ('ABL131_Day4', 'Evening'),
 ('ABL131_Day6', 'Morning'),
 ('ABL131_Day6', 'Afternoon'),
 ('ABL131_Day6', 'Evening'),
 ('ABL131_Day2', 'Morning'),
 ('BKH116_Day4', 'Evening'),
 ('BKH116_Day6', 'Morning'),
 ('BKH116_Day6', 'Afternoon'),
 ('BKH116_Day6', 'Evening'),
 ('BKH116_Day2', 'Morning'),
 ('BKH116_Day2', 'Afternoon'),
 ('BKH116_Day2', 'Evening'),
 ('BKH116_Day7', 'Morning'),
 ('BKH116_Day7', 'Afternoon'),
 ('BKH116_Day7', 'Evening'),
 ('BKH116_Day3', 'Morning'),
 ('BKH116_Day3', 'Afternoon'),
 ('BKH116_Day3', 'Evening'),
 ('BKH229_Day5', 'Morning'),
 ('BKH229_Day5', 'Afternoon'),
 ('BKH229_Day5', 'Evening'),
 ('BKH229_Day1', 'Morning'),
 ('BKH229_Day1', 'Afternoon'),
 ('BKH229_Day1', 'Evening'),
 ('BKH229_Day4', 'Morning'),
 ('BKH229_Day4', 'Afternoon'),
 ('BKH229_Day4', 'Evening'),
 ('ANH117_Day7', 'Morning'),
 ('ANH117_Day7', 'Afternoon'),
 ('ANH117_Day7', 'Evening'),
 ('ANH117_Day3', 'Morning'),
 ('ANH117_Day3', 'Afternoon'),
 ('ANH117_Day3', 'Evening'),
 ('BKH102_Day5', 'Morning'),
 ('BKH102_Day5', 'Afternoon'),
 ('BKH102_Day5', 'Evening'),
 ('BKH102_Day1', 'Morning'),
 ('BKH102_Day1', 'Afternoon'),
 ('BKH102_Day1', 'Evening'),
 ('BKH102_Day4', 'Morning'),
 ('BKH102_Day4', 'Afternoon'),
 ('BKH102_Day4', 'Evening'),
 ('BKH102_Day6', 'Morning'),
 ('BKH102_Day6', 'Afternoon'),
 ('BKH102_Day6', 'Evening'),
 ('BKH102_Day2', 'Morning'),
 ('BKH102_Day2', 'Afternoon'),
 ('BKH102_Day2', 'Evening'),
 ('BKH102_Day7', 'Morning'),
 ('BKH102_Day7', 'Afternoon'),
 ('BKH102_Day7', 'Evening'),
 ('BKH102_Day3', 'Morning'),
 ('BKH102_Day3', 'Afternoon'),
 ('BKH102_Day3', 'Evening'),
 ('BKH116_Day5', 'Morning'),
 ('BKH116_Day5', 'Afternoon'),
 ('BKH116_Day5', 'Evening'),
 ('BKH116_Day1', 'Morning'),
 ('BKH116_Day1', 'Afternoon'),
 ('BKH116_Day1', 'Evening'),
 ('BKH116_Day4', 'Morning'),
 ('BKH116_Day4', 'Afternoon'),
 ('BRK103_Day2', 'Morning'),
 ('BRK103_Day2', 'Afternoon'),
 ('BRK103_Day2', 'Evening'),
 ('BRK103_Day7', 'Morning'),
 ('DCH1042_Day6', 'Afternoon'),
 ('DCH1042_Day6', 'Evening'),
 ('DCH1042_Day2', 'Morning'),
 ('DCH1042_Day2', 'Afternoon'),
 ('DCH1042_Day2', 'Evening'),
 ('BKH233_Day3', 'Afternoon'),
 ('BKH233_Day3', 'Evening'),
 ('BRC282_Day5', 'Morning'),
 ('BRC282_Day5', 'Afternoon'),
 ('BRC282_Day5', 'Evening'),
 ('BRC285_Day3', 'Morning'),
 ('BRC285_Day3', 'Afternoon'),
 ('BRC285_Day3', 'Evening'),
 ('BRC286_Day5', 'Morning'),
 ('BRK103_Day7', 'Afternoon'),
 ('BRK103_Day7', 'Evening'),
 ('BRK103_Day3', 'Morning'),
 ('BRK103_Day3', 'Afternoon'),
 ('DCH1042_Day7', 'Morning'),
 ('DCH1042_Day7', 'Afternoon'),
 ('DCH1042_Day7', 'Evening'),
 ('BRC282_Day1', 'Morning'),
 ('BRC282_Day1', 'Afternoon'),
 ('BRC282_Day1', 'Evening'),
 ('BRC286_Day5', 'Afternoon'),
 ('BRC286_Day5', 'Evening'),
 ('BRC286_Day1', 'Morning'),
 ('BRC286_Day1', 'Afternoon'),
 ('BRK103_Day3', 'Evening'),
 ('DBH180_Day5', 'Morning'),
 ('DCH1042_Day3', 'Morning'),
 ('DCH1042_Day3', 'Afternoon'),
 ('DCH1042_Day3', 'Evening'),
 ('BRC282_Day4', 'Morning'),
 ('BRC282_Day4', 'Afternoon'),
 ('BRC282_Day4', 'Evening'),
 ('BRC286_Day1', 'Evening'),
 ('BRC286_Day4', 'Morning'),
 ('BRC286_Day4', 'Afternoon'),
 ('BRC286_Day4', 'Evening'),
 ('DBH180_Day1', 'Morning'),
 ('DCH1046_Day5', 'Morning'),
 ('DCH1046_Day5', 'Afternoon'),
 ('DCH1046_Day5', 'Evening'),
 ('DCH1046_Day1', 'Morning'),
 ('BRC282_Day6', 'Morning'),
 ('BRC282_Day6', 'Afternoon'),
 ('BRC282_Day6', 'Evening'),
 ('BRC282_Day2', 'Morning'),
 ('BRC282_Day2', 'Afternoon'),
 ('BRC286_Day6', 'Morning'),
 ('BRC286_Day6', 'Afternoon'),
 ('BRC286_Day6', 'Evening'),
 ('DBH180_Day4', 'Morning'),
 ('DCH1046_Day1', 'Afternoon'),
 ('DCH1046_Day1', 'Evening'),
 ('DCH1046_Day4', 'Morning'),
 ('DCH1046_Day4', 'Afternoon'),
 ('BRC282_Day2', 'Evening'),
 ('BRC282_Day7', 'Morning'),
 ('BRC282_Day7', 'Afternoon'),
 ('BRC282_Day7', 'Evening'),
 ('BRC286_Day2', 'Morning'),
 ('BRC286_Day2', 'Afternoon'),
 ('BRC286_Day2', 'Evening'),
 ('BRC286_Day7', 'Morning'),
 ('DBH180_Day2', 'Morning'),
 ('DCH1046_Day4', 'Evening'),
 ('DCH1046_Day6', 'Morning'),
 ('DCH1046_Day6', 'Afternoon'),
 ('DCH1046_Day6', 'Evening'),
 ('BRC282_Day3', 'Morning'),
 ('BRC282_Day3', 'Afternoon'),
 ('BRC282_Day3', 'Evening'),
 ('BRC286_Day7', 'Afternoon'),
 ('BRC286_Day7', 'Evening'),
 ('BRC286_Day3', 'Morning'),
 ('BRC286_Day3', 'Afternoon'),
 ('BRC286_Day3', 'Evening'),
 ('DCH1046_Day2', 'Morning'),
 ('DCH1046_Day2', 'Afternoon'),
 ('DCH1046_Day2', 'Evening'),
 ('BRC284_Day5', 'Morning'),
 ('BRC284_Day5', 'Afternoon'),
 ('BRC284_Day5', 'Evening'),
 ('BRC284_Day1', 'Morning'),
 ('BRK101_Day5', 'Morning'),
 ('BRK101_Day5', 'Afternoon'),
 ('BRK101_Day5', 'Evening'),
 ('DBH180_Day3', 'Morning'),
 ('DCC113_Day5', 'Morning'),
 ('DCH1046_Day7', 'Morning'),
 ('DCH1046_Day7', 'Afternoon'),
 ('DCH1046_Day7', 'Evening'),
 ('DCH1046_Day3', 'Morning'),
 ('BRC284_Day1', 'Afternoon'),
 ('BRC284_Day1', 'Evening'),
 ('BRC284_Day4', 'Morning'),
 ('BRC284_Day4', 'Afternoon'),
 ('BRK101_Day1', 'Morning'),
 ('BRK101_Day1', 'Afternoon'),
 ('BRK101_Day1', 'Evening'),
 ('DCC113_Day5', 'Afternoon'),
 ('DCC113_Day1', 'Morning'),
 ('DCC113_Day1', 'Afternoon'),
 ('BKH229_Day6', 'Morning'),
 ('BKH229_Day6', 'Afternoon'),
 ('BKH229_Day6', 'Evening'),
 ('BKH229_Day2', 'Morning'),
 ('BRC284_Day4', 'Evening'),
 ('BRC284_Day6', 'Morning'),
 ('BRC284_Day6', 'Afternoon'),
 ('BRC284_Day6', 'Evening'),
 ('BRK101_Day4', 'Morning'),
 ('BRK101_Day4', 'Afternoon'),
 ('BRK101_Day4', 'Evening'),
 ('BRK101_Day6', 'Morning'),
 ('DCC113_Day4', 'Morning'),
 ('DCC113_Day4', 'Afternoon'),
 ('BKH229_Day2', 'Afternoon'),
 ('BKH229_Day2', 'Evening'),
 ('BKH229_Day7', 'Morning'),
 ('BKH229_Day7', 'Afternoon'),
 ('BKH229_Day7', 'Evening'),
 ('BRC284_Day2', 'Morning'),
 ('BRC284_Day2', 'Afternoon'),
 ('BRC284_Day2', 'Evening'),
 ('BRK101_Day6', 'Afternoon'),
 ('BRK101_Day6', 'Evening'),
 ('BRK101_Day2', 'Morning'),
 ('BRK101_Day2', 'Afternoon'),
 ('BRK101_Day2', 'Evening'),
 ('BKH229_Day3', 'Morning'),
 ('BKH229_Day3', 'Afternoon'),
 ('BKH229_Day3', 'Evening'),
 ('BRC284_Day7', 'Morning'),
 ('BRC284_Day7', 'Afternoon'),
 ('BRC284_Day7', 'Evening'),
 ('BRC284_Day3', 'Morning'),
 ('BRC284_Day3', 'Afternoon'),
 ('BRK101_Day7', 'Morning'),
 ('BRK101_Day7', 'Afternoon'),
 ('BRK101_Day7', 'Evening'),
 ('DCC113_Day2', 'Morning'),
 ('DCC113_Day2', 'Afternoon'),
 ('BKH233_Day5', 'Morning'),
 ('BKH233_Day5', 'Afternoon'),
 ('BKH233_Day5', 'Evening'),
 ('BKH233_Day1', 'Morning'),
 ('BRC284_Day3', 'Evening'),
 ('BRC285_Day5', 'Morning'),
 ('BRC285_Day5', 'Afternoon'),
 ('BRC285_Day5', 'Evening'),
 ('BRK101_Day3', 'Morning'),
 ('BRK101_Day3', 'Afternoon'),
 ('BRK101_Day3', 'Evening'),
 ('DCC113_Day3', 'Morning'),
 ('DCC113_Day3', 'Afternoon'),
 ('BKH233_Day1', 'Afternoon'),
 ('BKH233_Day1', 'Evening'),
 ('BKH233_Day4', 'Morning'),
 ('BKH233_Day4', 'Afternoon'),
 ('BRC285_Day1', 'Morning'),
 ('BRC285_Day1', 'Afternoon'),
 ('BRC285_Day1', 'Evening'),
 ('BRK103_Day5', 'Morning'),
 ('BRK103_Day5', 'Afternoon'),
 ('BRK103_Day5', 'Evening'),
 ('BRK103_Day1', 'Morning'),
 ('BRK103_Day1', 'Afternoon'),
 ('DCH1042_Day5', 'Morning'),
 ('DCH1042_Day5', 'Afternoon'),
 ('DCH1042_Day5', 'Evening'),
 ('BKH233_Day4', 'Evening'),
 ('BKH233_Day6', 'Morning'),
 ('BKH233_Day6', 'Afternoon'),
 ('BKH233_Day6', 'Evening'),
 ('BRC285_Day4', 'Morning'),
 ('BRC285_Day4', 'Afternoon'),
 ('BRC285_Day4', 'Evening'),
 ('BRC285_Day6', 'Morning'),
 ('BRK103_Day1', 'Evening'),
 ('BRK103_Day4', 'Morning'),
 ('BRK103_Day4', 'Afternoon'),
 ('BRK103_Day4', 'Evening'),
 ('DCH1042_Day1', 'Morning'),
 ('DCH1042_Day1', 'Afternoon'),
 ('DCH1042_Day1', 'Evening'),
 ('BKH233_Day2', 'Morning'),
 ('BKH233_Day2', 'Afternoon'),
 ('BKH233_Day2', 'Evening'),
 ('BRC285_Day6', 'Afternoon'),
 ('BRC285_Day6', 'Evening'),
 ('BRC285_Day2', 'Morning'),
 ('BRC285_Day2', 'Afternoon'),
 ('BRC285_Day2', 'Evening'),
 ('BRK103_Day6', 'Morning'),
 ('BRK103_Day6', 'Afternoon'),
 ('BRK103_Day6', 'Evening'),
 ('DCH1042_Day4', 'Morning'),
 ('DCH1042_Day4', 'Afternoon'),
 ('DCH1042_Day4', 'Evening'),
 ('DCH1042_Day6', 'Morning'),
 ('BKH233_Day7', 'Morning'),
 ('BKH233_Day7', 'Afternoon'),
 ('BKH233_Day7', 'Evening'),
 ('BKH233_Day3', 'Morning'),
 ('BRC285_Day7', 'Morning'),
 ('BRC285_Day7', 'Afternoon'),
 ('BRC285_Day7', 'Evening'),
 ('GRBW212_Day2', 'Morning'),
 ('GRBW212_Day2', 'Afternoon'),
 ('GRBW212_Day2', 'Evening'),
 ('GRBW212_Day7', 'Morning'),
 ('HBH227_Day6', 'Afternoon'),
 ('HBH227_Day6', 'Evening'),
 ('HBH227_Day2', 'Morning'),
 ('HBH227_Day2', 'Afternoon'),
 ('DCH1064_Day4', 'Morning'),
 ('DCH1064_Day4', 'Afternoon'),
 ('DCH1064_Day4', 'Evening'),
 ('DCH1064_Day6', 'Morning'),
 ('DCH1020 / SYM II_Day1', 'Morning'),
 ('DCH1020 / SYM II_Day1', 'Afternoon'),
 ('DCH1020 / SYM II_Day1', 'Evening'),
 ('GRBW212_Day7', 'Afternoon'),
 ('GRBW212_Day7', 'Evening'),
 ('GRBW212_Day3', 'Morning'),
 ('GRBW212_Day3', 'Afternoon'),
 ('HBH227_Day2', 'Evening'),
 ('HBH227_Day7', 'Morning'),
 ('HBH227_Day7', 'Afternoon'),
 ('HBH227_Day7', 'Evening'),
 ('DCH1064_Day6', 'Afternoon'),
 ('DCH1064_Day6', 'Evening'),
 ('DCH1064_Day2', 'Morning'),
 ('DCH1064_Day2', 'Afternoon'),
 ('DCH1020 / SYM II_Day4', 'Morning'),
 ('DCH1020 / SYM II_Day4', 'Afternoon'),
 ('DCH1020 / SYM II_Day4', 'Evening'),
 ('GRBW212_Day3', 'Evening'),
 ('GRW220_Day5', 'Morning'),
 ('GRW220_Day5', 'Afternoon'),
 ('HBH227_Day3', 'Morning'),
 ('HBH227_Day3', 'Afternoon'),
 ('HBH227_Day3', 'Evening'),
 ('DCH1064_Day2', 'Evening'),
 ('DCH1064_Day7', 'Morning'),
 ('DCH1064_Day7', 'Afternoon'),
 ('DCH1064_Day7', 'Evening'),
 ('DCH1020 / SYM II_Day6', 'Morning'),
 ('DCH1020 / SYM II_Day6', 'Afternoon'),
 ('DCH1020 / SYM II_Day6', 'Evening'),
 ('GRW220_Day1', 'Morning'),
 ('GRW220_Day1', 'Afternoon'),
 ('HBH423_Day5', 'Morning'),
 ('HBH423_Day5', 'Afternoon'),
 ('HBH423_Day5', 'Evening'),
 ('HBH423_Day1', 'Morning'),
 ('DCH1064_Day3', 'Morning'),
 ('DCH1064_Day3', 'Afternoon'),
 ('DCH1064_Day3', 'Evening'),
 ('DCH1020 / SYM II_Day2', 'Morning'),
 ('DCH1020 / SYM II_Day2', 'Afternoon'),
 ('DCH1020 / SYM II_Day2', 'Evening'),
 ('GRW220_Day4', 'Morning'),
 ('GRW220_Day4', 'Afternoon'),
 ('GRW220_Day6', 'Morning'),
 ('HBH423_Day1', 'Afternoon'),
 ('HBH423_Day1', 'Evening'),
 ('HBH423_Day4', 'Morning'),
 ('HBH423_Day4', 'Afternoon'),
 ('HBH423_Day4', 'Evening'),
 ('DCH1070_Day5', 'Morning'),
 ('DCH1070_Day5', 'Afternoon'),
 ('DCH1070_Day5', 'Evening'),
 ('DCH1070_Day1', 'Morning'),
 ('DCH1020 / SYM II_Day7', 'Morning'),
 ('DCH1020 / SYM II_Day7', 'Afternoon'),
 ('DCH1020 / SYM II_Day7', 'Evening'),
 ('GRW220_Day6', 'Afternoon'),

In [11]:
online_slots = []

for day in range(1, 8):
    online_day = f"Online_Day{day}"
    online_slots.append((online_day, 'Morning'))
    online_slots.append((online_day, 'Afternoon'))
    online_slots.append((online_day, 'Evening'))

all_slots = []
for item in in_person_slots:
    all_slots.append(item)
for item in online_slots:
    all_slots.append(item)

print(in_person_slots)
print(online_slots)
print(all_slots)

[('RZR227_Day7', 'Morning'), ('RZR227_Day7', 'Afternoon'), ('RZR227_Day7', 'Evening'), ('RZR227_Day3', 'Morning'), ('RZR227_Day3', 'Afternoon'), ('RZR227_Day3', 'Evening'), ('RZR302_Day5', 'Morning'), ('RZR302_Day5', 'Evening'), ('RZR302_Day1', 'Morning'), ('RZR302_Day1', 'Evening'), ('RZR302_Day4', 'Morning'), ('RZR302_Day4', 'Evening'), ('RZR302_Day6', 'Morning'), ('RZR302_Day6', 'Afternoon'), ('RZR302_Day6', 'Evening'), ('RZR302_Day2', 'Morning'), ('RZR302_Day2', 'Evening'), ('RZR302_Day7', 'Morning'), ('RZR302_Day7', 'Afternoon'), ('RZR302_Day7', 'Evening'), ('RZR302_Day3', 'Morning'), ('RZR302_Day3', 'Evening'), ('RZR304_Day5', 'Morning'), ('RZR304_Day5', 'Afternoon'), ('RZR304_Day5', 'Evening'), ('RZR304_Day1', 'Morning'), ('RZR205_Day3', 'Morning'), ('RZR205_Day3', 'Afternoon'), ('RZR205_Day3', 'Evening'), ('RZR227_Day5', 'Morning'), ('RZR227_Day5', 'Afternoon'), ('RZR227_Day5', 'Evening'), ('RZR227_Day1', 'Morning'), ('RZR227_Day1', 'Afternoon'), ('RZR227_Day1', 'Evening'), ('RZR227_Day4', 'Morning'), ('RZR227_Day4', 'Afternoon'), ('RZR227_Day4', 'Evening'), ('RZR227_Day6', 'Morning'), ('RZR227_Day6', 'Afternoon'), ('RZR227_Day6', 'Evening'), ('RZR227_Day2', 'Morning'), ('RZR227_Day2', 'Afternoon'), ('RZR227_Day2', 'Evening'), ('RZR305_Day3', 'Morning'), ('RZR305_Day3', 'Afternoon'), ('RZR305_Day3', 'Evening'), ('RZR310_Day5', 'Morning'), ('RZR310_Day5', 'Evening'), ('RZR310_Day1', 'Morning'), ('RZR310_Day1', 'Evening'), ('RZR310_Day4', 'Morning'), ('RZR310_Day4', 'Evening'), ('RZR310_Day6', 'Morning'), ('RZR310_Day6', 'Afternoon'), ('RZR310_Day6', 'Evening'), ('RZR310_Day2', 'Morning'), ('RZR310_Day2', 'Evening'), ('RZR310_Day7', 'Morning'), ('RZR310_Day7', 'Afternoon'), ('RZR310_Day7', 'Evening'), ('RZR310_Day3', 'Morning'), ('RZR304_Day1', 'Afternoon'), ('RZR304_Day1', 'Evening'), ('RZR304_Day4', 'Morning'), ('RZR304_Day4', 'Afternoon'), ('RZR304_Day4', 'Evening'), ('RZR304_Day6', 'Morning'), ('RZR304_Day6', 'Afternoon'), ('RZR304_Day6', 'Evening'), ('RZR304_Day2', 'Morning'), ('RZR304_Day2', 'Afternoon'), ('RZR304_Day2', 'Evening'), ('RZR304_Day7', 'Morning'), ('RZR304_Day7', 'Afternoon'), ('RZR304_Day7', 'Evening'), ('RZR304_Day3', 'Morning'), ('RZR304_Day3', 'Afternoon'), ('RZR304_Day3', 'Evening'), ('RZR305_Day5', 'Morning'), ('RZR305_Day5', 'Afternoon'), ('RZR305_Day5', 'Evening'), ('RZR305_Day1', 'Morning'), ('RZR305_Day1', 'Afternoon'), ('RZR305_Day1', 'Evening'), ('RZR305_Day4', 'Morning'), ('RZR305_Day4', 'Afternoon'), ('RZR305_Day4', 'Evening'), ('RZR305_Day6', 'Morning'), ('RZR305_Day6', 'Afternoon'), ('RZR305_Day6', 'Evening'), ('RZR305_Day2', 'Morning'), ('RZR305_Day2', 'Afternoon'), ('RZR305_Day2', 'Evening'), ('RZR305_Day7', 'Morning'), ('RZR305_Day7', 'Afternoon'), ('RZR305_Day7', 'Evening'), ('SEW133_Day2', 'Morning'), ('SEW133_Day2', 'Afternoon'), ('SEW133_Day2', 'Evening'), ('SEW133_Day7', 'Morning'), ('SEW133_Day7', 'Afternoon'), ('SEW133_Day7', 'Evening'), ('SEW133_Day3', 'Morning'), ('SEW133_Day3', 'Afternoon'), ('SEW133_Day3', 'Evening'), ('SEW301_Day5', 'Morning'), ('SEW301_Day5', 'Afternoon'), ('SEW301_Day5', 'Evening'), ('SEW301_Day1', 'Morning'), ('SEW301_Day1', 'Afternoon'), ('SEW301_Day1', 'Evening'), ('SEW301_Day4', 'Morning'), ('SEW301_Day4', 'Afternoon'), ('SEW301_Day4', 'Evening'), ('SEW301_Day6', 'Morning'), ('SEW301_Day6', 'Afternoon'), ('SEW301_Day6', 'Evening'), ('SEW301_Day2', 'Morning'), ('SEW301_Day2', 'Afternoon'), ('SEW301_Day2', 'Evening'), ('RZR310_Day3', 'Evening'), ('SEW101_Day5', 'Morning'), ('SEW101_Day5', 'Afternoon'), ('SEW101_Day5', 'Evening'), ('SEW101_Day1', 'Morning'), ('SEW101_Day1', 'Afternoon'), ('SEW101_Day1', 'Evening'), ('SEW101_Day4', 'Morning'), ('SEW101_Day4', 'Afternoon'), ('SEW101_Day4', 'Evening'), ('SEW101_Day6', 'Morning'), ('SEW101_Day6', 'Afternoon'), ('SEW101_Day6', 'Evening'), ('SEW101_Day2', 'Morning'), ('SEW101_Day2', 'Afternoon'), ('SEW101_Day2', 'Evening'), ('SEW101_Day7', 'Morning'), ('SEW101_Day7', 'Afternoon'), ('SEW101_Day7', 'Evening'), ('SEW101_Day3', 'Morning'), ('SEW101_Day3', 'Afternoon'), ('SEW101_Day3', 'Evening'), ('SEW133_Day5', 'Morning'), ('SEW133_Day5', 'Afternoon'), ('SEW133_Day5', 'Evening'), ('SEW133_Day1', 'Morning'), ('SEW133_Day1', 'Afternoon'), ('SEW133_Day1', 'Evening'), ('SEW133_Day4', 'Morning'), ('SEW133_Day4', 'Afternoon'), ('SEW133_Day4', 'Evening'), ('SEW133_Day6', 'Morning'), ('SEW133_Day6', 'Afternoon'), ('SEW133_Day6', 'Evening'), ('SEW305_Day4', 'Morning'), ('SEW305_Day4', 'Afternoon'), ('SEW305_Day4', 'Evening'), ('SEW305_Day6', 'Morning'), ('SEW305_Day6', 'Afternoon'), ('SEW305_Day6', 'Evening'), ('SEW305_Day2', 'Morning'), ('SEW305_Day2', 'Afternoon'), ('SEW305_Day2', 'Evening'), ('SEW305_Day7', 'Morning'), ('SEW305_Day7', 'Afternoon'), ('SEW305_Day7', 'Evening'), ('SEW305_Day3', 'Morning'), ('SEW305_Day3', 'Afternoon'), ('SEW305_Day3', 'Evening'), ('SEW307_Day5', 'Morning'), ('SEW307_Day5', 'Afternoon'), ('SEW307_Day5', 'Evening'), ('SEW307_Day1', 'Morning'), ('SEW307_Day1', 'Afternoon'), ('SEW307_Day1', 'Evening'), ('SEW307_Day4', 'Morning'), ('SEW307_Day4', 'Afternoon'), ('SEW307_Day4', 'Evening'), ('SEW301_Day7', 'Morning'), ('SEW301_Day7', 'Afternoon'), ('SEW301_Day7', 'Evening'), ('SEW301_Day3', 'Morning'), ('SEW301_Day3', 'Afternoon'), ('SEW301_Day3', 'Evening'), ('SEW303_Day5', 'Morning'), ('SEW303_Day5', 'Afternoon'), ('SEW303_Day5', 'Evening'), ('SEW303_Day1', 'Morning'), ('SEW303_Day1', 'Afternoon'), ('SEW303_Day1', 'Evening'), ('SEW303_Day4', 'Morning'), ('SEW303_Day4', 'Afternoon'), ('SEW303_Day4', 'Evening'), ('SEW303_Day6', 'Morning'), ('SEW303_Day6', 'Afternoon'), ('SEW303_Day6', 'Evening'), ('SEW303_Day2', 'Morning'), ('SEW303_Day2', 'Afternoon'), ('SEW303_Day2', 'Evening'), ('SEW303_Day7', 'Morning'), ('SEW303_Day7', 'Afternoon'), ('SEW303_Day7', 'Evening'), ('SEW303_Day3', 'Morning'), ('SEW303_Day3', 'Afternoon'), ('SEW303_Day3', 'Evening'), ('SEW305_Day5', 'Morning'), ('SEW305_Day5', 'Afternoon'), ('SEW305_Day5', 'Evening'), ('SEW305_Day1', 'Morning'), ('SEW305_Day1', 'Afternoon'), ('SEW305_Day1', 'Evening'), ('SEW460_Day5', 'Evening'), ('SEW460_Day1', 'Morning'), ('SEW460_Day1', 'Afternoon'), ('SEW460_Day1', 'Evening'), ('SEW460_Day4', 'Morning'), ('SEW460_Day4', 'Afternoon'), ('SEW460_Day4', 'Evening'), ('SEW460_Day6', 'Morning'), ('SEW460_Day6', 'Afternoon'), ('SEW460_Day6', 'Evening'), ('SEW460_Day2', 'Morning'), ('SEW460_Day2', 'Afternoon'), ('SEW460_Day2', 'Evening'), ('SEW460_Day7', 'Morning'), ('SEW460_Day7', 'Afternoon'), ('SEW460_Day7', 'Evening'), ('SEW460_Day3', 'Morning'), ('SEW460_Day3', 'Afternoon'), ('SEW460_Day3', 'Evening'), ('SEW462_Day5', 'Morning'), ('SEW462_Day5', 'Evening'), ('SEW307_Day6', 'Morning'), ('SEW307_Day6', 'Afternoon'), ('SEW307_Day6', 'Evening'), ('SEW307_Day2', 'Morning'), ('SEW307_Day2', 'Afternoon'), ('SEW307_Day2', 'Evening'), ('SEW307_Day7', 'Morning'), ('SEW307_Day7', 'Afternoon'), ('SEW307_Day7', 'Evening'), ('SEW307_Day3', 'Morning'), ('SEW307_Day3', 'Afternoon'), ('SEW307_Day3', 'Evening'), ('SEW309_Day5', 'Morning'), ('SEW309_Day5', 'Afternoon'), ('SEW309_Day5', 'Evening'), ('SEW309_Day1', 'Morning'), ('SEW309_Day1', 'Afternoon'), ('SEW309_Day1', 'Evening'), ('SEW309_Day4', 'Morning'), ('SEW309_Day4', 'Afternoon'), ('SEW309_Day4', 'Evening'), ('SEW309_Day6', 'Morning'), ('SEW309_Day6', 'Afternoon'), ('SEW309_Day6', 'Evening'), ('SEW309_Day2', 'Morning'), ('SEW309_Day2', 'Afternoon'), ('SEW309_Day2', 'Evening'), ('SEW309_Day7', 'Morning'), ('SEW309_Day7', 'Afternoon'), ('SEW309_Day7', 'Evening'), ('SEW309_Day3', 'Morning'), ('SEW309_Day3', 'Afternoon'), ('SEW309_Day3', 'Evening'), ('SEW460_Day5', 'Morning'), ('SEW460_Day5', 'Afternoon'), ('ABL131_Day2', 'Afternoon'), ('ABL131_Day2', 'Evening'), ('ABL131_Day7', 'Morning'), ('ABL131_Day7', 'Afternoon'), ('ABL131_Day7', 'Evening'), ('ABL131_Day3', 'Morning'), ('ABL131_Day3', 'Afternoon'), ('ABL131_Day3', 'Evening'), ('ANH117_Day5', 'Morning'), ('ANH117_Day5', 'Afternoon'), ('ANH117_Day5', 'Evening'), ('ANH117_Day1', 'Morning'), ('ANH117_Day1', 'Afternoon'), ('ANH117_Day1', 'Evening'), ('ANH117_Day4', 'Morning'), ('ANH117_Day4', 'Afternoon'), ('ANH117_Day4', 'Evening'), ('ANH117_Day6', 'Morning'), ('ANH117_Day6', 'Afternoon'), ('ANH117_Day6', 'Evening'), ('ANH117_Day2', 'Morning'), ('ANH117_Day2', 'Afternoon'), ('ANH117_Day2', 'Evening'), ('ABL130_Day5', 'Morning'), ('ABL130_Day5', 'Afternoon'), ('ABL130_Day5', 'Evening'), ('ABL130_Day1', 'Morning'), ('ABL130_Day1', 'Afternoon'), ('ABL130_Day1', 'Evening'), ('ABL130_Day4', 'Morning'), ('ABL130_Day4', 'Afternoon'), ('ABL130_Day4', 'Evening'), ('ABL130_Day6', 'Morning'), ('ABL130_Day6', 'Afternoon'), ('ABL130_Day6', 'Evening'), ('ABL130_Day2', 'Morning'), ('ABL130_Day2', 'Afternoon'), ('ABL130_Day2', 'Evening'), ('ABL130_Day7', 'Morning'), ('ABL130_Day7', 'Afternoon'), ('ABL130_Day7', 'Evening'), ('ABL130_Day3', 'Morning'), ('ABL130_Day3', 'Afternoon'), ('ABL130_Day3', 'Evening'), ('ABL131_Day5', 'Morning'), ('ABL131_Day5', 'Afternoon'), ('ABL131_Day5', 'Evening'), ('ABL131_Day1', 'Morning'), ('ABL131_Day1', 'Afternoon'), ('ABL131_Day1', 'Evening'), ('ABL131_Day4', 'Morning'), ('ABL131_Day4', 'Afternoon'), ('ABL131_Day4', 'Evening'), ('ABL131_Day6', 'Morning'), ('ABL131_Day6', 'Afternoon'), ('ABL131_Day6', 'Evening'), ('ABL131_Day2', 'Morning'), ('BKH116_Day4', 'Evening'), ('BKH116_Day6', 'Morning'), ('BKH116_Day6', 'Afternoon'), ('BKH116_Day6', 'Evening'), ('BKH116_Day2', 'Morning'), ('BKH116_Day2', 'Afternoon'), ('BKH116_Day2', 'Evening'), ('BKH116_Day7', 'Morning'), ('BKH116_Day7', 'Afternoon'), ('BKH116_Day7', 'Evening'), ('BKH116_Day3', 'Morning'), ('BKH116_Day3', 'Afternoon'), ('BKH116_Day3', 'Evening'), ('BKH229_Day5', 'Morning'), ('BKH229_Day5', 'Afternoon'), ('BKH229_Day5', 'Evening'), ('BKH229_Day1', 'Morning'), ('BKH229_Day1', 'Afternoon'), ('BKH229_Day1', 'Evening'), ('BKH229_Day4', 'Morning'), ('BKH229_Day4', 'Afternoon'), ('BKH229_Day4', 'Evening'), ('ANH117_Day7', 'Morning'), ('ANH117_Day7', 'Afternoon'), ('ANH117_Day7', 'Evening'), ('ANH117_Day3', 'Morning'), ('ANH117_Day3', 'Afternoon'), ('ANH117_Day3', 'Evening'), ('BKH102_Day5', 'Morning'), ('BKH102_Day5', 'Afternoon'), ('BKH102_Day5', 'Evening'), ('BKH102_Day1', 'Morning'), ('BKH102_Day1', 'Afternoon'), ('BKH102_Day1', 'Evening'), ('BKH102_Day4', 'Morning'), ('BKH102_Day4', 'Afternoon'), ('BKH102_Day4', 'Evening'), ('BKH102_Day6', 'Morning'), ('BKH102_Day6', 'Afternoon'), ('BKH102_Day6', 'Evening'), ('BKH102_Day2', 'Morning'), ('BKH102_Day2', 'Afternoon'), ('BKH102_Day2', 'Evening'), ('BKH102_Day7', 'Morning'), ('BKH102_Day7', 'Afternoon'), ('BKH102_Day7', 'Evening'), ('BKH102_Day3', 'Morning'), ('BKH102_Day3', 'Afternoon'), ('BKH102_Day3', 'Evening'), ('BKH116_Day5', 'Morning'), ('BKH116_Day5', 'Afternoon'), ('BKH116_Day5', 'Evening'), ('BKH116_Day1', 'Morning'), ('BKH116_Day1', 'Afternoon'), ('BKH116_Day1', 'Evening'), ('BKH116_Day4', 'Morning'), ('BKH116_Day4', 'Afternoon'), ('BRK103_Day2', 'Morning'), ('BRK103_Day2', 'Afternoon'), ('BRK103_Day2', 'Evening'), ('BRK103_Day7', 'Morning'), ('DCH1042_Day6', 'Afternoon'), ('DCH1042_Day6', 'Evening'), ('DCH1042_Day2', 'Morning'), ('DCH1042_Day2', 'Afternoon'), ('DCH1042_Day2', 'Evening'), ('BKH233_Day3', 'Afternoon'), ('BKH233_Day3', 'Evening'), ('BRC282_Day5', 'Morning'), ('BRC282_Day5', 'Afternoon'), ('BRC282_Day5', 'Evening'), ('BRC285_Day3', 'Morning'), ('BRC285_Day3', 'Afternoon'), ('BRC285_Day3', 'Evening'), ('BRC286_Day5', 'Morning'), ('BRK103_Day7', 'Afternoon'), ('BRK103_Day7', 'Evening'), ('BRK103_Day3', 'Morning'), ('BRK103_Day3', 'Afternoon'), ('DCH1042_Day7', 'Morning'), ('DCH1042_Day7', 'Afternoon'), ('DCH1042_Day7', 'Evening'), ('BRC282_Day1', 'Morning'), ('BRC282_Day1', 'Afternoon'), ('BRC282_Day1', 'Evening'), ('BRC286_Day5', 'Afternoon'), ('BRC286_Day5', 'Evening'), ('BRC286_Day1', 'Morning'), ('BRC286_Day1', 'Afternoon'), ('BRK103_Day3', 'Evening'), ('DBH180_Day5', 'Morning'), ('DCH1042_Day3', 'Morning'), ('DCH1042_Day3', 'Afternoon'), ('DCH1042_Day3', 'Evening'), ('BRC282_Day4', 'Morning'), ('BRC282_Day4', 'Afternoon'), ('BRC282_Day4', 'Evening'), ('BRC286_Day1', 'Evening'), ('BRC286_Day4', 'Morning'), ('BRC286_Day4', 'Afternoon'), ('BRC286_Day4', 'Evening'), ('DBH180_Day1', 'Morning'), ('DCH1046_Day5', 'Morning'), ('DCH1046_Day5', 'Afternoon'), ('DCH1046_Day5', 'Evening'), ('DCH1046_Day1', 'Morning'), ('BRC282_Day6', 'Morning'), ('BRC282_Day6', 'Afternoon'), ('BRC282_Day6', 'Evening'), ('BRC282_Day2', 'Morning'), ('BRC282_Day2', 'Afternoon'), ('BRC286_Day6', 'Morning'), ('BRC286_Day6', 'Afternoon'), ('BRC286_Day6', 'Evening'), ('DBH180_Day4', 'Morning'), ('DCH1046_Day1', 'Afternoon'), ('DCH1046_Day1', 'Evening'), ('DCH1046_Day4', 'Morning'), ('DCH1046_Day4', 'Afternoon'), ('BRC282_Day2', 'Evening'), ('BRC282_Day7', 'Morning'), ('BRC282_Day7', 'Afternoon'), ('BRC282_Day7', 'Evening'), ('BRC286_Day2', 'Morning'), ('BRC286_Day2', 'Afternoon'), ('BRC286_Day2', 'Evening'), ('BRC286_Day7', 'Morning'), ('DBH180_Day2', 'Morning'), ('DCH1046_Day4', 'Evening'), ('DCH1046_Day6', 'Morning'), ('DCH1046_Day6', 'Afternoon'), ('DCH1046_Day6', 'Evening'), ('BRC282_Day3', 'Morning'), ('BRC282_Day3', 'Afternoon'), ('BRC282_Day3', 'Evening'), ('BRC286_Day7', 'Afternoon'), ('BRC286_Day7', 'Evening'), ('BRC286_Day3', 'Morning'), ('BRC286_Day3', 'Afternoon'), ('BRC286_Day3', 'Evening'), ('DCH1046_Day2', 'Morning'), ('DCH1046_Day2', 'Afternoon'), ('DCH1046_Day2', 'Evening'), ('BRC284_Day5', 'Morning'), ('BRC284_Day5', 'Afternoon'), ('BRC284_Day5', 'Evening'), ('BRC284_Day1', 'Morning'), ('BRK101_Day5', 'Morning'), ('BRK101_Day5', 'Afternoon'), ('BRK101_Day5', 'Evening'), ('DBH180_Day3', 'Morning'), ('DCC113_Day5', 'Morning'), ('DCH1046_Day7', 'Morning'), ('DCH1046_Day7', 'Afternoon'), ('DCH1046_Day7', 'Evening'), ('DCH1046_Day3', 'Morning'), ('BRC284_Day1', 'Afternoon'), ('BRC284_Day1', 'Evening'), ('BRC284_Day4', 'Morning'), ('BRC284_Day4', 'Afternoon'), ('BRK101_Day1', 'Morning'), ('BRK101_Day1', 'Afternoon'), ('BRK101_Day1', 'Evening'), ('DCC113_Day5', 'Afternoon'), ('DCC113_Day1', 'Morning'), ('DCC113_Day1', 'Afternoon'), ('BKH229_Day6', 'Morning'), ('BKH229_Day6', 'Afternoon'), ('BKH229_Day6', 'Evening'), ('BKH229_Day2', 'Morning'), ('BRC284_Day4', 'Evening'), ('BRC284_Day6', 'Morning'), ('BRC284_Day6', 'Afternoon'), ('BRC284_Day6', 'Evening'), ('BRK101_Day4', 'Morning'), ('BRK101_Day4', 'Afternoon'), ('BRK101_Day4', 'Evening'), ('BRK101_Day6', 'Morning'), ('DCC113_Day4', 'Morning'), ('DCC113_Day4', 'Afternoon'), ('BKH229_Day2', 'Afternoon'), ('BKH229_Day2', 'Evening'), ('BKH229_Day7', 'Morning'), ('BKH229_Day7', 'Afternoon'), ('BKH229_Day7', 'Evening'), ('BRC284_Day2', 'Morning'), ('BRC284_Day2', 'Afternoon'), ('BRC284_Day2', 'Evening'), ('BRK101_Day6', 'Afternoon'), ('BRK101_Day6', 'Evening'), ('BRK101_Day2', 'Morning'), ('BRK101_Day2', 'Afternoon'), ('BRK101_Day2', 'Evening'), ('BKH229_Day3', 'Morning'), ('BKH229_Day3', 'Afternoon'), ('BKH229_Day3', 'Evening'), ('BRC284_Day7', 'Morning'), ('BRC284_Day7', 'Afternoon'), ('BRC284_Day7', 'Evening'), ('BRC284_Day3', 'Morning'), ('BRC284_Day3', 'Afternoon'), ('BRK101_Day7', 'Morning'), ('BRK101_Day7', 'Afternoon'), ('BRK101_Day7', 'Evening'), ('DCC113_Day2', 'Morning'), ('DCC113_Day2', 'Afternoon'), ('BKH233_Day5', 'Morning'), ('BKH233_Day5', 'Afternoon'), ('BKH233_Day5', 'Evening'), ('BKH233_Day1', 'Morning'), ('BRC284_Day3', 'Evening'), ('BRC285_Day5', 'Morning'), ('BRC285_Day5', 'Afternoon'), ('BRC285_Day5', 'Evening'), ('BRK101_Day3', 'Morning'), ('BRK101_Day3', 'Afternoon'), ('BRK101_Day3', 'Evening'), ('DCC113_Day3', 'Morning'), ('DCC113_Day3', 'Afternoon'), ('BKH233_Day1', 'Afternoon'), ('BKH233_Day1', 'Evening'), ('BKH233_Day4', 'Morning'), ('BKH233_Day4', 'Afternoon'), ('BRC285_Day1', 'Morning'), ('BRC285_Day1', 'Afternoon'), ('BRC285_Day1', 'Evening'), ('BRK103_Day5', 'Morning'), ('BRK103_Day5', 'Afternoon'), ('BRK103_Day5', 'Evening'), ('BRK103_Day1', 'Morning'), ('BRK103_Day1', 'Afternoon'), ('DCH1042_Day5', 'Morning'), ('DCH1042_Day5', 'Afternoon'), ('DCH1042_Day5', 'Evening'), ('BKH233_Day4', 'Evening'), ('BKH233_Day6', 'Morning'), ('BKH233_Day6', 'Afternoon'), ('BKH233_Day6', 'Evening'), ('BRC285_Day4', 'Morning'), ('BRC285_Day4', 'Afternoon'), ('BRC285_Day4', 'Evening'), ('BRC285_Day6', 'Morning'), ('BRK103_Day1', 'Evening'), ('BRK103_Day4', 'Morning'), ('BRK103_Day4', 'Afternoon'), ('BRK103_Day4', 'Evening'), ('DCH1042_Day1', 'Morning'), ('DCH1042_Day1', 'Afternoon'), ('DCH1042_Day1', 'Evening'), ('BKH233_Day2', 'Morning'), ('BKH233_Day2', 'Afternoon'), ('BKH233_Day2', 'Evening'), ('BRC285_Day6', 'Afternoon'), ('BRC285_Day6', 'Evening'), ('BRC285_Day2', 'Morning'), ('BRC285_Day2', 'Afternoon'), ('BRC285_Day2', 'Evening'), ('BRK103_Day6', 'Morning'), ('BRK103_Day6', 'Afternoon'), ('BRK103_Day6', 'Evening'), ('DCH1042_Day4', 'Morning'), ('DCH1042_Day4', 'Afternoon'), ('DCH1042_Day4', 'Evening'), ('DCH1042_Day6', 'Morning'), ('BKH233_Day7', 'Morning'), ('BKH233_Day7', 'Afternoon'), ('BKH233_Day7', 'Evening'), ('BKH233_Day3', 'Morning'), ('BRC285_Day7', 'Morning'), ('BRC285_Day7', 'Afternoon'), ('BRC285_Day7', 'Evening'), ('GRBW212_Day2', 'Morning'), ('GRBW212_Day2', 'Afternoon'), ('GRBW212_Day2', 'Evening'), ('GRBW212_Day7', 'Morning'), ('HBH227_Day6', 'Afternoon'), ('HBH227_Day6', 'Evening'), ('HBH227_Day2', 'Morning'), ('HBH227_Day2', 'Afternoon'), ('DCH1064_Day4', 'Morning'), ('DCH1064_Day4', 'Afternoon'), ('DCH1064_Day4', 'Evening'), ('DCH1064_Day6', 'Morning'), ('DCH1020 / SYM II_Day1', 'Morning'), ('DCH1020 / SYM II_Day1', 'Afternoon'), ('DCH1020 / SYM II_Day1', 'Evening'), ('GRBW212_Day7', 'Afternoon'), ('GRBW212_Day7', 'Evening'), ('GRBW212_Day3', 'Morning'), ('GRBW212_Day3', 'Afternoon'), ('HBH227_Day2', 'Evening'), ('HBH227_Day7', 'Morning'), ('HBH227_Day7', 'Afternoon'), ('HBH227_Day7', 'Evening'), ('DCH1064_Day6', 'Afternoon'), ('DCH1064_Day6', 'Evening'), ('DCH1064_Day2', 'Morning'), ('DCH1064_Day2', 'Afternoon'), ('DCH1020 / SYM II_Day4', 'Morning'), ('DCH1020 / SYM II_Day4', 'Afternoon'), ('DCH1020 / SYM II_Day4', 'Evening'), ('GRBW212_Day3', 'Evening'), ('GRW220_Day5', 'Morning'), ('GRW220_Day5', 'Afternoon'), ('HBH227_Day3', 'Morning'), ('HBH227_Day3', 'Afternoon'), ('HBH227_Day3', 'Evening'), ('DCH1064_Day2', 'Evening'), ('DCH1064_Day7', 'Morning'), ('DCH1064_Day7', 'Afternoon'), ('DCH1064_Day7', 'Evening'), ('DCH1020 / SYM II_Day6', 'Morning'), ('DCH1020 / SYM II_Day6', 'Afternoon'), ('DCH1020 / SYM II_Day6', 'Evening'), ('GRW220_Day1', 'Morning'), ('GRW220_Day1', 'Afternoon'), ('HBH423_Day5', 'Morning'), ('HBH423_Day5', 'Afternoon'), ('HBH423_Day5', 'Evening'), ('HBH423_Day1', 'Morning'), ('DCH1064_Day3', 'Morning'), ('DCH1064_Day3', 'Afternoon'), ('DCH1064_Day3', 'Evening'), ('DCH1020 / SYM II_Day2', 'Morning'), ('DCH1020 / SYM II_Day2', 'Afternoon'), ('DCH1020 / SYM II_Day2', 'Evening'), ('GRW220_Day4', 'Morning'), ('GRW220_Day4', 'Afternoon'), ('GRW220_Day6', 'Morning'), ('HBH423_Day1', 'Afternoon'), ('HBH423_Day1', 'Evening'), ('HBH423_Day4', 'Morning'), ('HBH423_Day4', 'Afternoon'), ('HBH423_Day4', 'Evening'), ('DCH1070_Day5', 'Morning'), ('DCH1070_Day5', 'Afternoon'), ('DCH1070_Day5', 'Evening'), ('DCH1070_Day1', 'Morning'), ('DCH1020 / SYM II_Day7', 'Morning'), ('DCH1020 / SYM II_Day7', 'Afternoon'), ('DCH1020 / SYM II_Day7', 'Evening'), ('GRW220_Day6', 'Afternoon'), ('GRW220_Day2', 'Morning'), ('GRW220_Day2', 'Afternoon'), ('HBH423_Day6', 'Morning'), ('HBH423_Day6', 'Afternoon'), ('HBH423_Day6', 'Evening'), ('DCH1070_Day1', 'Afternoon'), ('DCH1070_Day1', 'Evening'), ('DCH1070_Day4', 'Morning'), ('DCH1070_Day4', 'Afternoon'), ('DCH1020 / SYM II_Day3', 'Morning'), ('DCH1020 / SYM II_Day3', 'Afternoon'), ('DCH1020 / SYM II_Day3', 'Evening'), ('GRW220_Day7', 'Morning'), ('GRW220_Day7', 'Afternoon'), ('HBH423_Day2', 'Morning'), ('HBH423_Day2', 'Afternoon'), ('HBH423_Day2', 'Evening'), ('HBH423_Day7', 'Morning'), ('DCH1070_Day4', 'Evening'), ('DCH1070_Day6', 'Morning'), ('DCH1070_Day6', 'Afternoon'), ('DCH1070_Day6', 'Evening'), ('G

In [18]:
print(online_slots)

[('Online_Day1', 'Morning'), ('Online_Day1', 'Afternoon'), ('Online_Day1', 'Evening'), ('Online_Day2', 'Morning'), ('Online_Day2', 'Afternoon'), ('Online_Day2', 'Evening'), ('Online_Day3', 'Morning'), ('Online_Day3', 'Afternoon'), ('Online_Day3', 'Evening'), ('Online_Day4', 'Morning'), ('Online_Day4', 'Afternoon'), ('Online_Day4', 'Evening'), ('Online_Day5', 'Morning'), ('Online_Day5', 'Afternoon'), ('Online_Day5', 'Evening'), ('Online_Day6', 'Morning'), ('Online_Day6', 'Afternoon'), ('Online_Day6', 'Evening'), ('Online_Day7', 'Morning'), ('Online_Day7', 'Afternoon'), ('Online_Day7', 'Evening')]

In [12]:
# Assuming room_capacity, inperson_slots, and online_slots are already defined as per your setup

# Initialize an empty dictionary to store slot capacities
slot_capacities = {}

# Merge in-in_person_slots slots with capacities
for slot in in_person_slots:
    # Extract the room identifier from the slot (before "_Day")
    room = slot[0].split('_Day')[0]
    # Use the room to get the capacity from room_capacity
    capacity = room_capacity.get(room, 0)  # Default to 0 if room not found
    # Add the slot and its capacity to the dictionary
    slot_capacities[slot] = capacity

# Merge online slots with capacities
# Assuming infinite capacity for online slots
for slot in online_slots:
    slot_capacities[slot] = float('inf')

# Now slot_capacities contains all slots as keys and their capacities as values
print(slot_capacities)

{('RZR227_Day7', 'Morning'): 12, ('RZR227_Day7', 'Afternoon'): 12, ('RZR227_Day7', 'Evening'): 12, ('RZR227_Day3', 'Morning'): 12, ('RZR227_Day3', 'Afternoon'): 12, ('RZR227_Day3', 'Evening'): 12, ('RZR302_Day5', 'Morning'): 12, ('RZR302_Day5', 'Evening'): 12, ('RZR302_Day1', 'Morning'): 12, ('RZR302_Day1', 'Evening'): 12, ('RZR302_Day4', 'Morning'): 12, ('RZR302_Day4', 'Evening'): 12, ('RZR302_Day6', 'Morning'): 12, ('RZR302_Day6', 'Afternoon'): 12, ('RZR302_Day6', 'Evening'): 12, ('RZR302_Day2', 'Morning'): 12, ('RZR302_Day2', 'Evening'): 12, ('RZR302_Day7', 'Morning'): 12, ('RZR302_Day7', 'Afternoon'): 12, ('RZR302_Day7', 'Evening'): 12, ('RZR302_Day3', 'Morning'): 12, ('RZR302_Day3', 'Evening'): 12, ('RZR304_Day5', 'Morning'): 20, ('RZR304_Day5', 'Afternoon'): 20, ('RZR304_Day5', 'Evening'): 20, ('RZR304_Day1', 'Morning'): 20, ('RZR205_Day3', 'Morning'): 20, ('RZR205_Day3', 'Afternoon'): 20, ('RZR205_Day3', 'Evening'): 20, ('RZR227_Day5', 'Morning'): 12, ('RZR227_Day5', 'Afternoon'): 12, ('RZR227_Day5', 'Evening'): 12, ('RZR227_Day1', 'Morning'): 12, ('RZR227_Day1', 'Afternoon'): 12, ('RZR227_Day1', 'Evening'): 12, ('RZR227_Day4', 'Morning'): 12, ('RZR227_Day4', 'Afternoon'): 12, ('RZR227_Day4', 'Evening'): 12, ('RZR227_Day6', 'Morning'): 12, ('RZR227_Day6', 'Afternoon'): 12, ('RZR227_Day6', 'Evening'): 12, ('RZR227_Day2', 'Morning'): 12, ('RZR227_Day2', 'Afternoon'): 12, ('RZR227_Day2', 'Evening'): 12, ('RZR305_Day3', 'Morning'): 20, ('RZR305_Day3', 'Afternoon'): 20, ('RZR305_Day3', 'Evening'): 20, ('RZR310_Day5', 'Morning'): 12, ('RZR310_Day5', 'Evening'): 12, ('RZR310_Day1', 'Morning'): 12, ('RZR310_Day1', 'Evening'): 12, ('RZR310_Day4', 'Morning'): 12, ('RZR310_Day4', 'Evening'): 12, ('RZR310_Day6', 'Morning'): 12, ('RZR310_Day6', 'Afternoon'): 12, ('RZR310_Day6', 'Evening'): 12, ('RZR310_Day2', 'Morning'): 12, ('RZR310_Day2', 'Evening'): 12, ('RZR310_Day7', 'Morning'): 12, ('RZR310_Day7', 'Afternoon'): 12, ('RZR310_Day7', 'Evening'): 12, ('RZR310_Day3', 'Morning'): 12, ('RZR304_Day1', 'Afternoon'): 20, ('RZR304_Day1', 'Evening'): 20, ('RZR304_Day4', 'Morning'): 20, ('RZR304_Day4', 'Afternoon'): 20, ('RZR304_Day4', 'Evening'): 20, ('RZR304_Day6', 'Morning'): 20, ('RZR304_Day6', 'Afternoon'): 20, ('RZR304_Day6', 'Evening'): 20, ('RZR304_Day2', 'Morning'): 20, ('RZR304_Day2', 'Afternoon'): 20, ('RZR304_Day2', 'Evening'): 20, ('RZR304_Day7', 'Morning'): 20, ('RZR304_Day7', 'Afternoon'): 20, ('RZR304_Day7', 'Evening'): 20, ('RZR304_Day3', 'Morning'): 20, ('RZR304_Day3', 'Afternoon'): 20, ('RZR304_Day3', 'Evening'): 20, ('RZR305_Day5', 'Morning'): 20, ('RZR305_Day5', 'Afternoon'): 20, ('RZR305_Day5', 'Evening'): 20, ('RZR305_Day1', 'Morning'): 20, ('RZR305_Day1', 'Afternoon'): 20, ('RZR305_Day1', 'Evening'): 20, ('RZR305_Day4', 'Morning'): 20, ('RZR305_Day4', 'Afternoon'): 20, ('RZR305_Day4', 'Evening'): 20, ('RZR305_Day6', 'Morning'): 20, ('RZR305_Day6', 'Afternoon'): 20, ('RZR305_Day6', 'Evening'): 20, ('RZR305_Day2', 'Morning'): 20, ('RZR305_Day2', 'Afternoon'): 20, ('RZR305_Day2', 'Evening'): 20, ('RZR305_Day7', 'Morning'): 20, ('RZR305_Day7', 'Afternoon'): 20, ('RZR305_Day7', 'Evening'): 20, ('SEW133_Day2', 'Morning'): 24, ('SEW133_Day2', 'Afternoon'): 24, ('SEW133_Day2', 'Evening'): 24, ('SEW133_Day7', 'Morning'): 24, ('SEW133_Day7', 'Afternoon'): 24, ('SEW133_Day7', 'Evening'): 24, ('SEW133_Day3', 'Morning'): 24, ('SEW133_Day3', 'Afternoon'): 24, ('SEW133_Day3', 'Evening'): 24, ('SEW301_Day5', 'Morning'): 168, ('SEW301_Day5', 'Afternoon'): 168, ('SEW301_Day5', 'Evening'): 168, ('SEW301_Day1', 'Morning'): 168, ('SEW301_Day1', 'Afternoon'): 168, ('SEW301_Day1', 'Evening'): 168, ('SEW301_Day4', 'Morning'): 168, ('SEW301_Day4', 'Afternoon'): 168, ('SEW301_Day4', 'Evening'): 168, ('SEW301_Day6', 'Morning'): 168, ('SEW301_Day6', 'Afternoon'): 168, ('SEW301_Day6', 'Evening'): 168, ('SEW301_Day2', 'Morning'): 168, ('SEW301_Day2', 'Afternoon'): 168, ('SEW301_Day2', 'Evening'): 168, ('RZR310_Day3', 'Evening'): 12, ('SEW101_Day5', 'Morning'): 36, ('SEW101_Day5', 'Afternoon'): 36, ('SEW101_Day5', 'Evening'): 36, ('SEW101_Day1', 'Morning'): 36, ('SEW101_Day1', 'Afternoon'): 36, ('SEW101_Day1', 'Evening'): 36, ('SEW101_Day4', 'Morning'): 36, ('SEW101_Day4', 'Afternoon'): 36, ('SEW101_Day4', 'Evening'): 36, ('SEW101_Day6', 'Morning'): 36, ('SEW101_Day6', 'Afternoon'): 36, ('SEW101_Day6', 'Evening'): 36, ('SEW101_Day2', 'Morning'): 36, ('SEW101_Day2', 'Afternoon'): 36, ('SEW101_Day2', 'Evening'): 36, ('SEW101_Day7', 'Morning'): 36, ('SEW101_Day7', 'Afternoon'): 36, ('SEW101_Day7', 'Evening'): 36, ('SEW101_Day3', 'Morning'): 36, ('SEW101_Day3', 'Afternoon'): 36, ('SEW101_Day3', 'Evening'): 36, ('SEW133_Day5', 'Morning'): 24, ('SEW133_Day5', 'Afternoon'): 24, ('SEW133_Day5', 'Evening'): 24, ('SEW133_Day1', 'Morning'): 24, ('SEW133_Day1', 'Afternoon'): 24, ('SEW133_Day1', 'Evening'): 24, ('SEW133_Day4', 'Morning'): 24, ('SEW133_Day4', 'Afternoon'): 24, ('SEW133_Day4', 'Evening'): 24, ('SEW133_Day6', 'Morning'): 24, ('SEW133_Day6', 'Afternoon'): 24, ('SEW133_Day6', 'Evening'): 24, ('SEW305_Day4', 'Morning'): 45, ('SEW305_Day4', 'Afternoon'): 45, ('SEW305_Day4', 'Evening'): 45, ('SEW305_Day6', 'Morning'): 45, ('SEW305_Day6', 'Afternoon'): 45, ('SEW305_Day6', 'Evening'): 45, ('SEW305_Day2', 'Morning'): 45, ('SEW305_Day2', 'Afternoon'): 45, ('SEW305_Day2', 'Evening'): 45, ('SEW305_Day7', 'Morning'): 45, ('SEW305_Day7', 'Afternoon'): 45, ('SEW305_Day7', 'Evening'): 45, ('SEW305_Day3', 'Morning'): 45, ('SEW305_Day3', 'Afternoon'): 45, ('SEW305_Day3', 'Evening'): 45, ('SEW307_Day5', 'Morning'): 45, ('SEW307_Day5', 'Afternoon'): 45, ('SEW307_Day5', 'Evening'): 45, ('SEW307_Day1', 'Morning'): 45, ('SEW307_Day1', 'Afternoon'): 45, ('SEW307_Day1', 'Evening'): 45, ('SEW307_Day4', 'Morning'): 45, ('SEW307_Day4', 'Afternoon'): 45, ('SEW307_Day4', 'Evening'): 45, ('SEW301_Day7', 'Morning'): 168, ('SEW301_Day7', 'Afternoon'): 168, ('SEW301_Day7', 'Evening'): 168, ('SEW301_Day3', 'Morning'): 168, ('SEW301_Day3', 'Afternoon'): 168, ('SEW301_Day3', 'Evening'): 168, ('SEW303_Day5', 'Morning'): 45, ('SEW303_Day5', 'Afternoon'): 45, ('SEW303_Day5', 'Evening'): 45, ('SEW303_Day1', 'Morning'): 45, ('SEW303_Day1', 'Afternoon'): 45, ('SEW303_Day1', 'Evening'): 45, ('SEW303_Day4', 'Morning'): 45, ('SEW303_Day4', 'Afternoon'): 45, ('SEW303_Day4', 'Evening'): 45, ('SEW303_Day6', 'Morning'): 45, ('SEW303_Day6', 'Afternoon'): 45, ('SEW303_Day6', 'Evening'): 45, ('SEW303_Day2', 'Morning'): 45, ('SEW303_Day2', 'Afternoon'): 45, ('SEW303_Day2', 'Evening'): 45, ('SEW303_Day7', 'Morning'): 45, ('SEW303_Day7', 'Afternoon'): 45, ('SEW303_Day7', 'Evening'): 45, ('SEW303_Day3', 'Morning'): 45, ('SEW303_Day3', 'Afternoon'): 45, ('SEW303_Day3', 'Evening'): 45, ('SEW305_Day5', 'Morning'): 45, ('SEW305_Day5', 'Afternoon'): 45, ('SEW305_Day5', 'Evening'): 45, ('SEW305_Day1', 'Morning'): 45, ('SEW305_Day1', 'Afternoon'): 45, ('SEW305_Day1', 'Evening'): 45, ('SEW460_Day5', 'Evening'): 20, ('SEW460_Day1', 'Morning'): 20, ('SEW460_Day1', 'Afternoon'): 20, ('SEW460_Day1', 'Evening'): 20, ('SEW460_Day4', 'Morning'): 20, ('SEW460_Day4', 'Afternoon'): 20, ('SEW460_Day4', 'Evening'): 20, ('SEW460_Day6', 'Morning'): 20, ('SEW460_Day6', 'Afternoon'): 20, ('SEW460_Day6', 'Evening'): 20, ('SEW460_Day2', 'Morning'): 20, ('SEW460_Day2', 'Afternoon'): 20, ('SEW460_Day2', 'Evening'): 20, ('SEW460_Day7', 'Morning'): 20, ('SEW460_Day7', 'Afternoon'): 20, ('SEW460_Day7', 'Evening'): 20, ('SEW460_Day3', 'Morning'): 20, ('SEW460_Day3', 'Afternoon'): 20, ('SEW460_Day3', 'Evening'): 20, ('SEW462_Day5', 'Morning'): 17, ('SEW462_Day5', 'Evening'): 17, ('SEW307_Day6', 'Morning'): 45, ('SEW307_Day6', 'Afternoon'): 45, ('SEW307_Day6', 'Evening'): 45, ('SEW307_Day2', 'Morning'): 45, ('SEW307_Day2', 'Afternoon'): 45, ('SEW307_Day2', 'Evening'): 45, ('SEW307_Day7', 'Morning'): 45, ('SEW307_Day7', 'Afternoon'): 45, ('SEW307_Day7', 'Evening'): 45, ('SEW307_Day3', 'Morning'): 45, ('SEW307_Day3', 'Afternoon'): 45, ('SEW307_Day3', 'Evening'): 45, ('SEW309_Day5', 'Morning'): 82, ('SEW309_Day5', 'Afternoon'): 82, ('SEW309_Day5', 'Evening'): 82, ('SEW309_Day1', 'Morning'): 82, ('SEW309_Day1', 'Afternoon'): 82, ('SEW309_Day1', 'Evening'): 82, ('SEW309_Day4', 'Morning'): 82, ('SEW309_Day4', 'Afternoon'): 82, ('SEW309_Day4', 'Evening'): 82, ('SEW309_Day6', 'Morning'): 82, ('SEW309_Day6', 'Afternoon'): 82, ('SEW309_Day6', 'Evening'): 82, ('SEW309_Day2', 'Morning'): 82, ('SEW309_Day2', 'Afternoon'): 82, ('SEW309_Day2', 'Evening'): 82, ('SEW309_Day7', 'Morning'): 82, ('SEW309_Day7', 'Afternoon'): 82, ('SEW309_Day7', 'Evening'): 82, ('SEW309_Day3', 'Morning'): 82, ('SEW309_Day3', 'Afternoon'): 82, ('SEW309_Day3', 'Evening'): 82, ('SEW460_Day5', 'Morning'): 20, ('SEW460_Day5', 'Afternoon'): 20, ('ABL131_Day2', 'Afternoon'): 140, ('ABL131_Day2', 'Evening'): 140, ('ABL131_Day7', 'Morning'): 140, ('ABL131_Day7', 'Afternoon'): 140, ('ABL131_Day7', 'Evening'): 140, ('ABL131_Day3', 'Morning'): 140, ('ABL131_Day3', 'Afternoon'): 140, ('ABL131_Day3', 'Evening'): 140, ('ANH117_Day5', 'Morning'): 59, ('ANH117_Day5', 'Afternoon'): 59, ('ANH117_Day5', 'Evening'): 59, ('ANH117_Day1', 'Morning'): 59, ('ANH117_Day1', 'Afternoon'): 59, ('ANH117_Day1', 'Evening'): 59, ('ANH117_Day4', 'Morning'): 59, ('ANH117_Day4', 'Afternoon'): 59, ('ANH117_Day4', 'Evening'): 59, ('ANH117_Day6', 'Morning'): 59, ('ANH117_Day6', 'Afternoon'): 59, ('ANH117_Day6', 'Evening'): 59, ('ANH117_Day2', 'Morning'): 59, ('ANH117_Day2', 'Afternoon'): 59, ('ANH117_Day2', 'Evening'): 59, ('ABL130_Day5', 'Morning'): 52, ('ABL130_Day5', 'Afternoon'): 52, ('ABL130_Day5', 'Evening'): 52, ('ABL130_Day1', 'Morning'): 52, ('ABL130_Day1', 'Afternoon'): 52, ('ABL130_Day1', 'Evening'): 52, ('ABL130_Day4', 'Morning'): 52, ('ABL130_Day4', 'Afternoon'): 52, ('ABL130_Day4', 'Evening'): 52, ('ABL130_Day6', 'Morning'): 52, ('ABL130_Day6', 'Afternoon'): 52, ('ABL130_Day6', 'Evening'): 52, ('ABL130_Day2', 'Morning'): 52, ('ABL130_Day2', 'Afternoon'): 52, ('ABL130_Day2', 'Evening'): 52, ('ABL130_Day7', 'Morning'): 52, ('ABL130_Day7', 'Afternoon'): 52, ('ABL130_Day7', 'Evening'): 52, ('ABL130_Day3', 'Morning'): 52, ('ABL130_Day3', 'Afternoon'): 52, ('ABL130_Day3', 'Evening'): 52, ('ABL131_Day5', 'Morning'): 140, ('ABL131_Day5', 'Afternoon'): 140, ('ABL131_Day5', 'Evening'): 140, ('ABL131_Day1', 'Morning'): 140, ('ABL131_Day1', 'Afternoon'): 140, ('ABL131_Day1', 'Evening'): 140, ('ABL131_Day4', 'Morning'): 140, ('ABL131_Day4', 'Afternoon'): 140, ('ABL131_Day4', 'Evening'): 140, ('ABL131_Day6', 'Morning'): 140, ('ABL131_Day6', 'Afternoon'): 140, ('ABL131_Day6', 'Evening'): 140, ('ABL131_Day2', 'Morning'): 140, ('BKH116_Day4', 'Evening'): 37, ('BKH116_Day6', 'Morning'): 37, ('BKH116_Day6', 'Afternoon'): 37, ('BKH116_Day6', 'Evening'): 37, ('BKH116_Day2', 'Morning'): 37, ('BKH116_Day2', 'Afternoon'): 37, ('BKH116_Day2', 'Evening'): 37, ('BKH116_Day7', 'Morning'): 37, ('BKH116_Day7', 'Afternoon'): 37, ('BKH116_Day7', 'Evening'): 37, ('BKH116_Day3', 'Morning'): 37, ('BKH116_Day3', 'Afternoon'): 37, ('BKH116_Day3', 'Evening'): 37, ('BKH229_Day5', 'Morning'): 24, ('BKH229_Day5', 'Afternoon'): 24, ('BKH229_Day5', 'Evening'): 24, ('BKH229_Day1', 'Morning'): 24, ('BKH229_Day1', 'Afternoon'): 24, ('BKH229_Day1', 'Evening'): 24, ('BKH229_Day4', 'Morning'): 24, ('BKH229_Day4', 'Afternoon'): 24, ('BKH229_Day4', 'Evening'): 24, ('ANH117_Day7', 'Morning'): 59, ('ANH117_Day7', 'Afternoon'): 59, ('ANH117_Day7', 'Evening'): 59, ('ANH117_Day3', 'Morning'): 59, ('ANH117_Day3', 'Afternoon'): 59, ('ANH117_Day3', 'Evening'): 59, ('BKH102_Day5', 'Morning'): 37, ('BKH102_Day5', 'Afternoon'): 37, ('BKH102_Day5', 'Evening'): 37, ('BKH102_Day1', 'Morning'): 37, ('BKH102_Day1', 'Afternoon'): 37, ('BKH102_Day1', 'Evening'): 37, ('BKH102_Day4', 'Morning'): 37, ('BKH102_Day4', 'Afternoon'): 37, ('BKH102_Day4', 'Evening'): 37, ('BKH102_Day6', 'Morning'): 37, ('BKH102_Day6', 'Afternoon'): 37, ('BKH102_Day6', 'Evening'): 37, ('BKH102_Day2', 'Morning'): 37, ('BKH102_Day2', 'Afternoon'): 37, ('BKH102_Day2', 'Evening'): 37, ('BKH102_Day7', 'Morning'): 37, ('BKH102_Day7', 'Afternoon'): 37, ('BKH102_Day7', 'Evening'): 37, ('BKH102_Day3', 'Morning'): 37, ('BKH102_Day3', 'Afternoon'): 37, ('BKH102_Day3', 'Evening'): 37, ('BKH116_Day5', 'Morning'): 37, ('BKH116_Day5', 'Afternoon'): 37, ('BKH116_Day5', 'Evening'): 37, ('BKH116_Day1', 'Morning'): 37, ('BKH116_Day1', 'Afternoon'): 37, ('BKH116_Day1', 'Evening'): 37, ('BKH116_Day4', 'Morning'): 37, ('BKH116_Day4', 'Afternoon'): 37, ('BRK103_Day2', 'Morning'): 30, ('BRK103_Day2', 'Afternoon'): 30, ('BRK103_Day2', 'Evening'): 30, ('BRK103_Day7', 'Morning'): 30, ('DCH1042_Day6', 'Afternoon'): 46, ('DCH1042_Day6', 'Evening'): 46, ('DCH1042_Day2', 'Morning'): 46, ('DCH1042_Day2', 'Afternoon'): 46, ('DCH1042_Day2', 'Evening'): 46, ('BKH233_Day3', 'Afternoon'): 24, ('BKH233_Day3', 'Evening'): 24, ('BRC282_Day5', 'Morning'): 66, ('BRC282_Day5', 'Afternoon'): 66, ('BRC282_Day5', 'Evening'): 66, ('BRC285_Day3', 'Morning'): 24, ('BRC285_Day3', 'Afternoon'): 24, ('BRC285_Day3', 'Evening'): 24, ('BRC286_Day5', 'Morning'): 32, ('BRK103_Day7', 'Afternoon'): 30, ('BRK103_Day7', 'Evening'): 30, ('BRK103_Day3', 'Morning'): 30, ('BRK103_Day3', 'Afternoon'): 30, ('DCH1042_Day7', 'Morning'): 46, ('DCH1042_Day7', 'Afternoon'): 46, ('DCH1042_Day7', 'Evening'): 46, ('BRC282_Day1', 'Morning'): 66, ('BRC282_Day1', 'Afternoon'): 66, ('BRC282_Day1', 'Evening'): 66, ('BRC286_Day5', 'Afternoon'): 32, ('BRC286_Day5', 'Evening'): 32, ('BRC286_Day1', 'Morning'): 32, ('BRC286_Day1', 'Afternoon'): 32, ('BRK103_Day3', 'Evening'): 30, ('DBH180_Day5', 'Morning'): 87, ('DCH1042_Day3', 'Morning'): 46, ('DCH1042_Day3', 'Afternoon'): 46, ('DCH1042_Day3', 'Evening'): 46, ('BRC282_Day4', 'Morning'): 66, ('BRC282_Day4', 'Afternoon'): 66, ('BRC282_Day4', 'Evening'): 66, ('BRC286_Day1', 'Evening'): 32, ('BRC286_Day4', 'Morning'): 32, ('BRC286_Day4', 'Afternoon'): 32, ('BRC286_Day4', 'Evening'): 32, ('DBH180_Day1', 'Morning'): 87, ('DCH1046_Day5', 'Morning'): 46, ('DCH1046_Day5', 'Afternoon'): 46, ('DCH1046_Day5', 'Evening'): 46, ('DCH1046_Day1', 'Morning'): 46, ('BRC282_Day6', 'Morning'): 66, ('BRC282_Day6', 'Afternoon'): 66, ('BRC282_Day6', 'Evening'): 66, ('BRC282_Day2', 'Morning'): 66, ('BRC282_Day2', 'Afternoon'): 66, ('BRC286_Day6', 'Morning'): 32, ('BRC286_Day6', 'Afternoon'): 32, ('BRC286_Day6', 'Evening'): 32, ('DBH180_Day4', 'Morning'): 87, ('DCH1046_Day1', 'Afternoon'): 46, ('DCH1046_Day1', 'Evening'): 46, ('DCH1046_Day4', 'Morning'): 46, ('DCH1046_Day4', 'Afternoon'): 46, ('BRC282_Day2', 'Evening'): 66, ('BRC282_Day7', 'Morning'): 66, ('BRC282_Day7', 'Afternoon'): 66, ('BRC282_Day7', 'Evening'): 66, ('BRC286_Day2', 'Morning'): 32, ('BRC286_Day2', 'Afternoon'): 32, ('BRC286_Day2', 'Evening'): 32, ('BRC286_Day7', 'Morning'): 32, ('DBH180_Day2', 'Morning'): 87, ('DCH1046_Day4', 'Evening'): 46, ('DCH1046_Day6', 'Morning'): 46, ('DCH1046_Day6', 'Afternoon'): 46, ('DCH1046_Day6', 'Evening'): 46, ('BRC282_Day3', 'Morning'): 66, ('BRC282_Day3', 'Afternoon'): 66, ('BRC282_Day3', 'Evening'): 66, ('BRC286_Day7', 'Afternoon'): 32, ('BRC286_Day7', 'Evening'): 32, ('BRC286_Day3', 'Morning'): 32, ('BRC286_Day3', 'Afternoon'): 32, ('BRC286_Day3', 'Evening'): 32, ('DCH1046_Day2', 'Morning'): 46, ('DCH1046_Day2', 'Afternoon'): 46, ('DCH1046_Day2', 'Evening'): 46, ('BRC284_Day5', 'Morning'): 50, ('BRC284_Day5', 'Afternoon'): 50, ('BRC284_Day5', 'Evening'): 50, ('BRC284_Day1', 'Morning'): 50, ('BRK101_Day5', 'Morning'): 150, ('BRK101_Day5', 'Afternoon'): 150, ('BRK101_Day5', 'Evening'): 150, ('DBH180_Day3', 'Morning'): 87, ('DCC113_Day5', 'Morning'): 99, ('DCH1046_Day7', 'Morning'): 46, ('DCH1046_Day7', 'Afternoon'): 46, ('DCH1046_Day7', 'Evening'): 46, ('DCH1046_Day3', 'Morning'): 46, ('BRC284_Day1', 'Afternoon'): 50, ('BRC284_Day1', 'Evening'): 50, ('BRC284_Day4', 'Morning'): 50, ('BRC284_Day4', 'Afternoon'): 50, ('BRK101_Day1', 'Morning'): 150, ('BRK101_Day1', 'Afternoon'): 150, ('BRK101_Day1', 'Evening'): 150, ('DCC113_Day5', 'Afternoon'): 99, ('DCC113_Day1', 'Morning'): 99, ('DCC113_Day1', 'Afternoon'): 99, ('BKH229_Day6', 'Morning'): 24, ('BKH229_Day6', 'Afternoon'): 24, ('BKH229_Day6', 'Evening'): 24, ('BKH229_Day2', 'Morning'): 24, ('BRC284_Day4', 'Evening'): 50, ('BRC284_Day6', 'Morning'): 50, ('BRC284_Day6', 'Afternoon'): 50, ('BRC284_Day6', 'Evening'): 50, ('BRK101_Day4', 'Morning'): 150, ('BRK101_Day4', 'Afternoon'): 150, ('BRK101_Day4', 'Evening'): 150, ('BRK101_Day6', 'Morning'): 150, ('DCC113_Day4', 'Morning'): 99, ('DCC113_Day4', 'Afternoon'): 99, ('BKH229_Day2', 'Afternoon'): 24, ('BKH229_Day2', 'Evening'): 24, ('BKH229_Day7', 'Morning'): 24, ('BKH229_Day7', 'Afternoon'): 24, ('BKH229_Day7', 'Evening'): 24, ('BRC284_Day2', 'Morning'): 50, ('BRC284_Day2', 'Afternoon'): 50, ('BRC284_Day2', 'Evening'): 50, ('BRK101_Day6', 'Afternoon'): 150, ('BRK101_Day6', 'Evening'): 150, ('BRK101_Day2', 'Morning'): 150, ('BRK101_Day2', 'Afternoon'): 150, ('BRK101_Day2', 'Evening'): 150, ('BKH229_Day3', 'Morning'): 24, ('BKH229_Day3', 'Afternoon'): 24, ('BKH229_Day3', 'Evening'): 24, ('BRC284_Day7', 'Morning'): 50, ('BRC284_Day7', 'Afternoon'): 50, ('BRC284_Day7', 'Evening'): 50, ('BRC284_Day3', 'Morning'): 50, ('BRC284_Day3', 'Afternoon'): 50, ('BRK101_Day7', 'Morning'): 150, ('BRK101_Day7', 'Afternoon'): 150, ('BRK101_Day7', 'Evening'): 150, ('DCC113_Day2', 'Morning'): 99, ('DCC113_Day2', 'Afternoon'): 99, ('BKH233_Day5', 'Morning'): 24, ('BKH233_Day5', 'Afternoon'): 24, ('BKH233_Day5', 'Evening'): 24, ('BKH233_Day1', 'Morning'): 24, ('BRC284_Day3', 'Evening'): 50, ('BRC285_Day5', 'Morning'): 24, ('BRC285_Day5', 'Afternoon'): 24, ('BRC285_Day5', 'Evening'): 24, ('BRK101_Day3', 'Morning'): 150, ('BRK101_Day3', 'Afternoon'): 150, ('BRK101_Day3', 'Evening'): 150, ('DCC113_Day3', 'Morning'): 99, ('DCC113_Day3', 'Afternoon'): 99, ('BKH233_Day1', 'Afternoon'): 24, ('BKH233_Day1', 'Evening'): 24, ('BKH233_Day4', 'Morning'): 24, ('BKH233_Day4', 'Afternoon'): 24, ('BRC285_Day1', 'Morning'): 24, ('BRC285_Day1', 'Afternoon'): 24, ('BRC285_Day1', 'Evening'): 24, ('BRK103_Day5', 'Morning'): 30, ('BRK103_Day5', 'Afternoon'): 30, ('BRK103_Day5', 'Evening'): 30, ('BRK103_Day1', 'Morning'): 30, ('BRK103_Day1', 'Afternoon'): 30, ('DCH1042_Day5', 'Morning'): 46, ('DCH1042_Day5', 'Afternoon'): 46, ('DCH1042_Day5', 'Evening'): 46, ('BKH233_Day4', 'Evening'): 24, ('BKH233_Day6', 'Morning'): 24, ('BKH233_Day6', 'Afternoon'): 24, ('BKH233_Day6', 'Evening'): 24, ('BRC285_Day4', 'Morning'): 24, ('BRC285_Day4', 'Afternoon'): 24, ('BRC285_Day4', 'Evening'): 24, ('BRC285_Day6', 'Morning'): 24, ('BRK103_Day1', 'Evening'): 30, ('BRK103_Day4', 'Morning'): 30, ('BRK103_Day4', 'Afternoon'): 30, ('BRK103_Day4', 'Evening'): 30, ('DCH1042_Day1', 'Morning'): 46, ('DCH1042_Day1', 'Afternoon'): 46, ('DCH1042_Day1', 'Evening'): 46, ('BKH233_Day2', 'Morning'): 24, ('BKH233_Day2', 'Afternoon'): 24, ('BKH233_Day2', 'Evening'): 24, ('BRC285_Day6', 'Afternoon'): 24, ('BRC285_Day6', 'Evening'): 24, ('BRC285_Day2', 'Morning'): 24, ('BRC285_Day2', 'Afternoon'): 24, ('BRC285_Day2', 'Evening'): 24, ('BRK103_Day6', 'Morning'): 30, ('BRK103_Day6', 'Afternoon'): 30, ('BRK103_Day6', 'Evening'): 30, ('DCH1042_Day4', 'Morning'): 46, ('DCH1042_Day4', 'Afternoon'): 46, ('DCH1042_Day4', 'Evening'): 46, ('DCH1042_Day6', 'Morning'): 46, ('BKH233_Day7', 'Morning'): 24, ('BKH233_Day7', 'Afternoon'): 24, ('BKH233_Day7', 'Evening'): 24, ('BKH233_Day3', 'Morning'): 24, ('BRC285_Day7', 'Morning'): 24, ('BRC285_Day7', 'Afternoon'): 24, ('BRC285_Day7', 'Evening'): 24, ('GRBW212_Day2', 'Morning'): 32, ('GRBW212_Day2', 'Afternoon'): 32, ('GRBW212_Day2', 'Evening'): 32, ('GRBW212_Day7', 'Morning'): 32, ('HBH227_Day6', 'Afternoon'): 46, ('HBH227_Day6', 'Evening'): 46, ('HBH227_Day2', 'Morning'): 46, ('HBH227_Day2', 'Afternoon'): 46, ('DCH1064_Day4', 'Morning'): 73, ('DCH1064_Day4', 'Afternoon'): 73, ('DCH1064_Day4', 'Evening'): 73, ('DCH1064_Day6', 'Morning'): 73, ('DCH1020 / SYM II_Day1', 'Morning'): 66, 

In [13]:
#convert to values in write up
S = list(schedule_counts.keys()) #set of all unique schedules
N_t = schedule_counts      #num of people with a given unique schedule
E = set(set_of_exams)
E_p = set(in_person_exams)
E_o = online_exams
d_E = exam_demand
R = all_slots
R_p = in_person_slots
R_o = online_slots
c_R = slot_capacities

In [14]:
large = {'PSYC101', 'CHEM121'}
E = E - large
E_p = E_p - large

In [15]:
# Define the first stage model

day_pairs = range(1, 7)

x_vars = [(slot,exam) for slot in R for exam in E]

y_vars = [(schedule, day) for schedule in S for day in day_pairs]

z_vars = [(slot, exam) for slot in R_p for exam in E_p]

model1 = gp.Model("First Stage Model")

# Add variables
x = model1.addVars(x_vars, vtype=GRB.BINARY, name="x variables")

y = model1.addVars(y_vars, lb = 0, name="y variables") #Relaxed into continuous vars

z = model1.addVars(z_vars, lb = 0, name="z variables") #Relaxed into continuous vars

# Add Objective Function

#obj1 = gp.quicksum(N_t[s] * gp.quicksum(y_vars[s,d] for d in day_pairs) for s in S)
obj1 = gp.quicksum(N_t[s] * gp.quicksum(y[s, d] for d in day_pairs) for s in S)


obj2 = gp.quicksum(z[r,e] for r in R_p for e in E_p)

model1.setObjective(obj1 + obj2, GRB.MINIMIZE)

Set parameter Username
Academic license - for non-commercial use only - expires 2025-01-24

In [16]:
# Add Constraints

#capacity constraints & capacity relaxation measure
for exam in E_p: 
    for slot in R_p:
        if c_R[slot] <= d_E[exam]: 
            model1.addConstr(x[slot,exam] == 0, name=f"capacity_constraint_{slot}_{exam}" ) 
            #model1.addConstr(z[slot,exam] == 0, name = "capacity_relaxation")
        else: 
            model1.addConstr(z[slot,exam] >= (2*d_E[exam] - c_R[slot])*x[slot,exam],
             name = f"capacity_relaxation_{slot}_{exam}")


for exam in E_p: 
    for slot in R_o:
        model1.addConstr(x[slot,exam] == 0, name = f"in_person_constraint_{slot}_{exam}")

for exam in E_o:
    for slot in R_p:
        model1.addConstr(x[slot,exam] == 0, name = f"online_constraint_{slot}_{exam}")
    
for exam in E:
    model1.addConstr(gp.quicksum(x[slot,exam] for slot in R) == 1, name = f"one_slot_per_exam_{exam}")

for r in R_p:
    model1.addConstr(gp.quicksum(x[r,e] for e in E_p) <= 1, name = f"at_most_one_in_person_{r}")

#
""" for i in range(1, 7):
    consecutive_slots = []
    for j in R:
        slot_day = j[0].split('_')[1]
        if (slot_day == f'Day{i}') or (slot_day == f'Day{i+1}'):
            consecutive_slots.append(j)
    for schedule in S:
        model1.addConstr(gp.quicksum(x[(r, e)] for r in consecutive_slots for e in set(schedule).intersection(E)) <= 2 + y[schedule, i], "y Violations") """

for i in range(1, 7):
    consecutive_slots = []
    for j in R:
        slot_day = j[0].split('_')[1]
        if (slot_day == f'Day{i}') or (slot_day == f'Day{i+1}'):
            consecutive_slots.append(j)
    for schedule in S:
        required_exams = set(schedule).intersection(E)
        if required_exams:
            # Ensure that the sum of x for required exams in consecutive slots is not more than 2 plus the corresponding y value
            model1.addConstr(
                gp.quicksum(x[r, e] for r in consecutive_slots for e in required_exams) <= 2 + y[schedule, i],
                name=f"y_Violations_schedule{S.index(schedule)}_day{i}"
            )

In [18]:
model1.setParam('TimeLimit', 300)
model1.optimize()
print(model1.status)

if model1.status == GRB.OPTIMAL:
    print('Optimal solution found.')

    # Retrieve the values of the variables in the optimal solution
    x_values = model1.getAttr('X', x)
    y_values = model1.getAttr('X', y)
    z_values = model1.getAttr('X', z)

    # Print the values of the variables
    print('x variables:')
    x_dict = {}
    for var in x_values:
        x_dict[var] =x_values[var]

    print('y variables:')
    y_dict = {}
    for var in y_values:
        y[var] = y_values[var]
    print('z variables:')
    z_dict = {}
    for var in z_values:
        z_dict[var] = z_values[var]


if model1.status == GRB.INFEASIBLE:
    model1.computeIIS()

    # Print out the constraints that are part of the IIS
    for c in model1.getConstrs():
        if c.IISConstr:
            print('Infeasible constraint:', c.constrName)

Gurobi Optimizer version 10.0.1 build v10.0.1rc0 (mac64[rosetta2])

CPU model: Apple M2
Thread count: 8 physical cores, 8 logical processors, using up to 8 threads

Optimize a model with 528867 rows, 979622 columns and 33415627 nonzeros
Model fingerprint: 0xadbd48ae
Variable types: 489622 continuous, 490000 integer (490000 binary)
Coefficient statistics:
  Matrix range     [1e+00, 3e+02]
  Objective range  [1e+00, 6e+01]
  Bounds range     [1e+00, 1e+00]
  RHS range        [1e+00, 2e+00]
Presolved: 9701 rows, 331080 columns, 5078731 nonzeros

Continuing optimization...


Cutting planes:
  MIR: 4
  Zero half: 10

Explored 1 nodes (61590 simplex iterations) in 3.42 seconds (0.00 work units)
Thread count was 8 (of 8 available processors)

Solution count 9: 1132 1137 1140 ... 4055

Optimal solution found (tolerance 1.00e-04)
Best objective 1.132000000000e+03, best bound 1.132000000000e+03, gap 0.0000%
2
Optimal solution found.
x variables:
y variables:
z variables:

In [ ]:
x_values = model1.getAttr('X', x)
# y_values = model1.getAttr('X', y)
z_values = model1.getAttr('X', z)

# Print the values of the variables
print('x variables:')
x_dict = {}
for var in x_values:
    x_dict[var] =x_values[var]

print('y variables:')
y_dict = {}
for var in y_values:
    y[var] = y_values[var]

print('z variables:')
z_dict = {}
for var in z_values:
    z_dict[var] = z_values[var]

keys_equal_to_1 = set([key[1] for key, value in x_dict.items() if value == 1])
keys_equal_to_1

x variables:
y variables:
z variables:

{'ANTH200',
 'ANTH205',
 'ARCH311',
 'ARCH423',
 'ASIA322',
 'ASTR101',
 'ASTR102',
 'ASTR350',
 'ASTR451',
 'ASTR470',
 'BIOE123',
 'BIOE252',
 'BIOE341',
 'BIOE383',
 'BIOE385',
 'BIOE420',
 'BIOE422',
 'BIOE440',
 'BIOE446',
 'BIOE449',
 'BIOE451',
 'BIOS122',
 'BIOS201',
 'BIOS202',
 'BIOS300',
 'BIOS301',
 'BIOS312',
 'BIOS329',
 'BIOS341',
 'BIOS344',
 'BIOS352',
 'BIOS353',
 'BIOS372',
 'BIOS385',
 'BIOS441',
 'BUSI222',
 'BUSI224',
 'BUSI305',
 'BUSI310',
 'BUSI343',
 'BUSI390',
 'BUSI395',
 'BUSI401',
 'BUSI430',
 'BUSI440',
 'BUSI461',
 'CEVE211',
 'CEVE302',
 'CEVE325',
 'CEVE400',
 'CEVE426',
 'CEVE431',
 'CEVE460',
 'CEVE471',
 'CEVE476',
 'CHBE301',
 'CHBE390',
 'CHBE401',
 'CHBE412',
 'CHBE418',
 'CHBE420',
 'CHBE468',
 'CHBE470',
 'CHEM201',
 'CHEM211',
 'CHEM219',
 'CHEM313',
 'CHEM401',
 'CHEM430',
 'CHEM452',
 'CHEM462',
 'CHEM496',
 'CMOR302',
 'CMOR304',
 'CMOR360',
 'CMOR405',
 'CMOR410',
 'CMOR420',
 'CMOR422',
 'CMOR441',
 'CMOR451',
 'CMOR462',
 'CMOR494',
 'CMST203',
 'COMP140',
 'COMP182',
 'COMP301',
 'COMP310',
 'COMP311',
 'COMP326',
 'COMP382',
 'COMP390',
 'COMP413',
 'COMP416',
 'COMP417',
 'COMP429',
 'COMP431',
 'COMP442',
 'COMP450',
 'COMP462',
 'COMP480',
 'COMP490',
 'COMP491',
 'DSCI301',
 'DSCI303',
 'DSCI304',
 'ECON200',
 'ECON203',
 'ECON209',
 'ECON210',
 'ECON300',
 'ECON305',
 'ECON307',
 'ECON308',
 'ECON437',
 'ECON481',
 'ECON483',
 'ECON497',
 'EEPS101',
 'EEPS106',
 'EEPS110',
 'EEPS115',
 'EEPS322',
 'EEPS410',
 'EEPS412',
 'EEPS418',
 'EEPS430',
 'EEPS438',
 'EEPS445',
 'EEPS454',
 'EEPS459',
 'EEPS465',
 'EEPS468',
 'EEPS471',
 'ELEC261',
 'ELEC303',
 'ELEC326',
 'ELEC361',
 'ELEC426',
 'ELEC429',
 'ELEC434',
 'ELEC450',
 'EMSP281',
 'EMSP282',
 'ENGI120',
 'ENGI200',
 'ENGI220',
 'ENGI300',
 'ENGI302',
 'ENGI355',
 'ENST315',
 'ENST437',
 'FILM434',
 'FREN424',
 'FWIS166',
 'FWIS188',
 'FWIS195',
 'GLHT449',
 'GLHT451',
 'HEAL103',
 'HIST256',
 'HIST319',
 'HIST340',
 'HIST372',
 'HIST391',
 'HUMA315',
 'ITAL141',
 'ITAL301',
 'JWST318',
 'LEAD260',
 'LING200',
 'LING305',
 'LING397',
 'LING401',
 'MATH101',
 'MATH102',
 'MATH111',
 'MATH211',
 'MATH212',
 'MATH300',
 'MATH302',
 'MATH304',
 'MATH321',
 'MATH354',
 'MATH355',
 'MATH423',
 'MDHM359',
 'MECH202',
 'MECH203',
 'MECH211',
 'MECH343',
 'MECH371',
 'MECH400',
 'MECH450',
 'MECH477',
 'MECH490',
 'MSNE402',
 'MSNE406',
 'MUSI421',
 'NAVA101',
 'NAVA203',
 'NAVA403',
 'NEUR362',
 'NEUR441',
 'PHYS101',
 'PHYS111',
 'PHYS125',
 'PHYS411',
 'PHYS413',
 'PHYS425',
 'PLST315',
 'POLI210',
 'POLI211',
 'POLI212',
 'POLI260',
 'POLI321',
 'POLI339',
 'POLI354',
 'POLI395',
 'PSYC203',
 'PSYC308',
 'PSYC321',
 'PSYC340',
 'PSYC351',
 'PSYC353',
 'PSYC362',
 'PSYC467',
 'RELI307',
 'RELI322',
 'SMGT360',
 'SOCI231',
 'SOCI301',
 'SOPA200',
 'SOPA309',
 'SOPA400',
 'SOSC302',
 'SOSC444',
 'STAT280',
 'STAT305',
 'STAT310',
 'STAT315',
 'STAT413',
 'STAT418',
 'STAT425',
 'STAT440',
 'STAT450',
 'SWGS101',
 'SWGS318',
 'SWGS345',
 'SWGS424'}

In [ ]:
keys_equal_to_1 = [key for key, value in z_dict.items() if value != 0]
keys_equal_to_1

[(('HRZAMP_Day5', 'Morning'), 'MATH212'),
 (('HRZAMP_Day5', 'Afternoon'), 'MATH102'),
 (('HRZAMP_Day5', 'Evening'), 'MATH101'),
 (('HRZAMP_Day1', 'Afternoon'), 'PSYC203'),
 (('HRZAMP_Day1', 'Evening'), 'BUSI310'),
 (('HRZAMP_Day4', 'Afternoon'), 'PHYS125'),
 (('HRZAMP_Day4', 'Evening'), 'BIOS341'),
 (('HRZAMP_Day7', 'Morning'), 'STAT310'),
 (('HRZAMP_Day7', 'Afternoon'), 'CHEM211'),
 (('HRZAMP_Day7', 'Evening'), 'MATH355'),
 (('HRZAMP_Day3', 'Afternoon'), 'PHYS101')]

In [ ]:
# Assuming initial setups are as previously defined
""" E = set(...)  # Set of all offered exams
E_p = set(...)  # Set of in-person offered exams
d_E = {...}  # Dictionary mapping each exam to its demand
S = [...]  # List of unique schedules (each schedule is a set of exam codes)
N_t = {...}  # Dictionary mapping each unique schedule to the number of students """
#convert to values in write up
S = list(schedule_counts.keys()) #set of all unique schedules
N_t = schedule_counts      #num of people with a given unique schedule
E = set(set_of_exams)
E_p = set(in_person_exams)
E_o = online_exams
d_E = exam_demand
R = all_slots
R_p = in_person_slots
R_o = online_slots
c_R = slot_capacities
divide_exams = ['PSYC101', 'CHEM121', 'MATH212', 'STAT310', 'MATH102', 'CHEM211', 'MATH101', 'PHYS125', 'BIOS341', 
                'BUSI310', 'PSYC203', 'MATH355', 'PHYS101']  # Exams to be divided into Part A and B


exam_counters = {exam: 0 for exam in divide_exams}  # Tracks encounters for dividing

for E_X in divide_exams:
    # Update E and E_p for each divided exam
    E.discard(E_X)
    E.update({f'{E_X}_A', f'{E_X}_B'})
    if E_X in E_p:
        E_p.discard(E_X)
        E_p.update({f'{E_X}_A', f'{E_X}_B'})

    # Update d_E
    if E_X in d_E:
        VAL = d_E[E_X] / 2
        d_E[f'{E_X}_A'] = VAL
        d_E[f'{E_X}_B'] = VAL
        del d_E[E_X]

# Update S and N_t with alternating Part A and Part B assignments
new_S = []
new_N_t = {}

for schedule in S:
    updated_schedule = set(schedule)  # Start with a copy of the current schedule
    for E_X in divide_exams:
        if E_X in updated_schedule:
            # Determine whether to use Part A or Part B based on the current count
            part_suffix = '_A' if exam_counters[E_X] % 2 == 0 else '_B'
            updated_schedule.discard(E_X)
            updated_schedule.add(f'{E_X}{part_suffix}')

            # Update the exam counter for this divided exam
            exam_counters[E_X] += 1

    # Convert updated_schedule set to a tuple for use as a dictionary key
    schedule_tuple = tuple(sorted(updated_schedule))  # Sorting to ensure consistency
    new_S.append(updated_schedule)
    # Update or add the new schedule in new_N_t, accumulating counts if necessary
    if schedule_tuple in new_N_t:
        new_N_t[schedule_tuple] += N_t[tuple(sorted(schedule))]
    else:
        new_N_t[schedule_tuple] = N_t[tuple(sorted(schedule))]

# Replace old S and N_t with new ones, converting new_S sets to sorted tuples
S = [tuple(sorted(sch)) for sch in new_S]
N_t = new_N_t

In [ ]:
day_pairs = range(1, 7)

x_vars = [(slot,exam) for slot in R for exam in E]

y_vars = [(schedule, day) for schedule in S for day in day_pairs]

z_vars = [(slot, exam) for slot in R_p for exam in E_p]

model1 = gp.Model("First Stage Model")

# Add variables
x = model1.addVars(x_vars, vtype=GRB.BINARY, name="x variables")

y = model1.addVars(y_vars, lb = 0, name="y variables") #Relaxed into continuous vars

z = model1.addVars(z_vars, lb = 0, name="z variables") #Relaxed into continuous vars

# Add Objective Function

#obj1 = gp.quicksum(N_t[s] * gp.quicksum(y_vars[s,d] for d in day_pairs) for s in S)
obj1 = gp.quicksum(N_t[s] * gp.quicksum(y[s, d] for d in day_pairs) for s in S)


obj2 = gp.quicksum(z[r,e] for r in R_p for e in E_p)

model1.setObjective(obj1 + obj2, GRB.MINIMIZE)

# Add Constraints

#capacity constraints & capacity relaxation measure
for exam in E_p: 
    for slot in R_p:
        if c_R[slot] <= d_E[exam]: 
            model1.addConstr(x[slot,exam] == 0, name=f"capacity_constraint_{slot}_{exam}" ) 
            #model1.addConstr(z[slot,exam] == 0, name = "capacity_relaxation")
        else: 
            model1.addConstr(z[slot,exam] >= (2*d_E[exam] - c_R[slot])*x[slot,exam],
             name = f"capacity_relaxation_{slot}_{exam}")


for exam in E_p: 
    for slot in R_o:
        model1.addConstr(x[slot,exam] == 0, name = f"in_person_constraint_{slot}_{exam}")

for exam in E_o:
    for slot in R_p:
        model1.addConstr(x[slot,exam] == 0, name = f"online_constraint_{slot}_{exam}")
    
for exam in E:
    model1.addConstr(gp.quicksum(x[slot,exam] for slot in R) == 1, name = f"one_slot_per_exam_{exam}")

for r in R_p:
    model1.addConstr(gp.quicksum(x[r,e] for e in E_p) <= 1, name = f"at_most_one_in_person_{r}")


for i in range(1, 7):
    consecutive_slots = []
    for j in R:
        slot_day = j[0].split('_')[1]
        if (slot_day == f'Day{i}') or (slot_day == f'Day{i+1}'):
            consecutive_slots.append(j)
    for schedule in S:
        required_exams = set(schedule).intersection(E)
        if required_exams:
            # Ensure that the sum of x for required exams in consecutive slots is not more than 2 plus the corresponding y value
            model1.addConstr(
                gp.quicksum(x[r, e] for r in consecutive_slots for e in required_exams) <= 2 + y[schedule, i],
                name=f"y_Violations_schedule{S.index(schedule)}_day{i}"
            )

In [ ]:
model1.setParam('TimeLimit', 300)
model1.optimize()

Set parameter TimeLimit to value 300
Gurobi Optimizer version 10.0.1 build v10.0.1rc0 (mac64[rosetta2])

CPU model: Apple M2
Thread count: 8 physical cores, 8 logical processors, using up to 8 threads

Optimize a model with 558504 rows, 1038107 columns and 35834812 nonzeros
Model fingerprint: 0x3647057e
Variable types: 518707 continuous, 519400 integer (519400 binary)
Coefficient statistics:
  Matrix range     [1e+00, 3e+02]
  Objective range  [1e+00, 6e+01]
  Bounds range     [1e+00, 1e+00]
  RHS range        [1e+00, 2e+00]
Found heuristic solution: objective 4778.0000000
Presolve removed 328102 rows and 252216 columns (presolve time = 6s) ...
Presolve removed 530782 rows and 443262 columns (presolve time = 11s) ...
Presolve removed 530782 rows and 684403 columns (presolve time = 15s) ...
Presolve removed 530782 rows and 684403 columns (presolve time = 20s) ...
Presolve removed 539290 rows and 692935 columns (presolve time = 30s) ...
Presolve removed 539290 rows and 692935 columns (presolve time = 30s) ...
Presolve removed 546628 rows and 700273 columns (presolve time = 35s) ...
Presolve removed 546628 rows and 700273 columns (presolve time = 40s) ...
Presolve removed 546628 rows and 700273 columns
Presolve time: 43.16s
Presolved: 11876 rows, 337834 columns, 5873259 nonzeros
Variable types: 0 continuous, 337834 integer (328170 binary)
Found heuristic solution: objective 2065.0000000
Deterministic concurrent LP optimizer: primal simplex, dual simplex, and barrier
Showing barrier log only...

Root barrier log...

Ordering time: 4.16s

Barrier performed 0 iterations in 57.31 seconds (28.28 work units)
Barrier solve interrupted - model solved by another algorithm

Concurrent spin time: 4.18s (can be avoided by choosing Method=3)

Solved with dual simplex

Root relaxation: objective 1.360000e+02, 2197 iterations, 10.36 seconds (3.70 work units)
Total elapsed time = 60.03s
Total elapsed time = 66.43s

    Nodes    |    Current Node    |     Objective Bounds      |     Work
 Expl Unexpl |  Obj  Depth IntInf | Incumbent    BestBd   Gap | It/Node Time

     0     0  136.00000    0  219 2065.00000  136.00000  93.4%     -   71s
H    0     0                     511.0000000  136.00000  73.4%     -   73s
H    0     0                     331.0000000  136.00000  58.9%     -   75s
H    0     0                     193.0000000  136.00000  29.5%     -   75s
     0     0  136.00000    0  197  193.00000  136.00000  29.5%     -   81s
H    0     0                     152.0000000  136.00000  10.5%     -  123s
     0     0  136.00000    0  191  152.00000  136.00000  10.5%     -  130s
H    0     0                     147.0000000  136.00000  7.48%     -  133s
     0     0  136.00000    0  187  147.00000  136.00000  7.48%     -  134s
     0     0  136.00000    0  192  147.00000  136.00000  7.48%     -  145s
     0     0  136.00000    0  179  147.00000  136.00000  7.48%     -  152s
     0     0  136.00000    0  173  147.00000  136.00000  7.48%     -  160s
     0     0  136.00000    0  161  147.00000  136.00000  7.48%     -  171s
     0     0  136.00000    0  158  147.00000  136.00000  7.48%     -  173s
     0     0  136.00000    0  154  147.00000  136.00000  7.48%     -  180s
     0     0  136.00000    0  152  147.00000  136.00000  7.48%     -  183s
     0     0  136.00000    0  167  147.00000  136.00000  7.48%     -  204s
     0     0  136.00000    0  162  147.00000  136.00000  7.48%     -  207s
     0     0  136.00000    0  139  147.00000  136.00000  7.48%     -  213s
     0     0  136.00000    0  139  147.00000  136.00000  7.48%     -  220s
H    0     0                     145.0000000  136.00000  6.21%     -  253s
     0     0  136.00000    0  139  145.00000  136.00000  6.21%     -  300s

Cutting planes:
  MIR: 13

Explored 1 nodes (66812 simplex iterations) in 302.24 seconds (223.07 work units)
Thread count was 8 (of 8 available processors)

Solution count 8: 145 147 152 ... 4778

Time limit reached
Best objective 1.450000000000e+02, best bound 1.360000000000e+02, gap 6.2069%

In [ ]:
if model1.status == GRB.OPTIMAL or model1.SolCount > 0:
    print('Optimal or best solution found.')

    # Retrieve the values of the variables in the optimal solution
    x_values = model1.getAttr('X', x)
    y_values = model1.getAttr('X', y)
    z_values = model1.getAttr('X', z)

    # Print the values of the variables
    #print('x variables:')
    x_dict = {}
    for var in x_values:
        x_dict[var] =x_values[var]

    #print('y variables:')
    y_dict = {}
    for var in y_values:
        y[var] = y_values[var]

    #print('z variables:')
    z_dict = {}
    for var in z_values:
        z_dict[var] = z_values[var]


if model1.status == GRB.INFEASIBLE:
    model1.computeIIS()

    # Print out the constraints that are part of the IIS
    for c in model1.getConstrs():
        if c.IISConstr:
            print('Infeasible constraint:', c.constrName)

Optimal or best solution found.

AttributeError: 'float' object has no attribute '_typeenum'

In [55]:
x_values = model1.getAttr('X', x)
# y_values = model1.getAttr('X', y)
z_values = model1.getAttr('X', z)

# Print the values of the variables
print('x variables:')
x_dict = {}
for var in x_values:
    x_dict[var] =x_values[var]

print('y variables:')
y_dict = {}
for var in y_values:
    y[var] = y_values[var]

print('z variables:')
z_dict = {}
for var in z_values:
    z_dict[var] = z_values[var]

keys_equal_to_1 = set([key[1] for key, value in z_dict.items() if value == 1])
keys_equal_to_1

x variables:
y variables:
z variables:

set()

In [ ]:
#Q = {{comp140_1, comp140_2}, {psyc_1, psyc_part2} ,,, }

In [53]:
from collections import defaultdict

exam_date_map = {}
for slot, cls in in_person_slots:
    # Extract day number and convert it to an integer
    day_num = int(slot.split('Day')[-1])
    exam_date_map[cls] = day_num

student_exam_dates = defaultdict(set)
for idx, classes in enumerate(S):
    for cls in classes:  # Iterating through each class in the tuple
        if cls in exam_date_map:
            student_exam_dates[idx].add(exam_date_map[cls])

# Re-identify students with exams on consecutive days, using the adjusted mapping
students_with_consecutive_exams = 0
for exam_dates in student_exam_dates.values():
    sorted_dates = sorted(exam_dates)
    for i in range(len(sorted_dates) - 1):
        if sorted_dates[i] + 1 == sorted_dates[i + 1]:
            students_with_consecutive_exams += 1
            break

print("Number of Students with at least 2 exams on back to back days:", students_with_consecutive_exams)
        

#number of studnets with an exam on the same day

students_with_same_day_exams = 0

# Iterate through each student's schedule
for classes in S:
    # Aggregate exam days for this student
    student_exam_days = defaultdict(int)  # Default to 0 for any new day
    for cls in classes:
        if cls in exam_date_map:
            student_exam_days[exam_date_map[cls]] += 1  # Increment the count for the exam day of this class
    
    # Check if the student has more than one exam on any day
    if any(count > 1 for count in student_exam_days.values()):
        students_with_same_day_exams += 1

print("Number of Students with an exam on the same day:", students_with_same_day_exams)

#number of students with overlaps

# First, we need to map exams not just to days but to day and time slots to check for time conflicts
exam_datetime_map = {}
for slot, cls in in_person_slots:
    # Convert day and time to a unique identifier for simplicity
    day_time = f"{slot[0]}_{slot[1]}"  # Combines day and time into a single string
    exam_datetime_map[cls] = day_time

# Map students to the day and time slots of their exams
student_exam_datetimes = defaultdict(set)
for idx, classes in enumerate(S):
    for cls in classes:
        if cls in exam_datetime_map:
            student_exam_datetimes[idx].add(exam_datetime_map[cls])

# Identify students with time conflicts in their exams
students_with_time_conflicts = 0
for exam_datetimes in student_exam_datetimes.values():
    if len(exam_datetimes) != len(set(exam_datetimes)):
        students_with_time_conflicts += 1

print("Number of Students with an exam at the same time of another exam:", students_with_time_conflicts)

total_days_between_exams = 0
total_intervals_counted = 0

for exam_dates in student_exam_dates.values():
    sorted_dates = sorted(exam_dates)
    for i in range(len(sorted_dates) - 1):
        days_between = sorted_dates[i + 1] - sorted_dates[i]
        total_days_between_exams += days_between
        total_intervals_counted += 1

# Calculate the average, avoiding division by zero
average_days_between_exams = (total_days_between_exams / total_intervals_counted) if total_intervals_counted else 0

print("Average number of days between two exams", average_days_between_exams)

Number of Students with at least 2 exams on back to back days: 0
Number of Students with an exam on the same day: 0
Number of Students with an exam at the same time of another exam: 0
Average number of days between two exams 0